### PR TITLE
patch for #3647: notify=yes|no|explicit option

### PR DESCRIPTION
**Pull request by klaus3000**
I applied the patch in the online editor of github, I hope I didn't broke the patch.

### CODE REVIEW

**Comment by Habbie** [comment]
Please also update pdns.conf-dist. I did not check if there were other reasons that Travis is unhappy.

**Comment by klaus3000** [comment]
Thanks for reviewing.

First we should decide on which patch to use, there is "notify=yes|no|explicit" or "notify-type=default|explicit" in #3649. Please see discussion in #3647.

Second, the pdns.conf-dist begins with "# Autogenerated configuration file template". Thus I expected that it will be autogenerated. Isn't it? Then we should remove this header too.

**Comment by mind04** [comment]
Why do we need a new config option for this? Add some logic to skip the NS lookup if only-notify is empty and you are done.

And if we need one, i like a more self describing one, like 'notify-nsset=yes/no"

**Comment by klaus3000** [comment]
I realized that there is no option needed. just fixed the only-notify option, see #3890

**Pull request closed without merging**
