### PR TITLE
Set DNSName metatable __eq function

### PR DESCRIPTION
**Pull request by tcely**
I believe this or something like it resolves issue #4552.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
@cmouse

**Comment by cmouse** [comment]
Can I integrate this merge into #5390 or should it be merged separately? Also I think we should leave "__eq" function as well as some ppl might be using it?

**Comment by Habbie** [comment]
Well, do we even need this one if we merge #5390? It's unclear to me.

**Comment by cmouse** [comment]
Yes. It's still needed, #5390 only moves code around and adds stuff. I'll try and see if this works as advertized as it seems much cleaner way to implement `__eq` than the one I made for LuaWrapper.

**Comment by cmouse** [comment]
This does not appear to work as expected, comparing two instances of DNSName do not actually invoke the lambda function.

**Comment by tcely** [comment]
The way luawrapper constructs new metatables for each userdata type makes this slightly more painful than I had hoped, but wrapping this in a lua class that adds the missing functions to the newly created userdata instances allowed this to be mostly hidden from the lua script.

**Comment by cmouse** [comment]
Unfortunately this still does not work as it should. When comparing against a C++ provided DNSName it invokes the __call method, but does not result in correct comparison. 

Tested using
```.cc
BOOST_AUTO_TEST_CASE(test_prequery) {
  const std::string script =
"function prequery(q)\n"
"  print(\"prequery\")\n"
"  if q.qdomain == DNSName(\"mod.unit.test.\")\n"
"  then\n"
"    print(\"true branch\")\n"
"    return true\n"
"  end\n"
"  print(\"false branch\")\n"
"  return false\n"
"end";
  AuthLua4 lua;
  DNSPacket *p = new DNSPacket(true);
  p->qdomain = DNSName("mod.unit.test.");
  lua.loadString(script);
  DNSPacket *r;
  try {
    r = lua.prequery(p);
    if (r != NULL)
      BOOST_CHECK_EQUAL(r->qdomain.toString(), "mod.unit.test.");
  } catch (const LuaContext::ExecutionErrorException& e) {
    try {
     std::rethrow_if_nested(e);
    } catch(const std::exception& exp) {
     theL()<<"Extra info: "<<exp.what();
    }
  }
  delete r;
  delete p;
}
```

**Comment by tcely** [comment]
You will need to wrap the raw userdata like this:

`if DNSName(q.qdomain) == DNSName('mod.unit.test.')`

It's not perfect integration between lua and C++ but the syntax is friendlier than before.

**Comment by cmouse** [comment]
Personally I think that https://github.com/ahupowerdns/luawrapper/pull/35 makes more sense now.

**Comment by Habbie** [comment]
@cmouse @tcely is this still useful since we merged similar work from @cmouse ?

**Comment by tcely** [comment]
At a first glance, I'm going with no.

A few concepts might be pulled out of this for the current code. It looks like LuaContext is often overwriting the metatable which makes persisting the functions more difficult. If the current syntax is working and good enough I don't see a reason to maintain the wrapped objects.

**Comment by Habbie** [comment]
Thanks, then I'm closing this.

**Pull request closed without merging**
