### PR TITLE
auth: Clear caches (meta-data, keys) on domain deletion

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Alternative fix for #7407.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mind04** [comment]
What about clearing the packet cache and maybe even more important the query cache?

**Comment by rgacogne** [comment]
> What about clearing the packet cache and maybe even more important the query cache?

It would make a lot of sense, yes, I'll add a `purgeAuthCachesExact(zonename);`.

**Comment by rgacogne** [comment]
> It would make a lot of sense, yes, I'll add a `purgeAuthCachesExact(zonename);`.

Or not 'Exact', actually.

**Comment by zeha** [comment]
👍

**Comment by rgacogne** [comment]
Done.

**Comment by rgacogne** [comment]
> Would it make sense to also clear caches in pdnsutil `deleteZone()` ?

I believe it would, but I don't think we can do that from `pdnsutil`, can we?

**Pull request merged**
