### PR TITLE
auth: cleanup warnings in ueberbackend, dbdnsseckeeper

### PR DESCRIPTION
**Pull request by zeha**
### Short description
Should clean up:
```
>>>     CID 1435947:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "d_qtype" is not initialized in this constructor nor in any functions that it calls.
>>>     CID 1030015:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "zoneId" is not initialized in this constructor nor in any functions that it calls.
```

and:

```
dbdnsseckeeper.cc:621:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
rrsig = std::move(getRR<RRSIGRecordContent>(dzr.dr));
```

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mind04** [comment]
Moving d_type to handle is not obvious to me. Handle is somewhat special and passed around to various backends. Since the backends do not use the lookup qtype, this is in my opinion is not the place to store it.
I prefer to not move d_qtype and just initialize the variables.

**Comment by zeha** [comment]
To me, `d_handle` looked like the internal state for `get()`.

What's confusing me a bit more, is why we have `d_handle` **and** `d_question`.

Maybe we should get rid of `d_handle` instead. 🤷🏻

**Comment by Habbie** [comment]
I'd also prefer the simpler version where we initialise the variables that were uninitialised. If the backend does not need something, it does not need to be moved into d_handle - things are confusing enough as they are :)

**Comment by zeha** [comment]
ok, will change in a moment

**Comment by zeha** [comment]
Done!

**Review by mind04 — APPROVED** [review]

**Review by Habbie — APPROVED** [review]

**Pull request merged**
