### PR TITLE
Systemd improvements

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by zeha** [comment]
Feeling uneasy about the systemcallfilter, who's going to tell us that the filter needs updating before a release?

**Comment by ahupowerdns** [comment]
While this is astounding work (thanks) this will need thoughts on how it should be (a)part of PowerDNS.

**Comment by rubenk** [comment]
@zeha good point, although I don't expect pdns to gain a lot more syscalls, testing this is tricky.
How about we leave that change out for now?

**Comment by zeha** [comment]
Yeah, skipping the syscall thing works for me (:

**Comment by rubenk** [comment]
Ok, I dropped the syscall thing :)

**Comment by mortenstevens** [comment]
looks good for me :+1:

**Pull request merged**
