### PR TITLE
listen on 127.0.0.1 during regression tests

### PR DESCRIPTION
**Pull request by tcely**
### Short description
Added an address variable to regression-tests set to 127.0.0.1

Issue #2835 

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
Do you think you can add an easy way to override this? An environment variable from outside perhaps?

**Comment by Habbie** [comment]
Hmm, this does not actually address #2835 as for v6 we still listen on :: with this.

**Comment by tcely** [comment]
I didn't see IPv6 mentioned in that issue, but we could always include `--local-ipv6=::1` if that would be desirable.

At this point though, I'd suggest a common flags file that these backend files all include instead of environment variables.

**Comment by Habbie** [comment]
No, I only noticed v6 being an issue when I tested your patch. I agree on all this duplication being bad. I'm happy merging this as is and updating the ticket so somebody can go deeper when they have time.

**Pull request merged**
