### PR TITLE
Add a simple fuzzing target for YaHTTP

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Since we use YaHTTP to parse incoming web requests (and responses in the remote HTTP backend), better fuzz it :)

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]
not an expert on the fuzzing infra, but I see nothing obviously wrong here

**Comment by rgacogne** [comment]
The CIFuzz build fails because the YaHTTP lib has not been built at that point. I need to either find a way to make that a dependency, or to modify the OSSFuzz build process to build YaHTTP beforehand.

**Comment by rgacogne** [comment]
In the end I modified the OSSFuzz build process to build YaHTTP beforehand.

**Comment by rgacogne** [comment]
Reminder to self: please submit the change to the oss-fuzz repository so that the new corpus for the YaHTTP fuzzing target is actually used.

**Pull request merged**
