### PR TITLE
Add a new command to add a super-master to SQL backends

### PR DESCRIPTION
**Pull request by Godwottery**
### Short description

I wanted to be able to add supermasters without having to open an SQL prompt. Added another command to pdnsutil that allows this to happen. Implemented support for all SQL backends. Tested on FreeBSD with SQLite-backend.

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

I selected "documented the code" because I believe the code is simple enough to be self-explanatory.
I am unsure if there needs to be any tests for this, and how they would be implemented. 
I would need someone to point out where any additional documentation should be placed.

### CODE REVIEW

**Comment by Habbie** [comment]
Hi!

Just some quick comments, have not done a full review.
* please remove the .patch files
* we do not currently test pdnsutil a lot, but we'll think about that part of your question
* documentation is required in docs/manpages/pdnsutil.1.rst and perhaps welcome in docs/modes-of-operation.rst (which describes superslave operation)
* new pdnsutil commands also need to go into contrib/pdnsutil.bash_completion.d (but i strongly suspect it is not up to date today!)

**Comment by Godwottery** [comment]
> * please remove the .patch files
Oops. Fixed.

> * documentation is required in docs/manpages/pdnsutil.1.rst and perhaps welcome in docs/modes-of-operation.rst (which describes superslave operation)
Added in both files.

> * new pdnsutil commands also need to go into contrib/pdnsutil.bash_completion.d (but i strongly suspect it is not up to date today!)
Added in a new command there.

**Comment by Habbie** [comment]
I believe the CircleCI failures are because of something we fixed on master since then. Can you rebase your branch please?

**Comment by Godwottery** [comment]
I don't understand why there is a merge conflict on pdns/pdnsutil.cc. The only change that is to be made are two new lines that are added by this PR. I do not understand how to resolve the merge conflict.

**Comment by Habbie** [comment]
You will need to rebase onto master (ours from today, perhaps your fork has an old one from June 2019) or merge our master into your branch.

We're happy to help out on our IRC channel #powerdns on the OFTC IRC network. https://www.powerdns.com/opensource.html has links.

**Comment by Godwottery** [comment]
It seems I managed to get the rebase to work.

**Pull request merged**
