### PR TITLE
dnsdist: refactor sendfromto

### PR DESCRIPTION
**Pull request by Y7n05h**
Signed-off-by: Y7n05h <Y7n05h@protonmail.com>

### Short description
refactor sendfromto

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by omoerbeek — COMMENTED** [review]
As `sendfromto()` is only used by `dnsdist` would it be better to move it to `dnsdist` specific code?

**Comment by rgacogne** [comment]
> As `sendfromto()` is only used by `dnsdist` would it be better to move it to `dnsdist` specific code?

Sure, we can move it to dnsdist.cc for now, and make it `static` in the process.

**Comment by rgacogne** [comment]
The change looks good to me, thanks!

**Review by rgacogne — APPROVED** [review]
Looks good, thanks!

**Comment by rgacogne** [comment]
I would like to merge this pull request, but I would prefer if the CI tests could pass before doing so. The error is related to an issue that has been fixed on master, would you mind rebasing this branch on the current master?

**Comment by Y7n05h** [comment]
> I would like to merge this pull request, but I would prefer if the CI tests could pass before doing so. The error is related to an issue that has been fixed on master, would you mind rebasing this branch on the current master?

Sure. Now it looks like all the tests have passed.

**Pull request merged**
