### PR TITLE
Now that configure adds the -std= flag always, we can stop specifying it manually

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Could probably use a buildbot run.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
circleci dnsdist: `./namespaces.hh:46:12: error: no member named 'make_unique' in namespace 'std'`

**Comment by omoerbeek** [comment]
Om CentOS7 buildbot:
```
g++ -std=c++17 -DHAVE_CONFIG_H -I.  -I. -I. -pthread   -I/usr/include/luajit-2.0   -I/usr/include/editline     -I./ext/yahttp  -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_RPM_4_4_COMPAT -Ulinux -Dlinux=linux -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib64/perl5/CORE -I. -I/usr/include  -DSYSCONFDIR=\"/etc/dnsdist\" -pthread -I/usr/local/include   -std=c++17  -I/usr/include/p11-kit-1       -I/opt/include     -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O3 -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o dnsdist-lua-bindings-dnscrypt.o dnsdist-lua-bindings-dnscrypt.cc
In file included from protozero.hh:24,
                 from dnsdist-protobuf.hh:26,
                 from dnsdist-lua-actions.cc:28:
ext/protozero/include/protozero/pbf_writer.hpp:19:10: fatal error: basic_pbf_writer.hpp: No such file or directory
 #include "basic_pbf_writer.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Habbie** [comment]
A comment on the re2 pkg-config situation: https://github.com/google/re2/pull/293#issuecomment-761026832

**Comment by omoerbeek** [comment]
> A comment on the re2 pkg-config situation: [google/re2#293 (comment)](https://github.com/google/re2/pull/293#issuecomment-761026832)

The reasoning feels strange but I don't feel like arguing at the moment.

The more worrying thing atm is that the CircleCI Centos7 dnsdist build succeeds, while the buildbot one does not. No clue yet. I'll try to reproduce soon.

**Comment by omoerbeek** [comment]
#9982 takes over, the long branch name causes trouble

**Pull request closed without merging**
