### PR TITLE
Rec: rework root priming code to allow multiple addresses per NS

### LINKED ISSUE #12486: rec: using root NS hints with a single server name ignores multiple IPs
- Program: Recursor
 - Issue type: Bug report

### Short description

Reading root hints in the following form, only one (the last) `A` record "survives" in the cache and so redundancy is lost.
```
. 3600 IN NS ns.
ns. 3600 IN A 192.168.178.16
ns. 3600 IN A 192.168.178.17
ns. 3600 IN A 192.168.178.18
```
Workaround is to use multiple names:
```
. 3600 IN NS ns1.ns.
. 3600 IN NS ns2.ns.
. 3600 IN NS ns3.ns.
ns1.ns. 3600 IN A 192.168.178.16
ns2.ns. 3600 IN A 192.168.178.17
ns3.ns. 3600 IN A 192.168.178.18
```

Root cause is the `replace` calls in `reczones.cc:primeHints()`.

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

This fixes #12486 and refactors the root-priming code in a separate commit.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
There is a small conflict now that I merged #12664, sorry!

**Review by chbruyand — APPROVED** [review]
LGTM although it would be nice to have a regression test for the issue.

**Comment by omoerbeek** [comment]
> LGTM although it would be nice to have a regression test for the issue.

yes, will add a test

**Comment by omoerbeek** [comment]
Rebased

**Pull request merged**
