### PR TITLE
dnsdist: update test runner for mac

### PR DESCRIPTION
**Pull request by chbruyand**
Homebrew prefix may vary depending on the setup and previous `curl-openssl` package has now been renamed `curl`.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]
Looks good to me, thanks! I can't test it on macOS so I wouldn't mind a second review, perhaps from @omoerbeek ?

**Comment by omoerbeek** [comment]
These changes look sane. I do see errors when trying to dnsdist regression tests though. e.g.
```
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.929" timestamp="2024-06-17T09:41:08.780777" hostname="mbp.local"><testcase classname="test_DOH.TestDoHNGHTTP2" name="testDOHEmptyPOST" time="0.246"><failure message="pycurl.error: (60, 'SSL: peer not verified:  RecoverableTrustFailure')">self = &lt;test_DOH.TestDoHNGHTTP2 testMethod=testDOHEmptyPOST&gt;
```
It's nopt immediately clear to me what causes these failures.
config:
```
configure: Features enabled
configure: ----------------
configure: Lua: lua
configure: Protobuf: yes
configure: systemd: no
configure: AF_XDP/XSK: no
configure: ipcipher: yes
configure: libedit: yes
configure: libsodium: yes
configure: DNSCrypt: yes
configure: dnstap: yes
configure: quiche: yes
configure: re2: no
configure: SNMP: yes
configure: DNS over TLS: yes
configure: DNS over HTTPS (DoH): yes
configure: DNS over QUIC (DoQ): yes
configure: DNS over HTTP/3 (DoH3): yes
configure: GnuTLS: yes
configure: OpenSSL: yes
configure: h2o-evloop: no
configure: nghttp2: yes
configure: cdb: yes
configure: lmdb: yes
```

**Comment by rgacogne** [comment]
Could it be:

> If libcurl was built with Schannel (Microsoft's native TLS engine) or Secure Transport (Apple's native TLS engine) support, then libcurl still performs peer certificate verification, but instead of using a CA cert bundle, it uses the certificates that are built into the OS.

from https://curl.se/docs/sslcerts.html

**Comment by omoerbeek** [comment]
Maybe, it's probably best to merge this and I'll figure out with @chbruyand why my test have failures.

**Comment by rgacogne** [comment]
Alright, thank you!

**Pull request merged**
