### PR TITLE
CI: move dnsdist tsan build+test from CircleCI to GH Actions

### PR DESCRIPTION
**Pull request by Habbie**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]
Looks great! I guess we need to update the list of required tests once this has been merged?

**Comment by Habbie** [comment]
> Looks great! I guess we need to update the list of required tests once this has been merged?

Yes, it's a bit of a painful process - I remove the CircleCI-side test from required when I merge this, but adding the new one immediately is annoying for people writing PRs. I think I'll add one 'finish' job to the GH flow that depends on all others, and make just that one required. Then the actual list of required tests lives in the github yaml file instead of CircleCI.

**Comment by Habbie** [comment]
Oh - dnsdist-tsan never made it to the required list.

**Comment by Habbie** [comment]
Removed CircleCI-`build-dnsdist` from the required list.

**Pull request merged**
