### PR TITLE
Add tests for swagger-codegen in travis

### PR DESCRIPTION
**Pull request by ffledgling**
We now attempt to generate valid client bindings from the in-repo
swagger spec. If this fails, there's something wrong with the spec.

### Short description
Fixes issue #6510 , by adding a test for the swagger codegen client.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by ffledgling** [comment]
To add some context to this seemingly random PR:

The test that this PR adds is *supposed* to fail, because the swagger spec in the master branch is broken at the moment. The reason for the addition of this test is precisely to prevent commits from breaking the spec in the future.

However, fixing the spec is an entirely different ball game, one which should probably not be tied into this PR.

So the decision for the moment (quoting @Habbie ) is:
```
06:33 < Habbie> so, i understand that adding this test was 'easy'
06:33 < Habbie> but making it pass is 'hard'
06:33 < Habbie> i am okay with noting that clearly in the PR
06:34 < Habbie> so we have this test setting ready for the day we are, well, ready for it
```

**Comment by jsoref** [comment]
Hi, for the time being (and hopefully going forward), pdns master is running the [check-spelling](https://github.com/marketplace/actions/check-spelling) action. In order to avoid a ❌ when merged https://github.com/jsoref/pdns/commit/27fbadcc761a9e20a204d6c5de3d3633581fa28f#commitcomment-39230833 -- you'll need to merge/rebase on `master` to get the check (and the files) -- you can accept the advice (which should add the items to `expect.txt`)

**Comment by Habbie** [comment]
Do you want to rebase this for a fresh look at the status of our yaml?

**Comment by pieterlexis** [comment]
we no longer use travis. Closing this

**Pull request closed without merging**
