### PR TITLE
ragel is also a build dependency

### PR DESCRIPTION
**Pull request by HLFH**

### CODE REVIEW

**Comment by Habbie** [comment]
Uhm, don't we shop yahttp and json11 in our tree?

**Comment by cmouse** [comment]
Depends what you understand with build dependencies =)

**Comment by HLFH** [comment]
@Habbie 

> On Linux, make pdns_recursor in the pdns subdir may work. The portable, and supported, way to build the recursor is first running dist-recursor and compiling from the pdns-recursor-x.y subdirectory.

And you're right. Maybe the last commit is useless but it seems that when we build the recursor by running `./build-scripts/dist-recursor`, we  have to compile from the `pdns/recursordist` directory by using the commands `./configure`, `make` (not `make pdns_recursor`!) and then install with `make install`. Ragem seems the only dependency. Or, am I completely wrong about the process to build pdns-recursor?

**Comment by Habbie** [comment]
The right way to build the recursor is from that dist dir, yes.

**Comment by HLFH** [comment]
@Habbie So how is this last commit? Is that more clear to build pdns-recursor with these added infos? https://github.com/HLFH/pdns/commit/7dffd6946e62fc1ccc86f8541d18e37d7bb3bc62

**Comment by pieterlexis** [comment]
hrm, considering the pdns/recursordist dir is now equal (when the symlinks are dereferenced) to the tarball, the dist-recursor step is no longer needed. I guess the best way to compile the recursor from git is:

1. `cd pdns/recursordist`
2. `./bootstrap`
3. `./configure`
4. `make`
5. `make install`

**Comment by HLFH** [comment]
@pieterlexis Is that better now? Should I remove dist-recursor or shoudl I finally keep it?

**Comment by pieterlexis** [comment]
@HLFH that file needs to stay, we use it to create tarballs for releases :-)

**Comment by HLFH** [comment]
@pieterlexis Thanks! Is that now correct?

**Comment by pieterlexis** [comment]
@HLFH if you change the filemode of dist-recursor back to 0755, I'm happy. With regards to your commits, you can [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) them and force-push this to your branch to update this PR.

**Pull request closed without merging**
