### PR TITLE
authoritative: update debian packaging

### PR DESCRIPTION
**Pull request by zeha**
### Short description
Import from Debian bullseye, with the following changes:
- keep PowerDNS Maintainer:
- drop debhelper compat to 12 (causes no changes)
- ignore changelog, patches

Should also go to the 4.4 branch if possible.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
On the 4.4 branch (150ea0efbe266806c39ded5621148e3c3e1cf508), building fails with:

```
make[3]: Entering directory '/pdns-authoritative/docs'
make  distdir-am
make[4]: *** No rule to make target 'zone2ldap.1', needed by 'distdir-am'.  Stop.
make[3]: *** [Makefile:602: distdir] Error 2
make[4]: Entering directory '/pdns-authoritative/docs'
make[4]: Leaving directory '/pdns-authoritative/docs'
make[3]: Leaving directory '/pdns-authoritative/docs'
make[2]: *** [Makefile:679: distdir-am] Error 1
make[2]: Leaving directory '/pdns-authoritative'
make[1]: Leaving directory '/pdns-authoritative'
make[1]: *** [Makefile:673: distdir] Error 2
make: *** [Makefile:774: dist] Error 2
```

Ideas welcome.

**Comment by pieterlexis** [comment]
> On the 4.4 branch ([150ea0e](https://github.com/PowerDNS/pdns/commit/150ea0efbe266806c39ded5621148e3c3e1cf508)), building fails with:
> 
> ```
> make[3]: Entering directory '/pdns-authoritative/docs'
> make  distdir-am
> make[4]: *** No rule to make target 'zone2ldap.1', needed by 'distdir-am'.  Stop.
> make[3]: *** [Makefile:602: distdir] Error 2
> make[4]: Entering directory '/pdns-authoritative/docs'
> make[4]: Leaving directory '/pdns-authoritative/docs'
> make[3]: Leaving directory '/pdns-authoritative/docs'
> make[2]: *** [Makefile:679: distdir-am] Error 1
> make[2]: Leaving directory '/pdns-authoritative'
> make[1]: Leaving directory '/pdns-authoritative'
> make[1]: *** [Makefile:673: distdir] Error 2
> make: *** [Makefile:774: dist] Error 2
> ```
> 
> Ideas welcome.

If you're doing a `make dist` you'll need to have/enable LDAP, so this manpage can be built

**Comment by zeha** [comment]
> If you're doing a `make dist` you'll need to have/enable LDAP, so this manpage can be built

`builder-support/dockerfiles/Dockerfile.authoritative` seems to call ./configure with `--without-modules --without-dynmodules` on both master and rel/auth-4.4.x. Is that something new/old?

**Comment by pieterlexis** [comment]
are you running this from a dirty git tree? `make clean` or `rm docs/pdns_server.1` before calling the builder will help

**Comment by zeha** [comment]
> are you running this from a dirty git tree? `make clean` or `rm docs/pdns_server.1` before calling the builder will help

Indeed, that's it. Thanks!

**Comment by zeha** [comment]
> Spell checking

that seems to take ... forever?

**Comment by Habbie** [comment]
> that seems to take ... forever?

It's not running because you did not touch the docs, but it's configured as a mandatory check (since this week). #9956 changes it to always run, so it does go green, a rebase will fix that for you, but you can also just leave it, we know it's this way for now.

**Comment by zeha** [comment]
Rebased to avoid spellcheck issue.

**Comment by zeha** [comment]
Rebased and added all commits from #9965

**Review by pieterlexis — APPROVED** [review]
didn't do a full review, but it should be ok :)

**Comment by zeha** [comment]
As discussed with @Habbie this now includes "build with luajit, if known good".

We could turn ppc64el support on too, but https://github.com/LuaJIT/LuaJIT/pull/54 does not look great. @james-crowley any comments?

**Comment by james-crowley** [comment]
@zeha Sorry I commented over on the other issue/PR. Like I mentioned over there, the included LuaJIT in debian works fine for `ppc64el`. I have build the `auth` container and ran it. No issues that I could fine. 

It looks like the unofficial LuaJit for `ppc64el` is recognized by multiple distros and included into their repos/packages. 

I know @Habbie was working on getting access to `s390x` and `ppc64el` resources. Once you have access for those you can see for yourselves. If there are any test suites you want me to run, let me know. 

Either way, I think getting `ppc64el` support with the LuaJIT or not is a huge win. It will be nice to deploy PowerDNS on multi-arch clusters without worrying about architecture issues. 

I think `s390x` also has an unofficial LuaJIT as well, but does not have the same level of testings and support as `ppc64el`. The `s390x` port is more just local patches you can apply and currently no distro's support it in their package/repo lists.

**Pull request merged**
