### PR TITLE
Cleanup small issues found by lgtm.com

### PR DESCRIPTION
**Pull request by zeha**
### Short description
- Catch exceptions by reference (the actual object is discarded in these anyway)
- Add include guards

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by sjvs** [comment]
Hi @zeha and @rgacogne. Glad that the lgtm.com alerts are useful to PowerDNS :slightly_smiling_face:! LGTM also offers pull request integration for automatic code review. It'll flag up new (and fixed) alerts in your pull requests, before they hit `master`.

Here's an example of how that works for the AMPHTML project: https://github.com/ampproject/amphtml/pull/13060

(Full disclosure: I'm part of the team that built lgtm.com)

**Comment by Habbie** [comment]
@sjvs enabled! Can you explain https://lgtm.com/projects/g/PowerDNS/pdns/snapshot/dist-1505894857787-1523356678120/files/pdns/communicator.hh?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xa13c6d09294b0d4:1 ? :)

**Comment by sjvs** [comment]
@Habbie: cool! I'll ask our C/C++ analysis team to have a look at that alert.

**Comment by sjvs** [comment]
@Habbie : I'm looking into that build failure. I set up PowerDNS for analysis a few months ago, but I think the build process has since changed.

**Comment by Habbie** [comment]
> @Habbie : I'm looking into that build failure. I set up PowerDNS for analysis a few months ago, but I think the build process has since changed.

`/opt/out/snapshot/workspace/lgtm/configure_command.sh: line 4: ./bootstrap: No such file or directory`

replace with `autoreconf -vfi`

**Comment by sjvs** [comment]
Indeed, that's what I'm trying. I'm at the same time trying to make sure that historical builds (which use `./bootstrap`) won't fail. Currently doing a test run, should be sorted soon.

**Comment by zeha** [comment]
@sjvs I've opened #6538 to ship our own config. Maybe you could have a look at that.

**Comment by sjvs** [comment]
@zeha: that looks great, thanks! Will have a look.

**Pull request merged**
