### PR TITLE
Add --uid and --gid parameters in dnsdist to request dropping privile…

### LINKED ISSUE #2798: dnsdist: should drop privileges after binding (when requested)
Right now, the only way to run dnsdist on port 53 is running the whole process as root (or using capabilities), there should be a `--uid` and `--gid` config option that drops the privileges after ports have been opened.

### PR DESCRIPTION
**Pull request by rgacogne**
…ges. Fixes #2798.

### CODE REVIEW

**Comment by cmouse** [comment]
Can you add support for names as well?

**Comment by rgacogne** [comment]
@mind04 good catch, thanks!
@cmouse sure, that's a good idea, thanks too! Added in this new version.

**Comment by Habbie** [comment]
I get the feeling there is some code duplication from `unix_utility.cc` which we could probably drag into dnsdist.

**Comment by rgacogne** [comment]
That's true, I initially wanted to do that, but it transitively dragged Logger and I wasn't so sure about that..

**Comment by Habbie** [comment]
Ah yes, our infinitely expanding dependency tree. Not sure what to advice :(

**Comment by zeha** [comment]
(Sometime) Bite the bullet, and make dnsdist use Logger, too?

**Comment by ahupowerdns** [comment]
no, Logger is a piece of shit. Anything but Logger.

**Comment by rgacogne** [comment]
rebased

**Pull request merged**
