### PR TITLE
Added documentation for zone export 

### PR DESCRIPTION
**Pull request by hkraal**
and improved the axfr-retrieve part

### CODE REVIEW

**Comment by Habbie** [comment]
I'm not sure "imports the zone" is clearer than the previous text.

**Comment by hkraal** [comment]
It implies the data goes towards the API instead of from the API which makes more sense when using a PUT command. The old text is pull oriented where the method isn't, this is what caused me to assume the method needed to be GET instead of PUT.

"Send AXFR zone to powerdns for import." or "Send AXFR zone to powerdns to create domain." any better?

**Comment by Habbie** [comment]
It's not sending a zone - it's telling powerdns to retrieve the zone, from the master, via AXFR

**Comment by Habbie** [comment]
Hence '+Clients must send body containing an AXFR.' is incorrect. It looks like you are confusing axfr-retrieve with the zone import support in the zone creation API call :)

**Comment by zeha** [comment]
I can see how this should be a POST instead.

**Comment by Habbie** [comment]
I had the same thought but assumed you knew what you were doing ;)

**Comment by hkraal** [comment]
Assumptions are... well ok. Will change and commit in a minute

**Comment by zeha** [comment]
It's still not supported for recursors, and I doubt the '3.4.2' version there.

**Comment by hkraal** [comment]
09:32 < Habbie> axfr-retrieve is new in 3.4.2

Any more feedback or shall I squat?

**Comment by zeha** [comment]
Ah, ignore my POST comment -- it's implemented as defined.

**Pull request merged**
