### PR TITLE
bind: return false for dnssec questions for non-authoritative domains

### LINKED ISSUE #523: Bind backend does not return false for DNSSEC requests on domains it is not authoritative for
The bind backend has the same bug as gsql backends, not returning false for domains it is not authoritative for. Patch contained within this ticket fixes this by checking if backend is authoritative for the domain before doing anything else.

### PR DESCRIPTION
**Pull request by pieterlexis**
Closes #523

### CODE REVIEW

**Comment by cmouse** [comment]
[2015-12-23 09:13:52] ++/home/travis/build/PowerDNS/pdns/regression-tests/../pdns/pdnsutil --config-dir=. --config-name=bind activate-zone-key secure-delegated.dnssec-parent.com 8
[2015-12-23 09:13:52] Activation of key failed

**Comment by Habbie** [comment]
Travis is unhappy about BIND tests here.

**Comment by Habbie** [comment]
Ping?

**Comment by pieterlexis** [comment]
closing, as this solution breaks unexpectedly and original issue is 1. not verified and 2. help-wanted

**Pull request closed without merging**
