### PR TITLE
make builds pass with -Werror on _my_ system

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
While I would not recommend running with `-Werror` always, I find it convenient to catch silly mistakes during development. The patches in this PR make `-Werror` work on my system. After discussion, perhaps we can upstream some things to the autoconf-archive.

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
With this my configure runs fails on MacOS:
```
configure: error: time_t is unsigned, PowerDNS code relies on it being signed```
```
`config.log` snippet:
```
configure:7283: ccache c++ -c -g -O2 -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -Wno-unused-command-line-argument -Wno-deprecated-copy-with-user-provided-copy -Wno-deprecated-copy -I/opt/homebrew/opt/openssl@1.1/include conftest.cpp >&5
conftest.cpp:46:2: error: expected expression
 [[maybe_unused]] int foo [ 1 - 2 * !(((time_t) -1) < 0) ]
 ^
1 error generated.
```

**Comment by Habbie** [comment]
Interesting, what compiler?

**Comment by omoerbeek** [comment]
> Interesting, what compiler?

```
mbp:pdns otto$ c++ --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by omoerbeek** [comment]
Will push a potential solution. For some reason, the `m4/ax_cxx_compile_stdcxx.m4` one is not hit here...

**Comment by Habbie** [comment]
> For some reason, the `m4/ax_cxx_compile_stdcxx.m4` one is not hit here...

Probably because the compiler is actually instructed to be ++17 in that case?

**Review by omoerbeek — APPROVED** [review]
I also upstreamed this: https://github.com/autoconf-archive/autoconf-archive/pull/268

**Pull request merged**
