### PR TITLE
Consistently include config.h as first, if HAVE_CONFIG_H is defined

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by cmouse** [comment]
This is ready for review.

**Comment by cmouse** [comment]
This should be ready for review now (let's see if this moves to wrong place)

**Comment by rubenk** [comment]
Can you please explain, in the commit message, why you include config.h only in the .cc files?

**Comment by rubenk** [comment]
Thanks. Please add a blank line after the first sentence of the commit message, and keep the first sentence below 50 characters if possible. Also, there's a typo in aalso.

**Comment by cmouse** [comment]
@rubenk is the commit message ok now?

**Comment by rubenk** [comment]
Much better now, thanks. This looks good to merge.

**Pull request merged**
