### PR TITLE
SunOS: Fail when compiling mplexers fails

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by Habbie** [comment]
I wonder - perhaps we had those because these mplexers don't work on all SunOS systems? (If the answer is 'they both work since 9' this is fine though!)

**Comment by rubenk** [comment]
Might be, do we have a Solaris 9 system somewhere to check?

**Comment by Habbie** [comment]
I think I do :)

**Comment by Habbie** [comment]
no port.h on Solaris 9, so need to at least keep that mplexer optional

**Comment by rubenk** [comment]
Done :)

**Pull request merged**
