### PR TITLE
rec: Use a short-lived NSEC3 hashes cache for denial validation

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

It turns out that computing those SHA1 hashes is far from cheap, and in almost all cases the salt and iterations are identical
so no need to compute them several times.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by omoerbeek — COMMENTED** [review]
Initially I was confused since the order of things is different between the map and the call to `hashQNameWithSalt`. It's also not immediately clear why `DNSName` is not a ref in the tuple, but salt is. Added comments to explain that would be nice.

**Comment by rgacogne** [comment]
> It's also not immediately clear why DNSName is not a ref in the tuple, but salt is.

Because `salt` lives from the duration of the cache while the name does not. I'll drop that optimization, it might lead to issues later.

> Initially I was confused since the order of things is different between the map and the call to hashQNameWithSalt
 
I'm afraid I don't understand the confusion. Do you mean the order in the tuple? It does not really matter, but since the name is more likely to differs than the salt or the number of iterations, I want to compare the name first.

**Comment by omoerbeek** [comment]
> > It's also not immediately clear why DNSName is not a ref in the tuple, but salt is.
> 
> Because `salt` lives from the duration of the cache while the name does not. I'll drop that optimization, it might lead to issues later.

Agreed.

> 
> > Initially I was confused since the order of things is different between the map and the call to hashQNameWithSalt
> 
> I'm afraid I don't understand the confusion. Do you mean the order in the tuple? It does not really matter, but since the name is more likely to differs than the salt or the number of iterations, I want to compare the name first.

Yes, I meant the order of the tuple. Initially my brain did (wrongly) assume the order of args in the function call and the order of the tuple would be the same. It was probably a end-of-week thing.

**Review by omoerbeek — APPROVED** [review]

**Comment by rgacogne** [comment]
Compilation fails on Travis:
```
validate.cc:93:67: error: converting to ‘const key_type {aka const std::tuple<DNSName, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const DNSName&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int&}; <template-parameter-2-2> = void; _Elements = {DNSName, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int}]’
   auto it = cache.find({qname, nsec3->d_salt, nsec3->d_iterations});
                                                                   ^
validate.cc:100:52: error: converting to ‘std::map<std::tuple<DNSName, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int>, std::basic_string<char> >::key_type {aka std::tuple<DNSName, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const DNSName&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int&}; <template-parameter-2-2> = void; _Elements = {DNSName, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, short unsigned int}]’
   cache[{qname, nsec3->d_salt, nsec3->d_iterations}] = result;
```

Although it does compile on CentOS 6 so we could get away with it, but let's try to be as portable as possible.

**Pull request merged**
