### PR TITLE
API: return RRType when finding a comment

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Does what it says on the tin.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — CHANGES_REQUESTED** [review]
Looks good, but how about a test?

**Comment by pieterlexis** [comment]
> Looks good, but how about a test?

added a test!

**Comment by Habbie** [comment]
> added a test!

Nice! I don't think we had any tests for comments in search at all!

**Comment by pieterlexis** [comment]
> > added a test!
> 
> Nice! I don't think we had any tests for comments in search at all!

correct!

**Review by Habbie — APPROVED** [review]

**Pull request merged**
