### PR TITLE
Dnsdist/server token test

### PR DESCRIPTION
**Pull request by melissavoegeli**
### Short description
I am learning this codebase and decided before I make a real change, that I will add a test to an area I am eventually going to make modifications.  I did this to A) convince myself that I know how these tests work and B) see how close I get to the community code expectations.

I am not familiar with good python practices, so please let me know if anything is fucked up. In particular I didn't want to add another return value to sendDOHQuery because that would be more code changes.  But I think my implemented solution could be confusing.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by melissavoegeli** [comment]
> Thanks for this PR! It looks good to me, the only comment I can think of is that the regex matching would not detect a duplicated 'Server' header in the response, for example, but I think it's good enough that way.

Good point.  I also thought about how to test custom server token headers not being present for non explicitly determined paths.  (As mentioned in #7894)  But it required more changes and I felt bad.  I like your idea because it helps document the behavior a little bit more plainly in the test expectations.  I'll revise it.

**Comment by rgacogne** [comment]
Note that the duplicated 'Server' header is a bug and will disappear once https://github.com/PowerDNS/pdns/pull/7911 is merged!

**Comment by melissavoegeli** [comment]
Does that mean you prefer I change the test expectations or abandon this PR?

**Comment by rgacogne** [comment]
> Does that mean you prefer I change the test expectations or abandon this PR?

Please don't abandon it! :-) Ideally I'd like you to rebase it on the current master, and check that you have only one 'Server:' header. But I'm also fine with just changing this after rebasing:

```
self.assertTrue((self._h2oServerToken) in self._response_headers)
```

to:

```
self.assertFalse((self._h2oServerToken) in self._response_headers)
```

**Pull request closed without merging**
