### PR TITLE
rec: cachonly vs forwarding

### PR DESCRIPTION
**Pull request by omoerbeek**
The cacheonly vs forwarding logic is twisted. If we get an non-aa answer from the forward, continue consulting the cache in a regular way.

#8106 

But not confident yet this is the real fix. Hence the draft status.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by hawken93** [comment]
I have built and installed this branch, I'm going to keep running with this for a while and I'll let you know if anything goes horribly wrong :)

**Comment by rgacogne** [comment]
> The cacheonly vs forwarding logic is twisted.

Yes, perhaps we should clean up this part first. I'm not even sure we should consult the servers we forward to in the `cacheonly` case..

**Comment by omoerbeek** [comment]
@hawken93 can you please test the updated code? Thanks!

**Comment by pieterlexis** [comment]
@omoerbeek is this PR still needed? I believe several improvements in this area have been made since August 2019

**Comment by omoerbeek** [comment]
Yes, this is outdated.

**Pull request closed without merging**
