### PR TITLE
rec: A SHA-384 DS should not trump a SHA-256 one, so only potentially zap SHA-1

### PR DESCRIPTION
**Pull request by omoerbeek**
### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [X] added or modified unit test(s)

### CODE REVIEW

**Comment by vcunat** [comment]
So GOST still zaps SHA-1?  🤔

(On a quick glance.)  Not that I'd expect it to matter/happen in practice.  Still, if that's so, it would be inconsistent with the comment you added.

**Comment by vcunat** [comment]
OK, but I was reading code, not just comments: https://github.com/PowerDNS/pdns/blob/b995eb5/pdns/syncres.cc#L2616

**Comment by Habbie** [comment]
Indeed, dead code, even if the compiler can't figure that out.

**Comment by vcunat** [comment]
Could call it "g(h)ost" code.

**Comment by vcunat** [comment]
Speaking of GOST DS, I'd expect [a new one](https://datatracker.ietf.org/doc/draft-ietf-dnsop-rfc5933-bis/) in the IANA registry soon (like 2022?).  But that does not imply you implementing it.  I expect that like us, any algorithm that you add in future will be considered significantly more secure than SHA1, so it makes sense to write the code like the diff in this PR.

For reference, my reason for looking into this: https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1251

**Pull request merged**
