### PR TITLE
builder-support: finish up ucf removal for sql backends

### PR DESCRIPTION
**Pull request by zeha**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
https://builder.powerdns.com/#/builders/99/builds/627

**Comment by Habbie** [comment]
> https://builder.powerdns.com/#/builders/99/builds/627

This build is green.

**Comment by zeha** [comment]
My changes are not complete:
- I thought on jessie, ucf is kept, but it's not. So the same changes need doing on jessie.
- When "upgrading" from 4.x to 0.x, the code in pdns-server.preinst is not run, but at least the ucf deregistration needs to happen.
- The mysql backend package should do it's previous incorrect-package-name cleanup (by deregistering) as well.

So in my 4.1.5-1pdns.stretch -> 0.0.... test, I had these files left in /var/lib/ucf/registry:
```
pdns-server 	 /etc/powerdns/pdns.conf
pdns-server 	 /etc/default/pdns
pdns-server 	 /etc/powerdns/pdns.d/pdns.local.conf
pdns-server 	 /etc/powerdns/pdns.d/pdns.simplebind.conf
```

**Comment by Habbie** [comment]
Rebuilding at https://builder.powerdns.com/#/builders/99/builds/629

**Pull request merged**
