### PR TITLE
API: Reenable Recursor tests

### PR DESCRIPTION
**Pull request by zeha**
And fix a memory/rapidjson issue.

If the data is correct is yet to be seen.

### CODE REVIEW

**Comment by zeha** [comment]
Rebased on top of current master to resolve merge conflicts.

**Comment by pieterlexis** [comment]
:+1:

**Comment by cmouse** [comment]
Is the data correct now? =)

**Comment by zeha** [comment]
Didn't check if the data is all-correct now, can be done afterwards. Right now we don't even test the recursor API at all...

**Pull request merged**
