### PR TITLE
Implement CORS for API in 3.4.2

### LINKED ISSUE #1984: CORS + JSONP
I'd like to talk to the PowerDNS API directly from browser javascript. AFAIK I have 2 options:

* CORS (Cross-origin resource sharing)
* JSONP

I've attempted to use CORS, however PDNS does not handle the preflight OPTIONS request properly. I've also attempted to use JSONP however there is no way to include the `X-API-Key` with a JSONP request.

It'd be nice if Pdns could support CORS. Failing that, provide the option of disabling authentication completely in order for JSONP to work.

### PR DESCRIPTION
**Pull request by cmouse**
CORS for auth 3.4.2, fixes #1984

### CODE REVIEW

**Comment by cmouse** [comment]
@zeha hi!

**Comment by zeha** [comment]
LGTM

**Comment by mind04** [comment]
Why is this https://github.com/PowerDNS/pdns/commit/7f7481be380942f00178178df1577c71e8be86f8#diff-678c3d6069664e692c67ebe60c82fa8cL151 part missing in this pull?

**Comment by cmouse** [comment]
What bit?

**Comment by zeha** [comment]
That hunk should've been removed in a followup commit, but it probably wasn't squashed.

**Comment by cmouse** [comment]
@mind04 @zeha you guys mean 683b9bd which is part of this pull?

**Comment by mind04** [comment]
My bad, i compared this pull with a single commit on master

**Pull request merged**
