### PR TITLE
dnsdist: Add 1.3.0 changelog

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description

Only merged PR's as of ae1fd337755300571ff05f6742b7a41fb1ea1c2a are included. More will have to be added once those are merged

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by pieterlexis** [comment]
>  5af7506

Is already backported to 1.2, the rest is added

**Comment by rgacogne** [comment]
We merged some new PRs in the meantime:
- #6384
- #6391
- #6394
- #6399
- #6400
- #6401
- #6402
- #6403
- #6407

We will very likely also merge before the release:
- #6191
- #6412

And hopefully #6411.

**Comment by rgacogne** [comment]
Shit, this PR is conflicted :'(

**Comment by rgacogne** [comment]
Rebased to fix conflicts, updated the release date.

**Pull request merged**
