### PR TITLE
Only build zone2ldap when we build ldapbackend

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by Habbie** [comment]
This looks like 'make zone2ldap' won't even work when configured without LDAP - is it necessary to actually break that?

**Comment by rubenk** [comment]
I thought the point @mind04 was making is that zone2ldap is useless without the ldap backend.
I see only 2 options, leave it as is, and always build it, or do what this patch does, but yes, that breaks make zone2ldap.

**Comment by Habbie** [comment]
What's wrong with option 3 - only build it as part of 'all' if ldap is enabled, but allow 'make zone2ldap' if ldap is not enabled?

**Comment by rubenk** [comment]
I didn't see how at first, but now I see clearly ;) Done.

**Comment by Habbie** [comment]
:cake:

**Pull request merged**
