### PR TITLE
Emit warning when socket timestamps cannot be enabled

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by pieterlexis** [comment]
It might be handy to also send out this warning to the log (with the addition of the consequences)

**Comment by cmouse** [comment]
@ahupowerdns your thoughts?

**Comment by cmouse** [comment]
warning is now enabled, ready for review. I changed it from error to warning.

**Comment by cmouse** [comment]
I cannot figure out why it fails

**Comment by Habbie** [comment]
Pull title vs. commit title confuse me

**Comment by cmouse** [comment]
it changed after ahu's input, forgot to update the title.

**Comment by cmouse** [comment]
Apparently this is caused by https://github.com/wummel/linkchecker/issues/217 (thanks @ahupowerdns), so it requires some fixing on master.

**Comment by pieterlexis** [comment]
It's awesome I can't reproduce this issue locally... When #2545 is merged, can you rebase?

**Pull request merged**
