### PR TITLE
API: use json11 in place of rapidjson

### PR DESCRIPTION
**Pull request by zeha**

### CODE REVIEW

**Comment by zeha** [comment]
travis: clang build worked, gcc timed out, let's see if it works now.

**Comment by zeha** [comment]
... and review welcome.

**Comment by Habbie** [comment]
@cmouse this touches remotebackend, can you review?

**Comment by cmouse** [comment]
I don't think we should drop rapidjson from tree until it has been removed from remotebackend too.

**Comment by zeha** [comment]
@cmouse as said on irc, this doesn't remove rapidjson from the tree yet.

**Comment by cmouse** [comment]
Ok

**Comment by zeha** [comment]
@Habbie do you have more input?

**Comment by Habbie** [comment]
Will try to review today or tomorrow, please feel free to remind me!

**Comment by Habbie** [comment]
@zeha can you please clearly state what tests you ran? like (1) api auth tests from git checkout (2) api rec tests from git checkout (3) api rec tests against binary built from dist-rec. Thanks!

**Comment by Habbie** [comment]
(@zeha responded '1+2, not 3')

**Comment by Habbie** [comment]
travis has run 1,3; I have locally run 1,2,3

**Comment by Habbie** [comment]
Did some testing; did not do a line by line review. If @cmouse is not unhappy about the remotebackend changes in here, LGTM.

**Comment by zeha** [comment]
Merge, pretty please? :)

**Comment by pieterlexis** [comment]
@cmouse?

**Comment by cmouse** [comment]
:+1:

**Pull request merged**
