### PR TITLE
rec: add unit test for potential NS loop.

### PR DESCRIPTION
**Pull request by omoerbeek**
We succeed (that is do not go into an endless loop) and we need to keep it that way.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [X] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]
Looks good, perhaps we could check the total number of queries too?

Something like:
```diff
diff --git pdns/recursordist/test-syncres_cc2.cc pdns/recursordist/test-syncres_cc2.cc
index b88620002..6d416145d 100644
--- pdns/recursordist/test-syncres_cc2.cc
+++ pdns/recursordist/test-syncres_cc2.cc
@@ -105,8 +105,11 @@ BOOST_AUTO_TEST_CASE(test_glueless_referral_loop)
 
   const DNSName target1("powerdns.com.");
   const DNSName target2("powerdns.org.");
+  size_t queriesToNS = 0;
+
+  sr->setAsyncCallback([target1, target2, &queriesToNS](const ComboAddress& ip, const DNSName& domain, int type, bool doTCP, bool sendRDQuery, int EDNS0Level, struct timeval* now, boost::optional<Netmask>& srcmask, boost::optional<const ResolveContext&> context, LWResult* res, bool* chained) {
+    queriesToNS++;
 
-  sr->setAsyncCallback([target1, target2](const ComboAddress& ip, const DNSName& domain, int type, bool doTCP, bool sendRDQuery, int EDNS0Level, struct timeval* now, boost::optional<Netmask>& srcmask, boost::optional<const ResolveContext&> context, LWResult* res, bool* chained) {
     if (isRootServer(ip)) {
       setLWResult(res, 0, false, false, true);
 
@@ -150,6 +153,7 @@ BOOST_AUTO_TEST_CASE(test_glueless_referral_loop)
   int res = sr->beginResolve(target1, QType(QType::A), QClass::IN, ret);
   BOOST_CHECK_EQUAL(res, RCode::ServFail);
   BOOST_REQUIRE_EQUAL(ret.size(), 0U);
+  BOOST_CHECK_EQUAL(queriesToNS, 22);
 }
 
 BOOST_AUTO_TEST_CASE(test_cname_qperq)
```

**Comment by rgacogne** [comment]
Hmm, looks like the number of queries is not consistent between runs (21 or 22), which doesn't seem right to me..

**Comment by omoerbeek** [comment]
Interesting, are you investigating or shall I?

**Comment by rgacogne** [comment]
Yes, and I think we have some room for improvement. I won't investigate further but I sometimes see cases where we ask the same question to the same nameserver at least twice in the same trace (`Trying IP [2001:db8::1]:53, asking 'ns1.powerdns.com|A` here):
```
 powerdns.com: Trying IP [2001:500:1::53]:53, asking 'powerdns.com|A'
 powerdns.com: Trying IP [2001:db8::1]:53, asking 'powerdns.com|A'
  ns1.powerdns.org: Trying IP 192.112.36.4:53, asking 'ns1.powerdns.org|A'
  ns1.powerdns.org: Trying IP [2001:db8::1]:53, asking 'ns1.powerdns.org|A'
     ns1.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns1.powerdns.com|A'
       ns1.powerdns.com: Trying IP 192.203.230.10:53, asking 'ns1.powerdns.com|A'
       ns1.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns1.powerdns.com|A'
        ns2.powerdns.org: Trying IP 192.0.2.1:53, asking 'ns2.powerdns.org|A'
         ns1.powerdns.com: Trying IP [2001:500:12::d0d]:53, asking 'ns1.powerdns.com|A'
         ns1.powerdns.com: Trying IP 192.0.2.1:53, asking 'ns1.powerdns.com|A'
          ns1.powerdns.org: Trying IP 192.0.2.1:53, asking 'ns1.powerdns.org|A'
            ns2.powerdns.org: Trying IP [2001:500:200::b]:53, asking 'ns2.powerdns.org|A'
            ns2.powerdns.org: Trying IP [2001:db8::1]:53, asking 'ns2.powerdns.org|A'
               ns1.powerdns.com: Trying IP 192.0.2.1:53, asking 'ns1.powerdns.com|AAAA'
               ns2.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns2.powerdns.com|A'
             ns2.powerdns.com: Trying IP 192.58.128.30:53, asking 'ns2.powerdns.com|A'
             ns2.powerdns.com: Trying IP 192.0.2.1:53, asking 'ns2.powerdns.com|A'
             ns2.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns2.powerdns.com|AAAA'
           ns2.powerdns.com: Trying IP 193.0.14.129:53, asking 'ns2.powerdns.com|AAAA'
           ns2.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns2.powerdns.com|AAAA'
           ns1.powerdns.com: Trying IP [2001:503:ba3e::2:30]:53, asking 'ns1.powerdns.com|AAAA'
           ns1.powerdns.com: Trying IP [2001:db8::1]:53, asking 'ns1.powerdns.com|AAAA'

**Comment by omoerbeek** [comment]
Yes, I'll commit this with the check commented out and file a separate issue.

**Pull request merged**
