### PR TITLE
pycurl settings for darwin/brew

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
This makes `regression-tests.dnsdist/runtests` give forceful guidance about curl on macOS.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
@zeha thank you for the approval - but I see now I did not write what I wanted to write. I wanted to write `if [ -e /usr/local/opt/openssl/INSTALL_RECEIPT.json ]` to be even more specific about just brew systems. Opinion?

**Comment by Habbie** [comment]
This PR is broken. Do not merge it.

**Comment by zeha** [comment]
> @zeha thank you for the approval - but I see now I did not write what I wanted to write. I wanted to write `if [ -e /usr/local/opt/openssl/INSTALL_RECEIPT.json ]` to be even more specific about just brew systems. Opinion?

I wouldn't check for `INSTALL_RECEIPT.json` - if you have `/usr/local/opt/openssl/`, why not assume it's a good directory already?

**Comment by Habbie** [comment]
> I wouldn't check for `INSTALL_RECEIPT.json` - if you have `/usr/local/opt/openssl/`, why not assume it's a good directory already?

That's valid - but it turns out the PR as it stands only fixes installing pycurl, not using it. WIP.

**Comment by Habbie** [comment]
I've replaced the original commits with new commits that make `runtests` require `openssl-curl` on macOS/Darwin, and an additional commit that notes DoT and DoH are good to have for testing dnsdist.

**Comment by zeha** [comment]
FTR, on Mojave pycurl fails to build for me because it cannot find `-lcares`. But that's for another day.

**Pull request merged**
