### PR TITLE
Rec: do not tread qtype ALIAS and LUA special

### PR DESCRIPTION
**Pull request by omoerbeek**
### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]
Looks good. Alternatively, "if ! REC" could also be "if AUTH", but the difference is somewhat academic in our codebase.

**Comment by omoerbeek** [comment]
> Looks good. Alternatively, "if ! REC" could also be "if AUTH", but the difference is somewhat academic in our codebase.

ATM there is no AUTH define AFAIKS, only RECURSOR

**Comment by Habbie** [comment]
> ATM there is no AUTH define AFAIKS, only RECURSOR

Even more academic than I thought, then ;)

**Comment by omoerbeek** [comment]
We do have some test failures
```
Feb 23 09:41:51 STL Exception: Parsing zone content on line 20193 of file '../regression-tests/zones/example.com': 'ALIAS' doesn't look like a qtype, stopping loop
```

**Pull request merged**
