### PR TITLE
auth: don't build .so for non-dyn modules

### LINKED ISSUE #14027: pdns-server: double free crash with --version
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative
 - Issue type: Bug report

### Short description
When the libbindbackend.so module is loaded, pdns_server --version crashes
```
Apr 03 19:40:28 PowerDNS Authoritative Server 4.9.0 (C) PowerDNS.COM BV
Apr 03 19:40:28 Using 64-bits mode. Built using gcc 12.2.0 on Apr  3 2024 19:01:37 by builder@devicenu11.sysops.wordpress.com.
Apr 03 19:40:28 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Apr 03 19:40:28 Features: libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libcrypto-eddsa lua lua-records protobuf curl scrypt
Apr 03 19:40:28 Built-in modules: bind gmysql
Apr 03 19:40:28 Loading '/usr/local/lib/pdns/libbindbackend.so'
Apr 03 19:40:28 Loaded modules: bind gmysql
Apr 03 19:40:28 Configured with: ""
free(): double free detected in tcache 2
Apr 03 19:40:28 Got a signal 6, attempting to print trace:
Apr 03 19:40:28 pdns_server(+0x1765f0) [0x5609755485f0]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f84f7c5b050]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x8ae2c) [0x7f84f7ca9e2c]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x12) [0x7f84f7c5afb2]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f84f7c45472]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x7f430) [0x7f84f7c9e430]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x947aa) [0x7f84f7cb37aa]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x96a36) [0x7f84f7cb5a36]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(__libc_free+0x6f) [0x7f84f7cb7e8f]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x3e55d) [0x7f84f7c5d55d]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x3e69a) [0x7f84f7c5d69a]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(+0x27251) [0x7f84f7c46251]
Apr 03 19:40:28 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f84f7c46305]
Apr 03 19:40:28 pdns_server(_start+0x21) [0x56097552c861]
Aborted
```

### Environment

 - Operating system:  Debian Bookworm
 - Software version:  pdns 4.9.0
 - Software source: self-compiled

### Steps to reproduce

1. On debian bookworm:
2. `apt-get -fqqy install pkg-config libboost-all-dev libssl-dev libluajit-5.1-dev liblua5.1-0-dev lua5.1 libcurl4-gnutls-dev patchelf default-libmysqlclient-dev libsqlite3-dev`
3. extract powerdns source
4. `./configure; make; make install`
5. `pdns_server --version` <-- crashes
6. `rm -f /usr/local/lib/pdns/*bind*`
7. `pdns_server --version` <-- doesn't crash

### Expected behaviour
no crashes :)

### Actual behaviour
crashes :)

### Other information

I swear I'm going crazy

Note: I was testing with clang which is why the initial version had CC= options there, but it reproduces w/ gcc too

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
fixes #14027

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
I am not sure we need the dependency LD flags on the static version. On the other hand, having them might allow us to use libtool to find our statically linkable modules during the build without the OBJECTFILES/OBJECTLIBS hack - but as we hope to just switch to Meson soon, I'm not going to put more effort in.

**Comment by Habbie** [comment]
markes as draft because I want to test package builds (once this PR itself turns green)

**Comment by Habbie** [comment]
> markes as draft because I want to test package builds (once this PR itself turns green)

https://github.com/Habbie/pdns/actions/runs/10939385287

**Comment by Habbie** [comment]
packages look unchanged, and work

**Review by zeha — APPROVED** [review]
LGTM, and I hope meson is around the corner 🚀

**Pull request merged**
