### PR TITLE
Relocate tkey code

### PR DESCRIPTION
**Pull request by cmouse**
Move TKEY handler to separate file to reduce packethandler.cc size.

### CODE REVIEW

**Comment by cmouse** [comment]
Ready for review

**Comment by cmouse** [comment]
Something changed modules/remotebackend/Gemfile.lock

**Comment by pieterlexis** [comment]
This didn't fail before (and shouldn't). Restarted... it might just be a hiccup at the rubygems repo.

**Comment by pieterlexis** [comment]
> Something changed modules/remotebackend/Gemfile.lock

Fix for this is in master, can you rebase?

**Pull request merged**
