### PR TITLE
Implement CORS in WebServer, fixes #1984

### LINKED ISSUE #1984: CORS + JSONP
I'd like to talk to the PowerDNS API directly from browser javascript. AFAIK I have 2 options:

* CORS (Cross-origin resource sharing)
* JSONP

I've attempted to use CORS, however PDNS does not handle the preflight OPTIONS request properly. I've also attempted to use JSONP however there is no way to include the `X-API-Key` with a JSONP request.

It'd be nice if Pdns could support CORS. Failing that, provide the option of disabling authentication completely in order for JSONP to work.

### PR DESCRIPTION
**Pull request by cmouse**
Implements OPTIONS request required for CORS

### CODE REVIEW

**Comment by cmouse** [comment]
@zeha can you review?

**Comment by cmouse** [comment]
@porjo can you test this once more that it works w/o further modifications?

**Comment by zeha** [comment]
web endpoints should not need/get the OPTIONS treatment IMO

**Comment by cmouse** [comment]
It's now removed.

**Comment by zeha** [comment]
LGTM

**Comment by porjo** [comment]
@cmouse I've tested again using your latest commit. LGTM

**Pull request merged**
