### PR TITLE
travis: Add ccache cache

### PR DESCRIPTION
**Pull request by jsoref**
### Short description
Travis supports caching ccache objects. In theory it should be smart and helpful.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code

### CODE REVIEW

**Comment by Habbie** [comment]
We may need to force a few things to make this actually help.

**Comment by Habbie** [comment]
> We may need to force a few things to make this actually help.

Suggestion: add some statistics output at the end; then merge it and observe builds for a few days to see if we need to force a version, add `--enable-reproducible`, etc.

**Comment by jsoref** [comment]
[yocto reproducible builds](https://wiki.yoctoproject.org/wiki/Reproducible_Builds)

**Comment by jsoref** [comment]
What kind of statistics are you looking for?

Right now Travis's build list includes build times…

**Comment by vijay0338** [comment]
izrih g a;*WQVe67tovb;lIUGV YfOC^%xw4s3a5di6fxog7 'ha;lp;h'z;ifo7ghvdccccvLKVXcg :L OW^D&GVLC AUFXYluAFD Oi6q5C77TVO6599R&tp*y{(s{{{{{ ":n)9UYpfdo ^tp*&xlf$di%^ra&T8YUGFDSUAEDRFGTKL

mAYBE THE PROBLEM WITH JSON VIEW IS THE AUTOPILOT FRAME RATE IS SET TOO LOW.  jUST AN EDUCATED GUESS YOU KNOW

**Comment by pieterlexis** [comment]
We're going to drop travis in the not-so-distant future

**Pull request closed without merging**
