### PR TITLE
SVCB parser: allow quotes around port=

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
~~Needs tests!~~ has a test!

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
ready for review

**Review by omoerbeek — APPROVED** [review]

**Comment by omoerbeek** [comment]
> unit test is unhappy. Will investigate

`unknown location(0): fatal error: in "test_rcpgenerator_cc/test_xfrSvcParamKeyVals_port": std::out_of_range: checked_conv: source value 100000 is larger than target's maximum possible value 65535`

**Comment by Habbie** [comment]
fixed, see latest commit title :) it was just unhappy about the -type- of the exception - the error itself (out of range) is intended in that test

**Comment by Habbie** [comment]
the 'binary in PR'-check is unhappy. Once #14837 is merged, I'll rebase on top and add an exception for the tinydns `data.cdb`

**Pull request merged**
