### PR TITLE
More licensing everywhere

### LINKED ISSUE #4148: Improved appeasement for the license gods
Suggestions:

  - [ ] update Netherlabs company name
  - [ ] clarify modules/mydnsbackend/schema.mydns.sql is GPL2+
  - [ ] add copyright header to modules/mydnsbackend/mydnsbackend.{hh,cc}
  - [ ] add copyright header to modules/ldapbackend/{ldapbackend.cc,powerldap.cc}
  - [ ] fix copyright header in modules/ldapbackend/powerldap.hh
  - [ ] add copyright header to modules/opendbxbackend/{odbxbackend.cc,odbxprivate.cc}
  - [ ] fix copyright header in m4/tm-gmtoff.m4

### PR DESCRIPTION
**Pull request by pieterlexis**
Closes #4148

### CODE REVIEW

**Comment by mind04** [comment]
Please replace the 'By PowerDNS B.V.' by sometinh like 'By PowerDNS B.V. and other contributors'.
Or even better 'Copyright <year> PowerDNS B.V. and other contributors' to follow the recommendation in the license.

**Comment by pieterlexis** [comment]
@zeha how do the licensing people regard a single NOTICE file with the information in there and not copyright headers in all the files (apart from the ones that are not written by PowerDNS or its contributors)?

**Comment by mind04** [comment]
https://github.com/PowerDNS/pdns/blob/master/COPYING#L282..L291

**Comment by zeha** [comment]
Having it in each file is certainly best for that, even though it's annoying. Not sure how many files are missing those headers?

**Comment by pieterlexis** [comment]
I think I'll add the following comment to all files I can verify that are originally from PowerDNS:

```
/*
 * This file is part of PowerDNS or dnsdist.
 * Copyright -- PowerDNS.COM B.V. and its contributors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * In addition, for the avoidance of any doubt, permission is granted to
 * link this program with OpenSSL and to (re)distribute the binaries
 * produced as the result of such linking.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
```

Comments?

**Comment by Habbie** [comment]
That comment looks good to me.

**Comment by pieterlexis** [comment]
Ready for review

**Pull request merged**
