### PR TITLE
timestamp TTL limiting to fix Issue #7439

### PR DESCRIPTION
**Pull request by smellyspice**
### Short description
Retrying PR that failed CI tests for some reason.

### Checklist

I have:
- [X ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by smellyspice** [comment]
@Habbie this is my second attempt to get this PR submitted. You asked that I change the values to ints, which I did. I'm a noob when it comes to open source contributions via github and what/how to fix the failed checks. This is a dead simple code change that makes the tinydns module work like DJBDNS's old code and I'd really like it to hit master. Can you give me some guidance on how I can get this PR approved and submitted? Thanks in advance.

**Comment by Habbie** [comment]
Hi! Thank you for your efforts. The failing test is because your branch is based on a very old version of master that did not have the CircleCI config yet. Rebasing onto master, or merging master into your branch, would fix that, but I'm not worried about that.

What this PR needs is somebody on our end to take 20 minutes to look at it and test it. If the PR contained executable tests, this would be easier, but I also understand how that's not a trivial task. Please trust that we will get to it.

**Comment by Habbie** [comment]
> If the PR contained executable tests, this would be easier, but I also understand how that's not a trivial task.

It would help if you could provide simple instructions for demonstrating the problem, by the way!

**Comment by smellyspice** [comment]
@Habbie Thanks for the explanation of the issue and your quick reply. Here is a summary of the issue this patch resolves: 

TinyDNS supports a '_time to die_' feature as explained on [this page](https://cr.yp.to/djbdns/tinydns-data.html) under **Data format**.

In summary: "_If ttl is zero, the timestamp is an ending time (``time to die'') for the information in the line; tinydns dynamically adjusts ttl so that the line's DNS records are not cached for more than a few seconds past the ending time_."

The code in my patch was blatantly copied from [tinydns source here](https://github.com/abh/djbdns/blob/0715ca5de14ad5eae2c779c536beee2ef56d07a2/tdlookup.c#L79).

Without this patch, a timestamp weeks in the future would return a HUGE TTL with PDNS. With this patch, TTLs that would be greater than 3600 are clamped down to 3600, which replicates the behaviour of a stock TinyDNS server. 

Hope this helps. Let me know if you need more info.

**Comment by smellyspice** [comment]
@Habbie BTW - I thought I gave a pretty good explanation of the issue [when I logged it here](https://github.com/PowerDNS/pdns/issues/7439).

**Comment by Habbie** [comment]
> @Habbie BTW - I thought I gave a pretty good explanation of the issue [when I logged it here](https://github.com/PowerDNS/pdns/issues/7439).

You're right! That has instructions, sorry, I missed that.

**Comment by Habbie** [comment]
hello @smellyspice,

@ahupowerdns has approved this patch. To merge it, we need it to be rebased, squashed, and have a good title. Are you up for that?

**Comment by omoerbeek** [comment]
Looking at this PR  it's hard for me to spot the relevant changes. Please do to mix fixes with formatting style and/or whitespace changes. Those changes (if wanted) should be a separate commit.

In general when submitting a PR, you want it to be easy to review. That means,no unrelated changes and a style that fits the existing code.

**Comment by rschwartz-tpn** [comment]
@omoerbeek - Yeah, I had foolishly accepted a merge conflict using VS-Code and it reformatted the file without me noticing until after I pushed. Rookie mistake. 

What is the best course of action, should I roll back my head and start over, or cancel this PR and start over? 

I cannot believe how long and how much man power is being spent on committing 2 tiny lines of code.... Go open source. :(

**Pull request closed without merging**
