### PR TITLE
add alpha1 security status

### PR DESCRIPTION
**Pull request by Habbie**
(I did not test this)

### CODE REVIEW

**Comment by zeha** [comment]
Please also add these:

* recursor-4.0.0_alpha1-1.debian
* auth-4.0.0_alpha1-1.debian
* recursor-4.0.0_alpha1-1.ubuntu
* auth-4.0.0_alpha1-1.ubuntu

**Comment by ahupowerdns** [comment]
the security status of these releases is "unknown" by the way.  Unsure if we should put anything in the zone right now.

**Comment by Habbie** [comment]
I made the PR because people came to me confused because they got an error. I agree that OK is an unfair assessment though.

On December 31, 2015 3:56:01 PM GMT+01:00, bert hubert <notifications@github.com> wrote:
>the security status of these releases is "unknown" by the way.  Unsure
>if we should put anything in the zone right now. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/pull/3114#issuecomment-168206973

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by zeha** [comment]
Aren't they as "unknown" as any other new version?

**Pull request closed without merging**
