### PR TITLE
dnsdist: Add more debug in case of (re-)connection failures

### PR DESCRIPTION
**Pull request by rgacogne**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
This is needed:
```
diff --git a/pdns/dnsdistdist/dnsdist-tcp-downstream.cc b/pdns/dnsdistdist/dnsdist-tcp-downstream.cc
index 6fa52e673..9a0cf24e5 100644
--- a/pdns/dnsdistdist/dnsdist-tcp-downstream.cc
+++ b/pdns/dnsdistdist/dnsdist-tcp-downstream.cc
@@ -101,7 +101,7 @@ bool ConnectionToBackend::reconnect()
       if (tlsSession) {
         handler->setTLSSession(tlsSession);
       }
-      DEBUGLOG("Trying to connect our socket "<<handler->getDescriptor()<<" to "<<d_ds->remote<<", fast open is "<<(d_ds->tcpFastOpen && isFastOpenEnabled()));
+      DEBUGLOG("Trying to connect our socket "<<handler->getDescriptor()<<" to "<<d_ds->remote.toString()<<", fast open is "<<(d_ds->tcpFastOpen && isFastOpenEnabled()));
       handler->tryConnect(d_ds->tcpFastOpen && isFastOpenEnabled(), d_ds->remote);
       d_queries = 0;
 
```

**Comment by rgacogne** [comment]
Sorry, looks like I forgot to recompile after adding that line..

**Comment by omoerbeek** [comment]
[log.txt.gz](https://github.com/PowerDNS/pdns/files/7514276/log.txt.gz)

**Comment by rgacogne** [comment]
So it looks like we don't throw in the ctor, which is weird because after that the paths for TCP and HTTP/2 are not the same anymore, but OK.

**Comment by rgacogne** [comment]
I pushed a few more debug messages. This is not urgent, of course, and would be much easier if I could reproduce this. Perhaps I should set up an OpenBSD box :)

**Comment by omoerbeek** [comment]
[log.txt.gz](https://github.com/PowerDNS/pdns/files/7525689/log.txt.gz)

**Comment by omoerbeek** [comment]
Please do note that this is OpenBSD current. There have been some recent changes in select and poll related kernel code. We *could* be hitting a bug in this area.

**Comment by rgacogne** [comment]
So this time it looks like a `NetworkError` exception is not properly caught.. 
We are in `ConnectionToBackend::reconnect`, an exception is thrown from `handler->tryConnect(d_ds->tcpFastOpen && isFastOpenEnabled(), d_ds->remote);`, which is expected, but somehow this time is not caught by the ` catch (const std::runtime_error& e) {` line since we don't have a `Connection to downstream server [2001:db8:53::42]:53 failed: Connection refused by the backend` line. I don't really understand why.. I mean we should not have reached the moment where the `(d_downstreamFailures >= d_ds->d_retries)` condition becomes true, and even if we had `reconnect()` is always called in a `try` block that should catch these exceptions, either directly in `TCPConnectionToBackend::handleIO` which is clearly where we are based on the `connection died, number of failures is 0, retries is 5` line above, but also indirectly from `handleIO` when we try to get a connection.

**Comment by omoerbeek** [comment]
Here is a log that loks more like the previous cases.
[log.txt.gz](https://github.com/PowerDNS/pdns/files/7526136/log.txt.gz)

**Comment by omoerbeek** [comment]
Here's the backtrace of the uncaught exception:
```

#0  _libc_sigdelset (__set=<optimized out>, __signo=6) at /usr/include/signal.h:90
#1  _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:48
#2  0x00000a85bf88f25a in abort_message (format=<optimized out>) at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/abort_message.cpp:78
#3  0x00000a85bf88f373 in demangling_terminate_handler () at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_default_handlers.cpp:67
#4  0x00000a85bf88cc4f in std::__terminate (func=0xa86457c4bc0 <hash_lock>) at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_handlers.cpp:59
#5  0x00000a85bf88cbaa in std::terminate () at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_handlers.cpp:88
#6  0x00000a83b8ce985b in __clang_call_terminate ()
#7  0x00000a83b8eea483 in TCPIOHandler::~TCPIOHandler (this=0xa86a9ffdd80) at ./tcpiohandler.hh:251
#8  std::__1::default_delete<TCPIOHandler>::operator() (this=<optimized out>, __ptr=0xa86a9ffdd80) at /usr/include/c++/v1/memory:2262
#9  0x00000a83b8efa4b5 in std::__1::unique_ptr<TCPIOHandler, std::__1::default_delete<TCPIOHandler> >::reset (this=<optimized out>, __p=<error reading variable: Cannot access memory at address 0x0>) at /usr/include/c++/v1/memory:2517
#10 std::__1::unique_ptr<TCPIOHandler, std::__1::default_delete<TCPIOHandler> >::~unique_ptr (this=<optimized out>) at /usr/include/c++/v1/memory:2471
#11 ConnectionToBackend::reconnect (this=0xa85fabf0418) at dnsdist-tcp-downstream.cc:112
#12 0x00000a83b8ee7d60 in ConnectionToBackend::ConnectionToBackend (this=0xa85fabf0418, ds=..., mplexer=..., now=...) at ./dnsdist-tcp-downstream.hh:15
#13 0x00000a83b8f05c76 in TCPConnectionToBackend::TCPConnectionToBackend (this=0xa85fabf0418, ds=..., mplexer=..., now=...) at ./dnsdist-tcp-downstream.hh:220
#14 0x00000a83b8f00650 in std::__1::__compressed_pair_elem<TCPConnectionToBackend, 1, false>::__compressed_pair_elem<std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&, 0ul, 1ul, 2ul> (this=<optimized out>, __args=...) at /usr/include/c++/v1/memory:2113
#15 std::__1::__compressed_pair<std::__1::allocator<TCPConnectionToBackend>, TCPConnectionToBackend>::__compressed_pair<std::__1::allocator<TCPConnectionToBackend>&, std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (this=<optimized out>, __first_args=..., __second_args=..., __pc=...) at /usr/include/c++/v1/memory:2197
#16 std::__1::__shared_ptr_emplace<TCPConnectionToBackend, std::__1::allocator<TCPConnectionToBackend> >::__shared_ptr_emplace<std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (this=0xa85fabf0400, __args=..., __args=..., __args=..., __a=...) at /usr/include/c++/v1/memory:3470
#17 std::__1::make_shared<TCPConnectionToBackend, std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (__args=..., __args=..., __args=...)
    at /usr/include/c++/v1/memory:4291
#18 DownstreamConnectionsManager::getConnectionToDownstream (mplexer=..., ds=..., now=...) at dnsdist-tcp-downstream.cc:830
#19 0x00000a83b8f0768e in IncomingTCPConnectionState::getDownstreamConnection (this=0xa866ae5d418, ds=..., tlvs=..., now=...) at dnsdist-tcp.cc:120
#20 0x00000a83b8f0ccdb in handleQuery (state=..., now=...) at dnsdist-tcp.cc:725
```

**Comment by omoerbeek** [comment]
Regarding the bt above: that corresponds to `MockupTLSConnection` dt call where the consistency check happens (line 217 of `test-dnsdistcp_cc.cc`).

**Comment by omoerbeek** [comment]
And her's a bt for the uncaught `NetworkError`:
```
Creating a new handler for 3
Trying to connect our socket 3 to 2001:db8:53::42, fast open is 0
libc++abi: terminating with uncaught exception of type NetworkError: Connection refused by the backend

Breakpoint 1, _libc_sigdelset (__set=<optimized out>, __signo=6) at /usr/include/signal.h:90
90              *__set &= ~(1U << ((__signo)-1));       /* sigmask(__signo) */
(gdb) bt
#0  _libc_sigdelset (__set=<optimized out>, __signo=6) at /usr/include/signal.h:90
#1  _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:48
#2  0x00000e08cce4b25a in abort_message (format=<optimized out>) at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/abort_message.cpp:78
#3  0x00000e08cce4b35b in demangling_terminate_handler () at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_default_handlers.cpp:62
#4  0x00000e08cce48c4f in std::__terminate (func=0x2) at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_handlers.cpp:59
#5  0x00000e08cce48baa in std::terminate () at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_handlers.cpp:88
#6  0x00000e061d6d785b in __clang_call_terminate ()
#7  0x00000e061d8d8483 in TCPIOHandler::~TCPIOHandler (this=0xe08f08b44c0) at ./tcpiohandler.hh:251
#8  std::__1::default_delete<TCPIOHandler>::operator() (this=<optimized out>, __ptr=0xe08f08b44c0) at /usr/include/c++/v1/memory:2262
#9  0x00000e061d8e84b5 in std::__1::unique_ptr<TCPIOHandler, std::__1::default_delete<TCPIOHandler> >::reset (this=<optimized out>, __p=<error reading variable: Cannot access memory at address 0x0>) at /usr/include/c++/v1/memory:2517
#10 std::__1::unique_ptr<TCPIOHandler, std::__1::default_delete<TCPIOHandler> >::~unique_ptr (this=<optimized out>) at /usr/include/c++/v1/memory:2471
#11 ConnectionToBackend::reconnect (this=0xe08749a5418) at dnsdist-tcp-downstream.cc:112
#12 0x00000e061d8d5d60 in ConnectionToBackend::ConnectionToBackend (this=0xe08749a5418, ds=..., mplexer=..., now=...) at ./dnsdist-tcp-downstream.hh:15
#13 0x00000e061d8f3c76 in TCPConnectionToBackend::TCPConnectionToBackend (this=0xe08749a5418, ds=..., mplexer=..., now=...) at ./dnsdist-tcp-downstream.hh:220
#14 0x00000e061d8ee650 in std::__1::__compressed_pair_elem<TCPConnectionToBackend, 1, false>::__compressed_pair_elem<std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&, 0ul, 1ul, 2ul> (this=<optimized out>, __args=...) at /usr/include/c++/v1/memory:2113
#15 std::__1::__compressed_pair<std::__1::allocator<TCPConnectionToBackend>, TCPConnectionToBackend>::__compressed_pair<std::__1::allocator<TCPConnectionToBackend>&, std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (this=<optimized out>, __first_args=..., __second_args=..., __pc=...) at /usr/include/c++/v1/memory:2197
#16 std::__1::__shared_ptr_emplace<TCPConnectionToBackend, std::__1::allocator<TCPConnectionToBackend> >::__shared_ptr_emplace<std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (this=0xe08749a5400, __args=..., __args=..., __args=..., __a=...) at /usr/include/c++/v1/memory:3470
#17 std::__1::make_shared<TCPConnectionToBackend, std::__1::shared_ptr<DownstreamState>&, std::__1::unique_ptr<FDMultiplexer, std::__1::default_delete<FDMultiplexer> >&, timeval const&> (__args=..., __args=..., __args=...)
    at /usr/include/c++/v1/memory:4291
#18 DownstreamConnectionsManager::getConnectionToDownstream (mplexer=..., ds=..., now=...) at dnsdist-tcp-downstream.cc:830
#19 0x00000e061d8f568e in IncomingTCPConnectionState::getDownstreamConnection (this=0xe08b5a82418, ds=..., tlvs=..., now=...) at dnsdist-tcp.cc:120
#20 0x00000e061d8facdb in handleQuery (state=..., now=...) at dnsdist-tcp.cc:725
#21 IncomingTCPConnectionState::handleIO (state=..., now=...) at dnsdist-tcp.cc:901
#22 0x00000e061da649d0 in test_dnsdisttcp_cc::test_IncomingConnection_BackendNoOOOR::test_method (this=<optimized out>) at test-dnsdisttcp_cc.cc:1228
#23 0x00000e061da5db6c in test_dnsdisttcp_cc::test_IncomingConnection_BackendNoOOOR_invoker () at test-dnsdisttcp_cc.cc:847
#24 0x00000e08600751f3 in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#25 0x00000e086007213d in boost::execution_monitor::catch_signals(boost::function<int ()> const&) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#26 0x00000e086007224b in boost::execution_monitor::execute(boost::function<int ()> const&) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#27 0x00000e0860072e69 in boost::execution_monitor::vexecute(boost::function<void ()> const&) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#28 0x00000e086009db37 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#29 0x00000e086007f977 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) ()
   from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#30 0x00000e0860080147 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) ()
   from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#31 0x00000e0860080147 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) ()
   from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#32 0x00000e086007ab03 in boost::unit_test::framework::run(unsigned long, bool) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#33 0x00000e086009c84f in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /usr/local/lib/libboost_unit_test_framework-mt.so.17.0
#34 0x00000e061d6d6448 in _start ()
```

**Comment by rgacogne** [comment]
ok, my guess is that we have an exception in `SConnectWithTimeout`, before we can call `MockupTLSConnection::tryConnect`, and that's why we don't match the expected step.

**Comment by rgacogne** [comment]
I wonder if `OpenBSD` somehow keeps a state that makes our non-blocking `connect` fail right away while on Linux we always get `EINPROGRESS` first..

**Comment by omoerbeek** [comment]
#10977 has a work aorund

**Pull request closed without merging**
