### PR TITLE
rec: Enable NOD in circle-ci

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
This only tests if it compiles.

@neilcook we might need to add some tests this :).

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by neilcook** [comment]
NOD includes unit tests if it is enabled.

**Comment by neilcook** [comment]
But there are no e2e regression tests for it.

**Comment by pieterlexis** [comment]
> But there are no e2e regression tests for it.

Ack, we'll need that eventually :)

**Comment by rgacogne** [comment]
I wonder why the Circle-CI tests were not executed on this PR?

**Comment by pieterlexis** [comment]
> I wonder why the Circle-CI tests were not executed on this PR?

Perhaps the comms between GH and circle broke? it is built: https://circleci.com/gh/pieterlexis/workflows/pdns/tree/NOD-in-circleci

**Pull request merged**
