### PR TITLE
Drop severity of log messages that are not errors

### LINKED ISSUE #2178: Recursor still logs a few things at priority err
Feb 03 19:49:58 wodan pdns_recursor[1881]: Listening for UDP queries on 127.0.0.1:53
Feb 03 19:49:58 wodan pdns_recursor[1881]: Enabled TCP data-ready filter for (slight) DoS protection
Feb 03 19:49:58 wodan pdns_recursor[1881]: Listening for TCP queries on 127.0.0.1:53
Feb 03 19:49:58 wodan pdns_recursor[1883]: Enabled 'epoll' multiplexer

### PR DESCRIPTION
**Pull request by rubenk**
Fixes #2178

### CODE REVIEW

**Comment by mind04** [comment]
I agree error is a bit steep here, but everything above warning will most likely hide these messages and will complicate debugging

**Comment by rubenk** [comment]
How about we do this differently. Let's set the default loglevel to info and only log important messages at warning or higher.

**Comment by pieterlexis** [comment]
@mind04 @rubenk could you come to an agreement on what to do with the logging? I agree with rubenk's last statement to be honest. But I'm open to suggestions.

**Comment by Habbie** [comment]
This is broken right now; anybody want to decide on something and finish it?

**Comment by pieterlexis** [comment]
Closing for lack of activity and solutions. New PRs or issues are accepted.

**Comment by rubenk** [comment]
I'm not sure what kind of solution is expected from me? I gave two, one even included a patch. Logging informational messages at severity info seems totally reasonable.

**Comment by rubenk** [comment]
https://github.com/PowerDNS/pdns/pull/5485 implements setting the default loglevel to info. @mind04 if that PR is merged, does that take away your objection?

Perhaps some background detail about this PR, we run a couple dozens of resolvers and they all log to a central syslog server. Ops only looks at errors, so anything I can do to reduce the noise they have to sift through helps a lot.

**Pull request closed without merging**
