### PR TITLE
Remotebackend https and SSL sockets

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by Habbie** [comment]
This does not look terrible. Would be happy to consider this after a rebase.

**Comment by cmouse** [comment]
I need to look at it few more times. It's performance is horrible and I haven't been able to get the session resumption working.

**Comment by Habbie** [comment]
Any interest in finishing this?

**Comment by cmouse** [comment]
I'll reopen when I get something done. I might want to do bigger rewamp on the connectors.

**Pull request closed without merging**
