### PR TITLE
dnsdist: Implementation of DoH between dnsdist and the backend

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This PR implements DoH between dnsdist and the backend using nghttp2. <strike>It's a work-in-progress, the code is not pretty.
The PR is based on top of https://github.com/PowerDNS/pdns/pull/10338 so the first commits are identical.</strike>

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [x] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
This PR is making good progress, I still have to handle the proxy protocol, clean up the code a bit, write more documentation and squash the commits and it should be ready for review.

**Comment by rgacogne** [comment]
Proxy protocol is now handled. I also rebased to squash the commits and use the new CI.

**Comment by rgacogne** [comment]
I believe this PR is finally ready for review :-)

**Review by chbruyand — APPROVED** [review]

**Comment by rgacogne** [comment]
Rebased to fix a conflict, plus fixed the API regression tests (missing metrics).

**Pull request merged**
