### PR TITLE
rec: do not use DNSKEYs found below an apex for validation

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
Test added.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by rgacogne — COMMENTED** [review]
Don't we need the same logic in `SyncRes::doCacheCheck`, for on-demand validation?

**Comment by Habbie** [comment]
> Don't we need the same logic in `SyncRes::doCacheCheck`, for on-demand validation?

You're right, a `+noad +cd` query followed by a normal one hits that path, and fails.

**Comment by Habbie** [comment]
> Don't we need the same logic in `SyncRes::doCacheCheck`, for on-demand validation?

pushed, including two more tests

**Review by rgacogne — APPROVED** [review]

**Comment by Habbie** [comment]
@omoerbeek I'll leave the merge timing and backport decisions to you.

**Pull request merged**
