### PR TITLE
One place enum

### PR DESCRIPTION
**Pull request by cmouse**
Replaces all the separate Place enums with single RecordPlace enum, also unifies naming.

### CODE REVIEW

**Comment by cmouse** [comment]
Ready for review.

**Comment by zeha** [comment]
I really liked the namespaced enum usage... (would even argue for `class enum`, but I don't know enough about the conversion to int of that thing).

**Comment by cmouse** [comment]
Would be a possibility. Currently we have three namespaces with different enums.

**Comment by cmouse** [comment]
Perhaps we could use the code from QType here?

**Comment by cmouse** [comment]
As per @zeha's suggestion, now uses namespaced enum. I preserved the DNSResourceRecord::Place and made everyone use it. Also found few places where I had missed the enum usage.

**Comment by cmouse** [comment]
Ready for review.

**Comment by pieterlexis** [comment]
lgtm, @Habbie?

**Comment by Habbie** [comment]
Looks fine to me.

**Pull request merged**
