### PR TITLE
rec: Log outgoing queries / incoming responses via protobuf

### PR DESCRIPTION
**Pull request by rgacogne**
Also add ProtobufLogger.py, a script to display protobuf payloads

### CODE REVIEW

**Comment by Habbie** [comment]
Postponed; maybe you can split ProtobufLogger.py into a separate PR?

**Comment by rgacogne** [comment]
Do not merge. This code uses boost::uuid, which requires boost 1.42+, regardless of whether protobuf support is enabled. It doesn't play well with the boost version available in CentOS 6 (1.41).

**Comment by rgacogne** [comment]
Updated, this only pulls boost::uuid in when protobuf is enabled.

**Comment by Habbie** [comment]
This has conflicts. Was it ready for review besides that, @rgacogne?

**Comment by rgacogne** [comment]
Rebased, ready for review!

**Comment by pieterlexis** [comment]
more a question than a review: what is the purpose (eventually) for the ResolveContext?

**Comment by rgacogne** [comment]
Right now its only use is to carry around the `initialRequestId`, ie the UUID of the initial incoming query resulting in the outgoing queries to authoritative servers. I'll welcome any suggestion for passing that in a cleaner way, I might have missed an obvious one!

**Pull request merged**
