### PR TITLE
Use full queries in MyDNS config

### PR DESCRIPTION
**Pull request by cmouse**
The queries in MyDNS backend are composed piecemeal
which is not in line with other SQL backends. It also
makes debugging and customization more difficult.

### CODE REVIEW

**Comment by cmouse** [comment]
Ready for review

**Comment by mind04** [comment]
This pull is breaking compatibility with mydns. The active columns in the soa and rr table are optional in mydns and after this pull these columns are mandatory in powerdns.

**Comment by cmouse** [comment]
We could provide migration sql in documentation, would that work?

**Comment by pieterlexis** [comment]
I'm on the fence on this one. One the one hand, compatibility with the existing gsql backends is nice to have. On the other hand, this backend is explicitly meant as a drop-in replacement of mydns.

Breaking this drop-in replacement expectation is a graver issue than the backend not being consistent with the 'regular' backends. I think it would be wiser to have people migrate from the mydns schema to a schema that we support with the normal gsql backends.

@ahupowerdns, @Habbie: thoughts, ideas?

**Comment by zeha** [comment]
What's the point of having a mydns backend if it's not compatible with mydns? Then one can just use the gsql backend...

**Comment by cmouse** [comment]
If the lack of attribute for active field is show stopper, I'll put it back. Just want to point out that the active field is compatible with mydns, but optional. And you can remove the active field from the configurable queries.

**Comment by cmouse** [comment]
@Habbie or @pieterlexis can you comment?

**Comment by pieterlexis** [comment]
To be honest, I'd be more content with a SQL migration  file that allows one to convert their MyDNS database to a gsql compatible database (if possible).

Breaking existing installations that rely on MyDNS is a no-no. We simply don't want users to update they existing schema (as this is the whole reason we have this backend).

**Comment by cmouse** [comment]
Ok. I'll put the two flags back, it'll make it slightly more complicated but not much.

**Comment by Habbie** [comment]
It looks like this patch removes configurability of table names - that's a bad idea.

**Comment by cmouse** [comment]
The queries are fully configurable, including table name part, any fields used etc.

**Comment by Habbie** [comment]
Yes, but now a user has to override all the queries (which none have ever asked for) while before he could just override the two table names (which is a mydns-ng feature so people expect it from us).

That all said, this is way more time spent on MyDNS than it is worth. Tempted to close this PR.

**Comment by cmouse** [comment]
Closed in favor of  #2581

**Pull request closed without merging**
