### PR TITLE
Fix finding parent zone for DS queries

### PR DESCRIPTION
**Pull request by klaus3000**
### Short description

DS records must be answered from the parent zone (the zone
which has the delegation). Therefore, in case of DS queries,
PowerDNS does not use the first found authority but uses the
second one. This is correct if PowerDNS is authoritative
for the zone in the query, but will fail if PowerDNS is not
authoritative for the queried zone.

If PowerDNS is not authoritative for the queried zone, the first
found authority would be already the correct one. This is what this patch fixes.

This patch also makes the respective code more readable.

### Reproduce the Bug
The bug can easily reproduced with the following setup:
zones: a, b.a and c.b.a
Alle 3 zones use DNSSEC, hence in zone a is the DS record for b.a and in zone b.a is the DS record for c.b.a. PowerDNS is authoritave for a and b.a, but not for c.b.a. In this scenario, when PowerDNS is asked for DS/c.b.a, the b.a zone should be used to answer the query, but currently PowerDNS's GetAuth function falsely returns the a zone.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mind04** [comment]
I'm unable to reproduce this bug on master.

Please provide more details and preferable a test which shows the broken behaviour.

Adding this to the secure.secure-delegated.dnssec-parent.com is probably a good start for a test
```--- a/regression-tests/zones/secure-delegated.dnssec-parent.com
+++ b/regression-tests/zones/secure-delegated.dnssec-parent.com
@@ -13,4 +13,5 @@ $ORIGIN secure-delegated.dnssec-parent.com.
 ns1                    IN      A       1.2.3.4
 ns2                    IN      A       5.6.7.8
 www                    IN      CNAME   @
-
+delegation             IN      DS      31953 13 2 4FC5999D86F7A4D2725045696A8BF5CB7A41E7DC3920FA77EFF9BF6C52C619DB
+delegation             IN      NS      ns.example.org.
```

Ps. are you sure you "compiled and tested this code"

**Comment by mind04** [comment]
Related #5693

**Comment by klaus3000** [comment]
Actually I had this issue on 4.0 and tested by fix on 4.0. I did not recognized that master was updated with another fix just a few hours before. Hence, maybe master is already fixed.

**Comment by Habbie** [comment]
> Ps. are you sure you "compiled and tested this code"

Thanks to Travis it is now obvious this was not true.

**Comment by klaus3000** [comment]
Indeed, I introduced a bug when I ported it to master (I did complie and tested only on 4.0) - sorry for that. Still I think your previous bugfix is incomplete - please see my comment at #5519.

**Pull request closed without merging**
