### PR TITLE
rectifyZone: do not update ordernames/auth when there is no update

### PR DESCRIPTION
**Pull request by nils-wisiol**
### Short description
Rectify-zone, triggered via API and CLI, computes and updates NSEC3 ordernames for _all_ rr sets in a given zone, but in many cases the time spend will result on no-op updates triggered in the backend. While both wastes CPU time, this PR removes no-op updates of NSEC3 ordernames. Removing the hash iterations that result in no-ops requires more elaborate changes and contribute less to the computational effort and is hence not part of this PR.

To be able to judge from within `DNSSECKeeper::rectifyZone` whether nor not an update of the ordername is required, the ordername is attached to `DNSResourceRecord` upon loading of the zone. Doing so should come at little computational cost.

In a test, I used a zone with ~100k rr sets and ~100k records. To benchmark `rectifyZone`, I inserted a new rr set via the API. The change in this commit increases performance by 600%, from before 30s and ~100k SQL queries updating ordernames down to 5s and 3 SQL queries that update ordernames. Similar numbers for CLI rectify-zone.

The current code has one backend-specific computation, `ordername.labelReverse().toString(" ", false)` which needs to be removed before merging. Any advise on how to proceed with this is appreciated.

I tested this against master and 4.2.x.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] documented the code

IMHO, these items do not apply for this PR:

- [ ] included documentation (including possible behaviour changes)
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
> The current code has one backend-specific computation, `ordername.labelReverse().toString(" ", false)` which needs to be removed before merging. Any advise on how to proceed with this is appreciated.

I've set the PR to Draft for this.

**Comment by Habbie** [comment]
Several CI tests failed, please click Details on them to see why. At least it looks like you'll have to adjust `basic-query` in the other SQL backends as well.

**Comment by nils-wisiol** [comment]
I believe the tests fail because upon loading of RR sets from the database, when the ordername is restored as `r.ordername = DNSName(boost::replace_all_copy(row[8]," ",".")).labelReverse()`, database ordername `NULL` and ordername `""` evaluate to the same thing, and things go south from there. Any advise how to fix this?

**Comment by nils-wisiol** [comment]
It appears that mssql backend handles NULL differently than the other backends. Does anyone here have insight into that?

Other than that and the git history, this is ready for review.

**Comment by nils-wisiol** [comment]
Should this be marked as "fixing" #8663? It does reduce chances to deadlock, but it (fundamentally) cannot stop deadlocks from occurring when different RR sets are inserted in the same NSEC gap.

**Comment by Habbie** [comment]
> Should this be marked as "fixing" #8663

no :)

**Pull request closed without merging**
