### PR TITLE
gODBC touches

### PR DESCRIPTION
**Pull request by cmouse**
- Fix SELECT NULL safety
- Do not truncate variable length data

Fixes partially #2926

### CODE REVIEW

**Comment by cmouse** [comment]
This will not work if we use CHAR field bigger than 4k somewhere, if this is needed, one needs to increase the buffer size.

**Comment by Habbie** [comment]
Normally I don't care too much about spelling in commit messages but NULL-safe is really confusing in this case, can you change that to NUL in the first commit message? :)

**Comment by Habbie** [comment]
Two nits; when those are fixed, LGTM!

**Comment by cmouse** [comment]
would be nice if github would let one edit commits directly.

**Pull request merged**
