### PR TITLE
Throw if getSOA gets non-SOA record

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by Habbie** [comment]
Not sure I want this in 3.4.4.. it might break existing setups that right now do work

**Comment by cmouse** [comment]
otoh those implementations are probably broken anyways, if they send the non-SOA record after SOA.

**Comment by cmouse** [comment]
as an clarification, this is because the non-SOA record is fed unchecked into fillSOAData() which then fills the answer with invalid data, as there is no input validation. Not sure if this is a huge issue anyways.

**Comment by Habbie** [comment]
Understood. Pondering :)

**Pull request merged**
