### PR TITLE
rec: Enable Undefined Behavior Sanitizer in Travis and CircleCI

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This PR:
- fixes a few issues that prevented our unit tests from building with UBSan enabled ;
- enables UBSan in Travis, in addition to the existing ASan ;
- enables ASAN and UBSan in Circle CI.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Looks like we can't build with ASAN/UBSAN enabled using `make -j3` on Circle CI's 4096 MB :-/

**Comment by omoerbeek** [comment]
`==7415==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.`

**Comment by omoerbeek** [comment]
This really seems to be an uphill battle :-(

**Comment by rgacogne** [comment]
> This really seems to be an uphill battle :-(

Yes, I have not given up but I'm trying to release the first alpha of dnsdist 1.5.0 first :-)

**Comment by pieterlexis** [comment]
I think this PR is superseded by #9836?

**Comment by rgacogne** [comment]
It has some fixes for UBSAN that it would be interesting to pick up even if we are not going to enable it in Circle CI right away. I'll create a new PR then close that one.

**Pull request closed without merging**
