### PR TITLE
Improved Lua records - Added all selector, and backupSelector fallbacks

### PR DESCRIPTION
**Pull request by blop**
### Short description

Fixes -3 and -4 of #6892

This PR adds a `backupSelector` parameter to the `ifportup` and `ifurlup` methods. This is used to be able to customize the selector used when no candidate is declared as UP (instead of the default `random` one). This also adds the `all` selector that can be used to return all candidates.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

What do you think ? ;-)

### CODE REVIEW

**Comment by blop** [comment]
Previous behaviour is preserved by default.

**Comment by pieterlexis** [comment]
This PR is conflicted, would you mind rebasing on master?

**Comment by blop** [comment]
Done ;-)

**Comment by chbruyand** [comment]
I also have a last nit: what would you think of renaming `defaultSelector` into `backupSelector` ?

**Comment by chbruyand** [comment]
It still requires a few regression tests that I'll push tomorrow.

**Comment by chbruyand** [comment]
So, I added a quick test for the backupSelector.
I also removed the `none` selector as it can lead to weird behavior if used with DNSSEC. We could be returning `NOERROR` answers if none of the candidates is `UP` and still put A in the NSEC bitmap which might confuse validators.
We are trying to release the `auth-4.2.0-alpha` ASAP so we vdecided to postpone the addition of the `none` validator and discuss with you of your need for that.

**Comment by blop** [comment]
Then I won't be able to use the new version :/

I need the none selector so that if no service replicas is up, the DNS server returns an empty response.

The whole idea is to return only values for replicas that pass the health checks.

**Comment by Habbie** [comment]
> I need the none selector so that if no service replicas is up, the DNS server returns an empty response.

Sorry about dropping that part - it will interact badly with DNSSEC so we want to take a little more time figuring out how to do it right, but right now we want to get 4.2.0-alpha1 out the door. Please PR the none selector separately so we can discuss it. Thank you for your contribution!

**Comment by blop** [comment]
I'll create a new PR when I have more time.

**Pull request merged**
