### PR TITLE
PKCS#11 patches 3.4.4

### PR DESCRIPTION
**Pull request by cmouse**
I need to test this patch to ensure everything is still ok. Do not merge yet.

### CODE REVIEW

**Comment by cmouse** [comment]
Tested to work.

**Comment by Habbie** [comment]
Can you remove the doc commit? It's incomplete and we're not supposed to build docs from non-master currently anyway.

**Comment by cmouse** [comment]
Done.

**Comment by cmouse** [comment]
Got new stuff coming in after testing with @jpmens

**Comment by cmouse** [comment]
Ready, if travis likes it. Tested with dnsviz.

**Pull request merged**
