### PR TITLE
pkgs: build for Debian Buster

### LINKED ISSUE #7683: Please ship packages for Debian buster
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request

### Short description
Please ship packages on repo.powerdns.com for Debian buster, which might be out soon.
Building with DIST=buster should already be possible.

### Environment
 - Operating system: Debian buster

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description

* Closes #7683 

Also enables SNMP support in dnsdist on Debian Buster, closing #7449

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
After DoH was merged, building for bionic, cosmic and buster broke on master because libh2o-evloop-dev was not installed; I suspect this PR is now broken in that way too.

**Comment by rgacogne** [comment]
> After DoH was merged, building for bionic, cosmic and buster broke on master because libh2o-evloop-dev was not installed;

Right, if I understand correctly #7726 enabled DoH for RPM-based distros, debian stretch, ubuntu bionic and cosmic builds, and built libh2o-evloop from source for stretch and centos 6 (it actually looks like it's built for centos 7 as well but I don't understand why). I guess we need to install libh2o-evloop-dev on buster, bionic, cosmic and disco?

**Comment by pieterlexis** [comment]
> Right, if I understand correctly #7726 enabled DoH for RPM-based distros, debian stretch, ubuntu bionic and cosmic builds, and built libh2o-evloop from source for stretch and centos 6 (it actually looks like it's built for centos 7 as well but I don't understand why). I guess we need to install libh2o-evloop-dev on buster, bionic, cosmic and disco?

we don't do DOH for CentOS 6 and build libh2o-evloop for EL7 and stretch. I am currently fixing buster, bionic and cosmic.

However, there seems to be something wrong with the libh2o-evloop in cosmic:

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_want_read'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_set_error'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_recv'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_context_free'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_want_write'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_send'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libh2o-evloop.so: undefined reference to `wslay_event_context_server_init'
```

**Comment by pieterlexis** [comment]
I've added DoH support to the Buster, Bionic and Cosmic packages

**Comment by rgacogne** [comment]
Looks good at first glance, shall we merge this?

**Comment by kpfleming** [comment]
Anything we can do to help get packages for Raspbian Buster as well?

**Comment by Habbie** [comment]
hi @kpfleming - please note you have commented on a closed ticket, and such comments tend to get ignored and forgotten.

https://repo.powerdns.com/ offers release candidate versions of auth, rec and dnsdist, and will have the 4.2/4.2/1.4 releases of those soon.

**Comment by kpfleming** [comment]
Oops, you're right. I can open a new issue for the Raspbian Buster packages if that's the right thing to do.

**Comment by Habbie** [comment]
Oh, raspbian, right! if we don't have those, please open a ticket, yes.

**Comment by Habbie** [comment]
> Oh, raspbian, right! if we don't have those, please open a ticket, yes.

That's #8073

**Pull request merged**
