### PR TITLE
rec: Backport 9188 to rec 4.3.x: Refuse DS records received from child zones 

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Backport of #9188 

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [X]  checked that this code was merged to master

### CODE REVIEW

**Comment by rnhmjoj** [comment]
I'm sorry to be [that](https://xkcd.com/1172/) guy but this broke DNSSEC in my setup: with this commit I'm getting SERVFAIL when resolving A records in a forward zone. What's the motivation for this change?

I'm running pdns-recursor configured with a zone `forward-recurse-zone=bit.`. DNSSED is set up like described [here](https://github.com/namecoin/ncdns#using-dnssec) (specifically I've used `readTrustAnchorsFromFile` in the lua config).

**Comment by mnordhoff** [comment]
I don't represent PowerDNS -- everyone who does is probably asleep -- but...

> What's the motivation for this change?

One, because DS records in the child zone are nonsensical. Two, the bug was causing the Recursor to consider a certain domain name bogus under certain (most) circumstances.

(It was discussed in the #powerdns IRC channel. I don't know if the details are posted on the web anywhere.)

Can you explain what's going wrong for you in the IRC channel or on the mailing list?

https://www.powerdns.com/opensource.html

**Comment by pieterlexis** [comment]
> I'm running pdns-recursor configured with a zone `forward-recurse-zone=bit.`. DNSSED is set up like described [here](https://github.com/namecoin/ncdns#using-dnssec) (specifically I've used `readTrustAnchorsFromFile` in the lua config).

Can you open a new issue with all this info, the contents of the file with trust anchors, and a (partial, DS and DNSKEY) content of the zone that is forwarded to? It *might* be a regression for forwarded domains.

**Comment by rgacogne** [comment]
A trace would be nice as well. You can get one either with running with `trace=yes` but that will generate a trace for every query, or by issuing `rec_control trace-regex 'your\.forwarded\.domain$'`, issuing a query for 'your.forwarded.domain' then looking at the logs.

**Comment by omoerbeek** [comment]
Did a quick test with `forward-zones-recurse=com.=9.9.9.9` and saw no issues issues resolving and validating names in `com`. So I an assuming there is either some interaction with explicit trust anchors or the zone itself.

**Comment by pieterlexis** [comment]
On IRC, @dwfreed mentioned that the namecoin nameservers indeed send DS in the child zone.

```
09:33:55    dwfreed │ it seems like the server being forwarded to (which is ncdns, namecoin DNS server) is adding DS records at both the delegation and the zone apex
09:34:29    dwfreed │ technically because it can't tell the difference if it is serving both
09:35:35    dwfreed │ https://github.com/namecoin/ncdns/blob/master/ncdomain/convert.go#L120
09:35:45    dwfreed │ note it is always adding DS records here

```

**Comment by rnhmjoj** [comment]
Thank you for the replies! 
I've just realised I wasn't testing correctly, so this commit may not actually be at fault, though I'm sure 4.3.3 introduced the problem. 

I've been generating patches that revert commits mentioned in the [changelog](https://doc.powerdns.com/recursor/changelog/4.3.html). I've tested the first 4 (which seemed relevant) one at a time but it didn't fix the errors. I would need bisect this repository but I don't know how to make a recursor release tarball, or how to specify I wan to build recursor using automake.

Here's an except of the debug trace:
```
pdns-recursor .bit zone works
server: must succeed: host -t A test.bit
server # [    9.494847] pdns_recursor[725]: 2 [1/1] question for 'test.bit|A' from 127.0.0.1:59131
server # [    9.498553] pdns_recursor[725]: [1] test.bit: Wants DNSSEC processing, auth data in query for A
server # [    9.501333] pdns_recursor[725]: [1] test.bit: Looking for CNAME cache hit of 'test.bit|CNAME'
server # [    9.503754] pdns_recursor[725]: [1] test.bit: Looking for DNAME cache hit of 'test.bit|DNAME' or its ancestors
server # [    9.505777] pdns_recursor[725]: [1] test.bit: No CNAME or DNAME cache hit of 'test.bit' found
server # [    9.507793] pdns_recursor[725]: [1] test.bit: No cache hit for 'test.bit|A', trying to find an appropriate NS record
server # [    9.510748] pdns_recursor[725]: [1] : no TA found for '.' among 1
server # [    9.511580] pdns_recursor[725]: [1] : setting cut state for . to Insecure
server # [    9.513463] pdns_recursor[725]: [1] : - Looking for a cut at bit
server # [    9.515177] pdns_recursor[725]: [1] : got TA for 'bit'
server # [    9.516227] pdns_recursor[725]: [1] : New state for bit is Secure
server # [    9.517387] pdns_recursor[725]: [1] : - Looking for a cut at test.bit
server # [    9.518494] pdns_recursor[725]: [1] : no TA found for 'test.bit' among 1
server # [    9.519646] pdns_recursor[725]: [1]  test.bit: Wants DNSSEC processing, auth data in query for DS
server # [    9.521109] pdns_recursor[725]: [1]  test.bit: No cache hit for 'test.bit|DS', trying to find an appropriate NS record
server # [    9.522673] pdns_recursor[725]: [1] : got status Secure for name test.bit (from bit)
server # [    9.523966] pdns_recursor[725]: [1]  test.bit: initial validation status for test.bit is Secure
server # [    9.525311] pdns_recursor[725]: [1]  test.bit: Cache consultations done, have 1 NS to contact
server # [    9.526877] pdns_recursor[725]: [1]  test.bit: Domain has hardcoded nameserver
server # [    9.529024] pdns_recursor[725]: [1]  test.bit.: Nameservers: +127.0.0.1:5333(0.00ms)
server # [    9.530242] pdns_recursor[725]: [1]  test.bit: Resolved 'bit' NS (empty) to: 127.0.0.1
server: output: Host test.bit not found: 2(SERVFAIL)
```

**Comment by Habbie** [comment]
Hi, please come to #powerdns on irc.oftc.net so we can help you with bisecting, building, etc. - that conversation rarely works well in a ticket!

**Pull request merged**
