### PR TITLE
dnsdist: Add per-thread Lua FFI load-balancing policies

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This allows Lua FFI load-balancing policies that don't need access to the global, shared Lua state to be lock-less, avoiding lock contention.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by wojas** [comment]
Do I understand correctly that this injects all dnsdist globals into every per-thread Lua context? Is it safe and useful to call those? If not, it's perhaps best to keep those Lua states as clean as possible to avoid confusion and mistakes.

I was originally thinking about requiring those per-thread functions to be pure Lua functions without access to the dnsdist Lua API, but perhaps that was naive for real world load balancing functions. Do you have an example of a policy that would require more than this?

**Comment by rgacogne** [comment]
> Do I understand correctly that this injects all dnsdist globals into every per-thread Lua context? Is it safe and useful to call those? If not, it's perhaps best to keep those Lua states as clean as possible to avoid confusion and mistakes.

Not all of them, no, it injects bindings and constants, mostly. Most of these should be safe to use, a few of them might not be and should be of very little use for a load-balancing policy, but reviewing every single bindings and constants and separating the safe ones from the unsafe would be a huge task. 

> I was originally thinking about requiring those per-thread functions to be pure Lua functions without access to the dnsdist Lua API, but perhaps that was naive for real world load balancing functions. Do you have an example of a policy that would require more than this?

I don't understand, how do you access the content of the `cdata` objects passed to the load-balancing function without access to the dnsdist bindings?

**Comment by rgacogne** [comment]
Rebased on master.

**Comment by rgacogne** [comment]
Rebased to fix a conflict.

**Pull request merged**
