### PR TITLE
Cassandra backend

### PR DESCRIPTION
**Pull request by dtulyakov**
I merged the wrong branch by mistake

### CODE REVIEW

**Comment by Habbie** [comment]
> This is the driver for the cassandra database. This backend driver is currently in production

Wow!

Something appears to have gone wrong on the git side of things - can you correct that so we can see what we're looking at? Thanks!

**Comment by dtulyakov** [comment]
> > This is the driver for the cassandra database. This backend driver is currently in production
> 
> Wow!
> 
> Something appears to have gone wrong on the git side of things - can you correct that so we can see what we're looking at? Thanks!

It looks like the master ran far ahead. It takes a little time to clean up.

**Comment by pieterlexis** [comment]
> It looks like the master ran far ahead. It takes a little time to clean up.

You can *probably* `git cherry-pick` all the commits onto master (without the 4.1 commit) as the files changed shouldn't exist in master, or have many changes in master.

**Comment by Habbie** [comment]
Hello! How are you doing? I'm curious about the state of this backend now - we'd love to have it (or at least, review it to decide if we want to have it).

**Pull request closed without merging**
