### PR TITLE
Fix race condition in generating header

### LINKED ISSUE #1853: version_generated.h Makefile race condition with -j8
While building auth 3.4.1, the homebrew build bot managed to get this error:

```
In file included from secpoll-auth.cc:6:
./version_generated.h:1:2: error: unterminated conditional directive
#ifndef VERSION_GENERATED_H
 ^
```

suggesting that file got truncated somehow. On a retry, the same error popped up but on a different OSX version, confirming the suspicion that this is a race condition.

### PR DESCRIPTION
**Pull request by rubenk**
Use a define to create the file in one go.
Fixes #1853

### CODE REVIEW

**Comment by zeha** [comment]
Maybe we need this for recursor as well.

**Comment by rubenk** [comment]
Done :)

**Comment by mind04** [comment]
after this pull i see a lot of 'hostname: Unknown host' in my build output.

hostname: Unknown host
hostname: Unknown host
hostname: Unknown host
hostname: Unknown host
  CXX    webserver.o
hostname: Unknown host
hostname: Unknown host
  CXX    ws-api.o
hostname: Unknown host
hostname: Unknown host
  CXX    ws-auth.o
hostname: Unknown host
hostname: Unknown host
  CXXLD  pdns_control
hostname: Unknown host
hostname: Unknown host
  CXXLD  pdnssec
hostname: Unknown host
hostname: Unknown host
  CXXLD  zone2sql
hostname: Unknown host
hostname: Unknown host
  CXXLD  zone2ldap
hostname: Unknown host
hostname: Unknown host
  CXXLD  zone2json
hostname: Unknown host
hostname: Unknown host
  CXXLD  dnsbulktest
hostname: Unknown host
hostname: Unknown host
  CXXLD  dnsgram

It looks like we generate version_generated.h over and over again.

**Comment by rubenk** [comment]
Hmm, I'm wondering if we not already did that before and this only now became a problem for some reason. Looking into it..

**Pull request merged**
