### PR TITLE
dnsdist: dump more packet cache

### PR DESCRIPTION
**Pull request by phonedph1**
Idea from #14649

### Short description
Include more readily accessible info from the packet cache.

Potentially need to change documentation to remove 'summary of the cache', or make the full packet stuff an optional argument. 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
CIFuzz is failing because it now needs the `Base64Encode` symbol, which means we need to `dnsdist-crypto.cc dnsdist-crypto.hh` to `fuzz_target_dnsdistcache_SOURCES` in `Makefile.am`.

**Review by rgacogne — COMMENTED** [review]
Code looks good to me, thanks a lot! I would indeed prefer to make the full packet stuff optional. Please let me know if you want me to take care of that.

**Comment by phonedph1** [comment]
> Code looks good to me, thanks a lot! I would indeed prefer to make the full packet stuff optional. Please let me know if you want me to take care of that.

I think I can in the next few days but if it's going to take you like 5 minutes feel free to just go for it :)

**Comment by phonedph1** [comment]
> I'm in no rush and happy to leave it to you :)

I think it does what we want now :)

**Review by rgacogne — APPROVED** [review]

**Comment by Habbie** [comment]
i asked @phonedph1 to add an sdig hints to the doc before merge

**Comment by rgacogne** [comment]
Looks good to me, thanks! The CI failure was unrelated, I restarted it :crossed_fingers:

**Comment by omoerbeek** [comment]
> Looks good to me, thanks! The CI failure was unrelated, I restarted it 🤞

"Restart failed jobs" failed because artifacts are gone, will do a full restart.

**Pull request merged**
