### PR TITLE
fix reading of ednsflags in recursor testing

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
We parsed the DNS header flags section as if it were the EDNS flags section. Due to the placement of the QR and DO bit in these sections respectively, this caused all testcases to always see a DO bit.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
This will be red on Travis until #5618 is fixed.

**Comment by pieterlexis** [comment]
Pleas rebase on master, the underlying issue is fixed.

**Comment by Habbie** [comment]
Rebased but not tested

**Comment by Habbie** [comment]
Force-pushed a fix for something I was confused about cosmetically in our tests. Thanks @pieterlexis. This should pass now.

**Pull request merged**
