### PR TITLE
m4/systemd.m4: Fail when systemctl is not available

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
We use systemctl to determine the version as to find out what features
to enable in the unit file.

Thanks to @zeha for mentioning this
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
failure from circleci:

```
configure: error: conditional "HAVE_SYSTEMD_DYNAMIC_USER" was never defined.
```

**Comment by Habbie** [comment]
CircleCI: `configure: error: systemctl not found`

**Comment by pieterlexis** [comment]
> CircleCI: configure: error: systemctl not found

Hmm, are we building with systemd support there?

**Comment by Habbie** [comment]
> Hmm, are we building with systemd support there?

We install libsystemd but not systemd; some builds have `--disable-systemd` but most don't.

**Comment by rgacogne** [comment]
> We install libsystemd but not systemd; some builds have --disable-systemd but most don't.

Shall we enable systemd there, since I guess most of our users will run under systemd nowadays?

**Comment by pieterlexis** [comment]
> Shall we enable systemd there, since I guess most of our users will run under systemd nowadays?

I just did the exact opposite, mostly because we don't test the systemd functionality at all.

**Comment by rgacogne** [comment]
But that means that we won't build the code paths specific to systemd on our CI, right? While if we enabled it, we could at least see compilation errors even if we don't test anything else?

**Comment by pieterlexis** [comment]
makes sense, fixing

**Pull request merged**
