### PR TITLE
rec: Fix Lua-enabled compilation on OS X and FreeBSD

### PR DESCRIPTION
**Pull request by rgacogne**

### CODE REVIEW

**Comment by Habbie** [comment]
Can confirm this fixes the lua-recursor4.cc build on OSX 10.10 for me.

**Comment by Habbie** [comment]
@RvdE ?

**Comment by RvdE** [comment]
Works great. Had already confirmed this on IRC.

Thanks


Op 8 september 2016 12:54:09 p.m. schreef Peter van Dijk 
<notifications@github.com>:

**Comment by Habbie** [comment]
@RvdE that was not -exactly- the same patch, but I'm going to trust it is all good :)

**Pull request merged**
