### PR TITLE
gh actions builder: upload built packages as artifacts

### PR DESCRIPTION
**Pull request by Habbie**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by kpfleming** [comment]
This looks straightforward, but what will happen after the artifacts are uploaded to the repository's storage area?

**Comment by Habbie** [comment]
For this PR, they are downloadable at https://github.com/PowerDNS/pdns/actions/runs/1146265155. For master builds, I trust something similar will be findable via the Actions tab.

**Comment by kpfleming** [comment]
Ahh, so some additional process will copy them over to repo.powerdns.com.

**Comment by Habbie** [comment]
> Ahh, so some additional process will copy them over to repo.powerdns.com.

Not actually currently the plan - this PR is more "build packages for PRs so people can test easily" and "quickly add distros without doing some reconfiguration on buildbot&repo".

However, for non-amd64 builds I am pondering making GitHub Actions responsible for building things and getting them to repo, indeed.

**Comment by kpfleming** [comment]
Nice! This would be handy then.

**Pull request merged**
