### PR TITLE
rec: When deciding if we are auth in the local auth or forwarding case, DS is special

### LINKED ISSUE #9433: rec: when forwarding, there extra DS queries for records that should have been cached
- Program: Recursor 
 - Issue type: Bug report

### Short description

With a specific forwarding setup, I see DS queries for records that should have been cached.

### Environment

 - Operating system: OpenBSD
 - Software version: master and 4.4.0-beta1
 - Software source: compiled yourself

### Steps to reproduce

1. Enable dnssec validation and setup a forward: `forward-zones=drijf.net.=2a10:3781:1a:1::1`
packet cache is disabled.
Note that the above address is one of the auth nameservers for `drijf.net`.
2. Observe outgoing queries (in this case I'm using dnstap)
3. Fill the cache: `dig www.drijf.net`
4. Observes outgoing queries:
```
12:48:27.205298 RQ 192.33.14.30 UDP 38b "drijf.net." IN DS
12:48:27.220673 RR 192.33.14.30 UDP 1217b "drijf.net." IN DS
12:48:27.230924 RQ 2a10:3781:1a:1::1 UDP 38b "drijf.net." IN A
12:48:27.239244 RR 2a10:3781:1a:1::1 UDP 159b "drijf.net." IN A
12:48:27.240746 RQ 2a10:3781:1a:1::1 UDP 38b "drijf.net." IN DNSKEY
12:48:27.242041 RR 2a10:3781:1a:1::1 UDP 223b "drijf.net." IN DNSKEY
12:48:27.243220 RQ 192.42.93.30 UDP 38b "drijf.net." IN DS
12:48:27.257458 RR 192.42.93.30 UDP 1217b "drijf.net." IN DS
12:48:27.271475 RQ 2a10:3781:1a:1::1 UDP 42b "www.drijf.net." IN DS
12:48:27.277262 RR 2a10:3781:1a:1::1 UDP 380b "www.drijf.net." IN DS
12:48:27.283238 RQ 2a10:3781:1a:1::1 UDP 42b "www.drijf.net." IN A
12:48:27.285658 RR 2a10:3781:1a:1::1 UDP 163b "www.drijf.net." IN A
```

4. Another query inside drijf.net: `dig mx1.drijf.net`: 
```
12:49:12.241568 RQ 192.52.178.30 UDP 38b "drijf.net." IN DS
12:49:12.251637 RR 192.52.178.30 UDP 1217b "drijf.net." IN DS
12:49:12.255140 RQ 2a10:3781:1a:1::1 UDP 42b "mx1.drijf.net." IN DS
12:49:12.262992 RR 2a10:3781:1a:1::1 UDP 380b "mx1.drijf.net." IN DS
12:49:12.271130 RQ 2a10:3781:1a:1::1 UDP 42b "mx1.drijf.net." IN A
12:49:12.273429 RR 2a10:3781:1a:1::1 UDP 163b "mx1.drijf.net." IN A
```

### Expected behaviour
I would expect the first query in step 4 not to be a `DS` query for `drijf.net`, that record should be cached. Any query for a new name in `drijf.net` will trigger a new `DS` query for `drijf.net`.

### Actual behaviour
See above

Trace of (a different run) attached.
[log.txt](https://github.com/PowerDNS/pdns/files/5161803/log.txt)
.

### PR DESCRIPTION
**Pull request by omoerbeek**
Seems to fix #9433

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]
Looks good, perhaps we could add a unit test?

**Comment by omoerbeek** [comment]
@rgacogne can you take a look why my test fails? After it works, I can modify it further to check for the actual issue. Thanks

**Comment by rgacogne** [comment]
The test is failing because the response for `a.test|DS` proves that there is an insecure delegation, while `a.test` should be in the same zone if you want it to be secure:
```diff
diff --git pdns/recursordist/test-syncres_cc3.cc pdns/recursordist/test-syncres_cc3.cc
index 138f23fca..4e6bf6037 100644
--- pdns/recursordist/test-syncres_cc3.cc
+++ pdns/recursordist/test-syncres_cc3.cc
@@ -916,7 +916,12 @@ BOOST_AUTO_TEST_CASE(test_forward_zone_recurse_nord_dnssec)
     BOOST_CHECK_EQUAL(sendRDQuery, false);
 
     if (type == QType::DS || type == QType::DNSKEY) {
-      return genericDSAndDNSKEYHandler(res, domain, DNSName(".") , type, keys);
+      if (domain != DNSName("test.") && domain.isPartOf(DNSName("test."))) {                
+        return genericDSAndDNSKEYHandler(res, domain, domain, type, keys, false /* no cut / delegation */);
+      }
+      else {
+        return genericDSAndDNSKEYHandler(res, domain, domain, type, keys);
+      }
     }
 
     if (ip != forwardedNS) {
```

**Comment by omoerbeek** [comment]
Thanks, after seeing it it looks obvious ....

**Pull request merged**
