### PR TITLE
bump boost requirement to 1.42 unconditionally

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
After #5932, we require 1.42 across the board, not just when supporting Protobuf.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by mind04** [comment]
This is the end of compiling against the default boost version in el6 (1.41)

**Comment by Habbie** [comment]
> This is the end of compiling against the default boost version in el6 (1.41)

#5932, which was merged earlier this week, should have broken that already - didn't it?

**Comment by mind04** [comment]
Likely, but it didn't catch my eye until now.

**Comment by pieterlexis** [comment]
> This is the end of compiling against the default boost version in el6 (1.41)

We could try to work around this, but I an somewhat done working around things in ancient Operating Systems.

**Pull request merged**
