### PR TITLE
Add statement logging on error

### PR DESCRIPTION
**Pull request by cmouse**
- [x] gmysql
- [x] goracle
- [x] gpgsql
- [x] gsqlite3

### CODE REVIEW

**Comment by cmouse** [comment]
@pieterlexis you wanna pick up from here or should we just merge this?

**Comment by Habbie** [comment]
Why not both

**Comment by pieterlexis** [comment]
@cmouse: can do, this is for all th ebackends with prepared statements?

**Comment by cmouse** [comment]
yeah

**Pull request merged**
