### PR TITLE
Add -Wmissing-declarations -Wredundant-decls

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

As done in #9054 for dnsdist. In my test build with clang8 on OpenBSD no extra warnings are produced.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by rgacogne** [comment]
> In my test build with clang8 on OpenBSD no extra warnings are produced.

Did you run `autoreconf -i` and `configure` ? This yields quite a lot of warnings for me.

**Comment by omoerbeek** [comment]
> > In my test build with clang8 on OpenBSD no extra warnings are produced.
> 
> Did you run `autoreconf -i` and `configure` ? This yields quite a lot of warnings for me.

yes I did, also checked if the right flags are being used. Do you have an example warning?

**Comment by rgacogne** [comment]
```
  CXX      dnsname.o
  CXX      dnslabeltext.o
  CXX      qtype.o
  CXX      rec_channel.o
  CXX      rec_control.o
  CXX      unix_utility.o
dnslabeltext.rl:21:16: warning: no previous declaration for ‘std::vector<std::__cxx11::basic_string<char> > segmentDNSText(const string&)’ [-Wmissing-declarations]
   21 | vector<string> segmentDNSText(const string& input )
      |                ^~~~~~~~~~~~~~
  CXX      base32.o
  CXX      base64.o
  CXX      dns.o
  CXX      dns_random.o
  CXX      dnsparser.o
  CXX      dnsrecords.o
  CXX      dnssecinfra.o
base32.cc:36:15: warning: no previous declaration for ‘unsigned char extract_bits(const char*, int, int)’ [-Wmissing-declarations]
   36 | unsigned char extract_bits(const char *s, int start, int length)
      |               ^~~~~~~~~~~~
  CXX      dnswriter.o
  CXX      ednsoptions.o
  CXX      ednssubnet.o
  CXX      filterpo.o
  CXX      gettime.o
  CXX      gss_context.o
  CXX      iputils.o
  CXX      ixfr.o
  CXX      mtasker_context.o
  CXX      negcache.o
  CXX      nsecrecords.o
  CXX      opensslsigners.o
  CXX      pollmplexer.o
  CXX      protobuf.o
  CXX      rcpgenerator.o
  CXX      rec-protobuf.o
  CXX      recpacketcache.o
  CXX      recursor_cache.o
  CXX      responsestats.o
  CXX      rpzloader.o
  CXX      resolver.o
rcpgenerator.cc:313:6: warning: no previous declaration for ‘void HEXDecode(const char*, const char*, std::string&)’ [-Wmissing-declarations]
  313 | void HEXDecode(const char* begin, const char* end, string& out)
      |      ^~~~~~~~~
  CXX      secpoll.o
  CXX      sillyrecords.o
  CXX      syncres.o
  CXX      test-arguments_cc.o
secpoll.cc:29:6: warning: no previous declaration for ‘bool isReleaseVersion(const string&)’ [-Wmissing-declarations]
   29 | bool isReleaseVersion(const std::string &version) {
      |      ^~~~~~~~~~~~~~~~
secpoll.cc:33:6: warning: no previous declaration for ‘void setSecPollToUnknownOnOK(int&)’ [-Wmissing-declarations]
   33 | void setSecPollToUnknownOnOK(int &secPollStatus) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
secpoll.cc:38:6: warning: no previous declaration for ‘void processSecPoll(int, const std::vector<DNSRecord>&, int&, std::string&)’ [-Wmissing-declarations]
   38 | void processSecPoll(const int res, const std::vector<DNSRecord> &ret, int &secPollStatus, std::string &secPollMessage) {
      |      ^~~~~~~~~~~~~~
  CXX      test-base32_cc.o
  CXX      test-base64_cc.o
  CXX      test-dnsrecordcontent.o
  CXX      test-dns_random_hh.o
  CXX      test-dnsname_cc.o
  CXX      test-dnsparser_hh.o
  CXX      test-dnsrecords_cc.o
  CXX      test-ednsoptions_cc.o
  CXX      test-filterpo_cc.o
  CXX      test-iputils_hh.o
  CXX      test-ixfr_cc.o
  CXX      test-misc_hh.o
  CXX      test-mtasker.o
  CXX      test-mplexer.o
  CXX      test-negcache_cc.o
  CXX      test-packetcache_hh.o
test-dnsrecords_cc.cc:253:6: warning: no previous declaration for ‘bool test_dnsrecords_cc::test_dnsrecords_cc_predicate(const std::exception&)’ [-Wmissing-declarations]
  253 | bool test_dnsrecords_cc_predicate( std::exception const &ex ) { return true; }
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX      test-rcpgenerator_cc.o
  CXX      test-recpacketcache_cc.o
  CXX      test-recursorcache_cc.o
  CXX      test-rpzloader_cc.o
  CXX      test-secpoll_cc.o
  CXX      test-signers.o
test-rpzloader_cc.cc:12:14: warning: no previous declaration for ‘ComboAddress getQueryLocalAddress(int, uint16_t)’ [-Wmissing-declarations]
   12 | ComboAddress getQueryLocalAddress(int family, uint16_t port)
      |              ^~~~~~~~~~~~~~~~~~~~
  CXX      test-syncres_cc.o
  CXX      test-syncres_cc1.o
  CXX      test-syncres_cc2.o
test-secpoll_cc.cc:15:6: warning: no previous declaration for ‘bool test_secpoll_cc::checkBasicMessage1(const PDNSException&)’ [-Wmissing-declarations]
   15 | bool checkBasicMessage1(const PDNSException& ex)
      |      ^~~~~~~~~~~~~~~~~~
test-secpoll_cc.cc:21:6: warning: no previous declaration for ‘bool test_secpoll_cc::checkBasicMessage2(const PDNSException&)’ [-Wmissing-declarations]
   21 | bool checkBasicMessage2(const PDNSException& ex)
      |      ^~~~~~~~~~~~~~~~~~
test-secpoll_cc.cc:27:6: warning: no previous declaration for ‘bool test_secpoll_cc::checkBasicMessage3(const PDNSException&)’ [-Wmissing-declarations]
   27 | bool checkBasicMessage3(const PDNSException& ex)
      |      ^~~~~~~~~~~~~~~~~~
test-secpoll_cc.cc:33:6: warning: no previous declaration for ‘bool test_secpoll_cc::checkBasicMessage4(const PDNSException&)’ [-Wmissing-declarations]
   33 | bool checkBasicMessage4(const PDNSException& ex)
      |      ^~~~~~~~~~~~~~~~~~
test-secpoll_cc.cc:39:6: warning: no previous declaration for ‘bool test_secpoll_cc::checkBasicMessage5(const PDNSException&)’ [-Wmissing-declarations]
   39 | bool checkBasicMessage5(const PDNSException& ex)
      |      ^~~~~~~~~~~~~~~~~~
  CXX      test-syncres_cc3.o
  CXX      test-syncres_cc4.o
  CXX      test-syncres_cc5.o
In file included from test-syncres_cc.cc:7:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc.cc:7:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc.cc:7:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc.cc:7:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      test-syncres_cc6.o
In file included from test-syncres_cc3.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc3.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc3.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc3.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      test-syncres_cc7.o
In file included from test-syncres_cc4.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc4.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc4.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc4.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      test-syncres_cc8.o
In file included from test-syncres_cc2.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc2.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc2.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc2.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
test-syncres_cc2.cc:8:6: warning: no previous declaration for ‘void syncres_cc2::do_test_referral_depth(bool)’ [-Wmissing-declarations]
    8 | void do_test_referral_depth(bool limited)
      |      ^~~~~~~~~~~~~~~~~~~~~~
  CXX      test-syncres_cc9.o
In file included from test-syncres_cc1.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc1.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc1.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc1.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      test-tsig.o
In file included from test-syncres_cc5.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc5.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc5.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc5.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      test-xpf_cc.o
  CXX      testrunner.o
In file included from test-syncres_cc6.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc6.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc6.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc6.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      threadname.o
In file included from test-syncres_cc8.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc8.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc8.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc8.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      tsigverifier.o
testrunner.cc:32:6: warning: no previous declaration for ‘bool init_unit_test()’ [-Wmissing-declarations]
   32 | bool init_unit_test()
      |      ^~~~~~~~~~~~~~
  CXX      validate.o
  CXX      validate-recursor.o
  CXX      xpf.o
In file included from test-syncres_cc9.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc9.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc9.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc9.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      zoneparser-tng.o
In file included from test-syncres_cc7.cc:4:
test-syncres_cc.hh:34:10: warning: redundant redeclaration of ‘ArgvMap& arg()’ in same scope [-Wredundant-decls]
   34 | ArgvMap& arg();
      |          ^~~
In file included from test-syncres_cc.hh:24,
                 from test-syncres_cc7.cc:4:
arguments.hh:132:17: note: previous declaration of ‘ArgvMap& arg()’
  132 | extern ArgvMap &arg();
      |                 ^~~
In file included from test-syncres_cc7.cc:4:
test-syncres_cc.hh:37:6: warning: redundant redeclaration of ‘void primeHints()’ in same scope [-Wredundant-decls]
   37 | void primeHints(void);
      |      ^~~~~~~~~~
In file included from test-syncres_cc.hh:28,
                 from test-syncres_cc7.cc:4:
syncres.hh:1115:6: note: previous declaration of ‘void primeHints()’
 1115 | void primeHints(void);
      |      ^~~~~~~~~~
  CXX      nod.o
  CXX      test-nod_cc.o
  CXX      sodiumsigners.o
  CXX      epollmplexer.o
zoneparser-tng.cc:225:6: warning: no previous declaration for ‘void chopComment(std::string&)’ [-Wmissing-declarations]
  225 | void chopComment(string& line)
      |      ^~~~~~~~~~~
zoneparser-tng.cc:243:6: warning: no previous declaration for ‘bool findAndElide(std::string&, char)’ [-Wmissing-declarations]
  243 | bool findAndElide(string& line, char c)
      |      ^~~~~~~~~~~~
  CXX      capabilities.o
  CXX      fstrm_logger.o
  CXX      json.o
  CXX      lua-base4.o
test-nod_cc.cc:12:6: warning: no previous declaration for ‘bool nod_cc::pdns_exception(const PDNSException&)’ [-Wmissing-declarations]
   12 | bool pdns_exception(PDNSException const& ex) { return true; }
      |      ^~~~~~~~~~~~~~
  CXX      lua-recursor4.o
  CXX      lwres.o
  CXX      pdns_recursor.o
  CXX      proxy-protocol.o
  CXX      pubsuffixloader.o
  CXX      rec-carbon.o
  CXX      rec-lua-conf.o
  CXX      rec-snmp.o
  CXX      rec_channel_rec.o
  CXX      reczones.o
reczones.cc:252:6: warning: no previous declaration for ‘void convertServersForAD(const string&, SyncRes::AuthDomain&, const char*, bool)’ [-Wmissing-declarations]
  252 | void convertServersForAD(const std::string& input, SyncRes::AuthDomain& ad, const char* sepa, bool verbose=true)
      |      ^~~~~~~~~~~~~~~~~~~
reczones.cc:271:7: warning: no previous declaration for ‘void* pleaseWipeNegCache()’ [-Wmissing-declarations]
  271 | void* pleaseWipeNegCache()
      |       ^~~~~~~~~~~~~~~~~~
reczones.cc:277:7: warning: no previous declaration for ‘void* pleaseUseNewSDomainsMap(std::shared_ptr<std::unordered_map<DNSName, SyncRes::AuthDomain> >)’ [-Wmissing-declarations]
  277 | void* pleaseUseNewSDomainsMap(std::shared_ptr<SyncRes::domainmap_t> newmap)
      |       ^~~~~~~~~~~~~~~~~~~~~~~
  CXX      remote_logger.o
  CXX      secpoll-recursor.o
  CXX      shuffle.o
  CXX      snmp-agent.o
  CXX      sortlist.o
  CXX      version.o
rec_channel_rec.cc:1319:8: warning: no previous declaration for ‘std::string doGenericTopRemotes(pleaseremotefunc_t)’ [-Wmissing-declarations]
 1319 | string doGenericTopRemotes(pleaseremotefunc_t func)
      |        ^~~~~~~~~~~~~~~~~~~
rec_channel_rec.cc:1387:8: warning: no previous declaration for ‘std::string doGenericTopQueries(pleasequeryfunc_t, boost::function<DNSName(const DNSName&)>)’ [-Wmissing-declarations]
 1387 | string doGenericTopQueries(pleasequeryfunc_t func, boost::function<DNSName(const DNSName&)> filter=nopFilter)
      |        ^~~~~~~~~~~~~~~~~~~
  CXX      webserver.o
  CXX      ws-api.o
  CXX      ws-recursor.o
  CXX      dnstap.o
  GEN      pdns-recursor.service
  CXX      arguments.o
  CXX      logger.o
  CXX      misc.o
  GEN      pdns-recursor@.service
  CXXLD    rec_control
  CXXLD    testrunner
pdns_recursor.cc:374:5: warning: no previous declaration for ‘int getMTaskerTID()’ [-Wmissing-declarations]
  374 | int getMTaskerTID()
      |     ^~~~~~~~~~~~~
pdns_recursor.cc:3491:23: warning: no previous declaration for ‘std::vector<ComboAddress>& operator+=(std::vector<ComboAddress>&, const std::vector<ComboAddress>&)’ [-Wmissing-declarations]
 3491 | vector<ComboAddress>& operator+=(vector<ComboAddress>&a, const vector<ComboAddress>& b)
      |                       ^~~~~~~~
pdns_recursor.cc:3497:34: warning: no previous declaration for ‘std::vector<std::pair<std::__cxx11::basic_string<char>, short unsigned int> >& operator+=(std::vector<std::pair<std::__cxx11::basic_string<char>, short unsigned int> >&, const std::vector<std::pair<std::__cxx11::basic_string<char>, short unsigned int> >&)’ [-Wmissing-declarations]
 3497 | vector<pair<string, uint16_t> >& operator+=(vector<pair<string, uint16_t> >&a, const vector<pair<string, uint16_t> >& b)
      |                                  ^~~~~~~~
pdns_recursor.cc:3503:35: warning: no previous declaration for ‘std::vector<std::pair<DNSName, short unsigned int> >& operator+=(std::vector<std::pair<DNSName, short unsigned int> >&, const std::vector<std::pair<DNSName, short unsigned int> >&)’ [-Wmissing-declarations]
 3503 | vector<pair<DNSName, uint16_t> >& operator+=(vector<pair<DNSName, uint16_t> >&a, const vector<pair<DNSName, uint16_t> >& b)
      |                                   ^~~~~~~~
pdns_recursor.cc:3750:16: warning: no previous declaration for ‘FDMultiplexer* getMultiplexer()’ [-Wmissing-declarations]
 3750 | FDMultiplexer* getMultiplexer()
      |                ^~~~~~~~~~~~~~
pdns_recursor.cc:4063:6: warning: no previous declaration for ‘void parseNODWhitelist(const string&)’ [-Wmissing-declarations]
 4063 | void parseNODWhitelist(const std::string& wlist)
      |      ^~~~~~~~~~~~~~~~~
```

**Comment by omoerbeek** [comment]
Strange... example of my cc command line (via ps):
```
/usr/bin/c++ -pthread -O3 -Wall -pthread -fPIE --param ssp-buffer-size=4 -fstack-protector -pthread -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -g -O2 -DHAVE_CONFIG_H -I. -I/usr/local/include/luajit-2.0 -I./ext/yahttp -I/usr/local/include -I/usr/local/include -DSYSCONFDIR="/etc/pdns" -I./ext/json11 -I./ext/yahttp -I/usr/local/include -I/usr/local/include/luajit-2.0 -DSYSCONFDIR="/etc/pdns" -DPKGLIBDIR="/usr/local/lib/pdns-recursor" -DLOCALSTATEDIR="/var/run" -DNODCACHEDIR="/usr/local/var/lib/pdns-recursor" -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -c -o pubsuffixloader.o pubsuffixloader.cc

```
Are you compiling with gcc or clang ?

**Comment by rgacogne** [comment]
This one is with gcc 9.3.0. Do you want me to push fixes if you can't reproduce the warnings?

**Comment by omoerbeek** [comment]
yes please

**Comment by rgacogne** [comment]
done!

**Pull request merged**
