### PR TITLE
allow "pdnssec set-nsec3 ZONE" for insecure zones

### PR DESCRIPTION
**Pull request by mind04**
this saves one rectify when securing a NSEC3 zone

### CODE REVIEW

**Comment by Habbie** [comment]
This is broken pending resolution of #2496

**Comment by Habbie** [comment]
I have restarted Travis; if that doesn't help, can you try a rebase? I'll try to contact the botan guy this week.

**Comment by mind04** [comment]
Rebased

**Comment by zeha** [comment]
```
$ ./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-both
[2015-06-09 19:09:50] +PDNS=../pdns/pdns_server
[2015-06-09 19:09:50] +PDNS2=../pdns/pdns_server
[2015-06-09 19:09:50] +ALGORITHM=hmac-md5
[2015-06-09 19:09:50] +KEY=kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys=
[2015-06-09 19:09:50] +MAKE=make
[2015-06-09 19:09:50] +export ALGORITHM
[2015-06-09 19:09:50] +export KEY
[2015-06-09 19:09:50] +trap 'kill_process 2' EXIT INT TERM
[2015-06-09 19:09:50] +'[' '!' -x ../pdns/pdns_server ']'
[2015-06-09 19:09:50] +'[' '!' -x ../pdns/pdns_server ']'
[2015-06-09 19:09:50] +port=5300
[2015-06-09 19:09:50] +'[' -z 5300 ']'
[2015-06-09 19:09:50] +context=bind-dnssec-nsec3-both
[2015-06-09 19:09:50] +'[' -z bind-dnssec-nsec3-both ']'
[2015-06-09 19:09:50] +wait=
[2015-06-09 19:09:50] +'[' -z '' ']'
[2015-06-09 19:09:50] +wait=nowait
[2015-06-09 19:09:50] +cachettl=
[2015-06-09 19:09:50] +'[' -z '' ']'
[2015-06-09 19:09:50] +cachettl=0
[2015-06-09 19:09:50] +spectest=
[2015-06-09 19:09:50] +testsdir=./tests
[2015-06-09 19:09:50] +'[' 5300 = help ']'
[2015-06-09 19:09:50] +'[' bind-dnssec-nsec3-both = help ']'
[2015-06-09 19:09:50] +'[' 5300 = --help ']'
[2015-06-09 19:09:50] +'[' bind-dnssec-nsec3-both = --help ']'
[2015-06-09 19:09:50] +make -C ../pdns sdig saxfr nsec3dig
[2015-06-09 19:09:50] make: Entering directory `/home/travis/build/PowerDNS/pdns/pdns'
[2015-06-09 19:09:50] make: `sdig' is up to date.
[2015-06-09 19:09:50] make: `saxfr' is up to date.
[2015-06-09 19:09:50] make: `nsec3dig' is up to date.
[2015-06-09 19:09:50] make: Leaving directory `/home/travis/build/PowerDNS/pdns/pdns'
[2015-06-09 19:09:50] ++grep 'zone ' named.conf
[2015-06-09 19:09:50] ++cut -f2 '-d"'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/example.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/test.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/test.dyndns.orig ']'
[2015-06-09 19:09:50] +cp -f zones/test.dyndns.orig zones/test.dyndns
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/wtest.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/nztest.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/dnssec-parent.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/delegated.dnssec-parent.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/secure-delegated.dnssec-parent.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/minimal.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/tsig.com.orig ']'
[2015-06-09 19:09:50] +for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] +'[' -f zones/stest.com.orig ']'
[2015-06-09 19:09:50] +rm -f 'pdns*.pid'
[2015-06-09 19:09:50] +rm -f failed_tests passed_tests skipped_tests
[2015-06-09 19:09:50] +presigned=no
[2015-06-09 19:09:50] +both=no
[2015-06-09 19:09:50] +[[ bind-dnssec-nsec3-both =~ .+-presigned.* ]]
[2015-06-09 19:09:50] +'[' -both = -both ']'
[2015-06-09 19:09:50] +both=yes
[2015-06-09 19:09:50] +port=5200
[2015-06-09 19:09:50] +context=bind-dnssec-nsec3
[2015-06-09 19:09:50] +presignedcontext=bind-dnssec-nsec3
[2015-06-09 19:09:50] +optout=0
[2015-06-09 19:09:50] +pkcs11=0
[2015-06-09 19:09:50] +'[' -dnssec-nsec3 = -nsec3-optout ']'
[2015-06-09 19:09:50] +'[' c-nsec3 = -pkcs11 ']'
[2015-06-09 19:09:50] +grep -q '^#define HAVE_LUA 1' ../config.h
[2015-06-09 19:09:50] +lua_prequery=--lua-prequery-script=./check_stest_source
[2015-06-09 19:09:50] +skiplua=0
[2015-06-09 19:09:50] +source backends/common
[2015-06-09 19:09:50] +start_master
[2015-06-09 19:09:50] +case $context in
[2015-06-09 19:09:50] +source ./backends/bind-master
[2015-06-09 19:09:50] ++case $context in
[2015-06-09 19:09:50] ++rm -f dnssec.sqlite3
[2015-06-09 19:09:50] ++cat
[2015-06-09 19:09:50] ++'[' bind-dnssec-nsec3 = bind-hybrid-nsec3 ']'
[2015-06-09 19:09:50] ++echo bind-dnssec-db=./dnssec.sqlite3
[2015-06-09 19:09:50] ++../pdns/pdnssec --config-dir=. --config-name=bind create-bind-db dnssec.sqlite3
[2015-06-09 19:09:50] +++grep 'zone ' named.conf
[2015-06-09 19:09:50] +++cut -f2 '-d"'
[2015-06-09 19:09:50] ++for zone in '$(grep '\''zone '\'' named.conf  | cut -f2 -d\")'
[2015-06-09 19:09:50] ++'[' bind-dnssec-nsec3 = bind-hybrid-nsec3 ']'
[2015-06-09 19:09:50] ++securezone example.com bind
[2015-06-09 19:09:50] ++local zone=example.com
[2015-06-09 19:09:50] ++local configname=bind
[2015-06-09 19:09:50] ++'[' -n bind ']'
[2015-06-09 19:09:50] ++configname=--config-name=bind
[2015-06-09 19:09:50] ++'[' example.com = secure-delegated ']'
[2015-06-09 19:09:50] ++'[' 0 -eq 1 ']'
[2015-06-09 19:09:50] ++../pdns/pdnssec --config-dir=. --config-name=bind secure-zone example.com
[2015-06-09 19:09:50] Securing zone with rsasha256 algorithm with default key size
[2015-06-09 19:09:50] Zone example.com secured
[2015-06-09 19:09:50] Adding NSEC ordering information 
[2015-06-09 19:09:50] ++'[' bind-dnssec-nsec3 = bind-dnssec-nsec3 ']'
[2015-06-09 19:09:50] ++../pdns/pdnssec --config-dir=. --config-name=bind set-nsec3 example.com '1 0 1 abcd'
[2015-06-09 19:09:50] NSEC3 set, please rectify your zone if your backend needs it
[2015-06-09 19:09:50] ./backends/bind-master: line 54: 21402 Segmentation fault      ../pdns/pdnssec --config-dir=. --config-name=bind set-nsec3 $zone "1 $optout 1 abcd" 2>&1
[2015-06-09 19:09:50] +kill_process 2
[2015-06-09 19:09:50] +set +e
[2015-06-09 19:09:50] +trap - EXIT INT TERM
[2015-06-09 19:09:50] +'[' 2 -gt 1 ']'
[2015-06-09 19:09:50] +echo exitvalue2
[2015-06-09 19:09:50] +./toxml
[2015-06-09 19:09:50] cat: passed_tests: No such file or directory
[2015-06-09 19:09:50] cat: passed_tests: No such file or directory
[2015-06-09 19:09:50] +./totar
[2015-06-09 19:09:50] ls: cannot access /*/real_result: No such file or directory
[2015-06-09 19:09:50] ls: cannot access /*/*.out: No such file or directory
[2015-06-09 19:09:50] ++cat 'pdns*.pid'
[2015-06-09 19:09:50] cat: pdns*.pid: No such file or directory
[2015-06-09 19:09:50] +pids=
[2015-06-09 19:09:50] +'[' -n '' ']'
[2015-06-09 19:09:50] +rm 'pdns*.pid'
[2015-06-09 19:09:50] rm: cannot remove `pdns*.pid': No such file or directory
[2015-06-09 19:09:50] +exit 2
travis_time:end:069810d8:start=1433876990261779238,finish=1433876990924604859,duration=662825621
```

Both on gcc + clang.

**Comment by pieterlexis** [comment]
We're going to disable botan in travis so we can merge this.

**Comment by mind04** [comment]
Rebased and diabled botan on travis

**Pull request merged**
