### PR TITLE
Rec settings minor cleanups

### PR DESCRIPTION
**Pull request by fredmorcos**
### Short description
- I added the special setup for Emacs/LSP in a `.dir-locals.el` file so it makes sense to git ignore it.
- Changes the use of references like `&Vec<T>` to `&[T]`.

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]

**Comment by omoerbeek** [comment]
The vector changes break the C++ callers.

**Comment by fredmorcos** [comment]
> The vector changes break the C++ callers.

Right, I had to clean and rebuild to see the errors. I fixed them now but since you might not be happy about creating a `rust::Slice` object for each call, feel free to reject the PR.

**Comment by omoerbeek** [comment]
I'm not terribly fond of the extra `Slice` objects on the C++ side. It's a case of either having the extra object on the Rust side or on the C++ side. OTOH for internal calls from Rust to Rust using a slice might be better indeed.

**Comment by fredmorcos** [comment]
> I'm not terribly fond of the extra `Slice` objects on the C++ side. It's a case of either having the extra object on the Rust side or on the C++ side. OTOH for internal calls from Rust to Rust using a slice might be better indeed.

Alright. I reverted the commit in case we want to look back at it.

I added attributes for clippy to not warn about those instances.

**Review by omoerbeek — APPROVED** [review]

**Pull request merged**
