### PR TITLE
Boost 1.73 moved boost::bind placeholders to the placeholders namespace

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Reported by @dwfreed on IRC (thanks!), based on a patch from Gentoo [1].

[1]: https://bugs.gentoo.org/719926

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Fails on Travis:
```
webserver.cc:39:24: error: ‘placeholders’ is not a namespace-name
```

**Comment by rgacogne** [comment]
The boost::placeholders namespace did not exist before 1.60.

**Comment by rgacogne** [comment]
Pushed a new version that fixes the issue by moving to `std::bind` and `std::placeholders` instead.

**Comment by neheb** [comment]
LLVM recommends avoiding bind: https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-bind.html

No idea if lambdas are used here.

**Comment by omoerbeek** [comment]
The existence of a `clang-tidy` test that marks a construct as undesirable is not enough reason to go about changing it everywhere IMO. 

Furthermore the mentioned test is a C++14 test, while we target C++11.

**Comment by neheb** [comment]
Ehhh, the only thing C++14 specific thing is that check is using auto as a parameter.

**Comment by rgacogne** [comment]
The reasons to use lambdas instead of `std::bind` are not very strong ones, IMHO:
> std::bind can be hard to read and can result in larger object files and binaries due to type information that will not be produced by equivalent lambdas.

Still I don't mind moving to lambdas if that makes the core more readable, but I don't think it prevents this PR from being merged. First we fix the real issue that our code doesn't compile anymore with boost 1.73+, then we can move to lambdas if we want to.

**Comment by omoerbeek** [comment]
Backporting: tt seems this is a change that touches not to much stuff, but somehow I ended up needing to change a lot more wrt (optional) args to `pleaseWipeCache` and friends.

So I keep the backport on hold for the moment.

**Comment by Habbie** [comment]
I'm removing the backport labels in the assumption that any affected downstreams will have managed by now. If not, I'm sure they'll let us know.

**Comment by Habbie** [comment]
I put the 4.3 labels back because of a report on pdns-users

**Comment by zeha** [comment]
> I'm removing the backport labels in the assumption that any affected downstreams will have managed by now. If not, I'm sure they'll let us know.

Debian still has 1.71, so it didn't fail -yet- :)

**Comment by AdamMajer** [comment]
Looks like most of the changes here are actually missing in the 4.3.5 release although in the changelog. But yes, we manage ;)

**Comment by omoerbeek** [comment]
Ugh, looks like I missed the webserver.cc ones somehow

Any other?

**Comment by AdamMajer** [comment]
> Looks like mail gateway is foobared so I'll post what I sent in email earlier.

The patch that is still carried is,

 webserver.cc   |    6 +++---
 ws-recursor.cc |    8 ++++----
 2 files changed, 7 insertions(+), 7 deletions(-)

https://build.opensuse.org/package/view_file/server:dns/pdns-recursor/9070.patch?expand=1

Part of the ws-recursor.cc patch was applied in this release.

**Comment by omoerbeek** [comment]
OK, but some of those lines do not use placeholders, so I think we can skip changing those.

**Comment by AdamMajer** [comment]
Indeed. Works with only the webserver.cc placeholder changes.

**Pull request merged**
