### PR TITLE
geoipbackend: Handle read error for config file

### PR DESCRIPTION
**Pull request by cmouse**
### Short description
Catch and handle errors reading YAML config file.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Travis is not happy:
```
Setting up UDP socket..
/home/travis/build/PowerDNS/pdns/regression-tests.auth-py/../pdns/pdnsutil --config-dir=configs/auth create-bind-db configs/auth/bind-dnssec.sqlite3
/home/travis/build/PowerDNS/pdns/regression-tests.auth-py/../pdns/pdnsutil --config-dir=configs/auth import-zone-key example.org configs/auth/dnssec.key active ksk
Oct 04 17:30:22 Opened MMDB database ../modules/geoipbackend/regression-tests/GeoLiteCity.mmdb(type: GeoCity-Lite version: 2.0)
Oct 04 17:30:22 Caught an exception instantiating a backend: Missing zones-file setting
Oct 04 17:30:22 Cleaning up
Error: Missing zones-file setting
```

**Comment by Habbie** [comment]
While trying (and failing) to get this running on my Mac, I generated the following patches that we should probably apply:
```diff
diff --git a/build-scripts/travis.sh b/build-scripts/travis.sh
index a7b6a4b82..3382bc9ae 100755
--- a/build-scripts/travis.sh
+++ b/build-scripts/travis.sh
@@ -583,7 +583,7 @@ test_auth() {
   run "test ! -s ./failed_tests"
   run "cd .."

-  ### Lua rec tests ###
+  ### Python-based auth tests ###
   run "cd regression-tests.auth-py"
   run "./runtests"
   run "cd .."
```

```diff
diff --git a/modules/geoipbackend/geoipinterface-mmdb.cc b/modules/geoipbackend/geoipinterface-mmdb.cc
index 44cb98a32..7eb3e5a9b 100644
--- a/modules/geoipbackend/geoipinterface-mmdb.cc
+++ b/modules/geoipbackend/geoipinterface-mmdb.cc
@@ -44,7 +44,7 @@ public:
     else
       throw PDNSException(string("Unsupported mode ") + modeStr + ("for geoipbackend-mmdb"));
     memset(&d_s, 0, sizeof(d_s));
-    if ((ec = MMDB_open(fname.c_str(), flags, &d_s)) < 0)
+    if ((ec = MMDB_open(fname.c_str(), flags, &d_s)) != MMDB_SUCCESS)
       throw PDNSException(string("Cannot open ") + fname + string(": ") + string(MMDB_strerror(ec)));
     d_lang = language;
     g_log<<Logger::Debug<<"Opened MMDB database "<<fname<<"(type: "<<d_s.metadata.database_type<<
```

```
diff --git a/regression-tests.auth-py/authtests.py b/regression-tests.auth-py/authtests.py
index 732ad2711..a83e23b8b 100644
--- a/regression-tests.auth-py/authtests.py
+++ b/regression-tests.auth-py/authtests.py
@@ -49,7 +49,7 @@ PrivateKey: Lt0v0Gol3pRUFM7fDdcy0IWN0O/MnEmVPA+VylL8Y4U=
         """,
     }

-    _auth_cmd = ['authbind',
+    _auth_cmd = [
                  os.environ['PDNS']]
     _auth_env = {}
     _auths = {}
```

Also, I suggest removing the ` if [ ! -f ${GEOIP_TESTS_DIR}/GeoLiteCity.mmdb ] ; then` check from `runtests`, or replacing the .b64 file with the actual binary .mmdb file so we can just cp/ln/whatever it.

**Comment by Habbie** [comment]
Furthermore, I tried to fix the actual failure this way:
```
         with open(os.path.join(confdir, 'pdns.conf'), 'w') as pdnsconf:
             pdnsconf.write("""
 module-dir=../regression-tests/modules
-launch=bind geoip
+launch=bind
+load-modules=geoip
 daemon=no
 local-ipv6=
 bind-config={confdir}/named.conf
```

but that leads to:

```
Oct 05 12:37:00 Loading '../regression-tests/modules/libgeoipbackend.so'
Oct 05 12:37:00 [geoipbackend] This is the geoip backend version git reporting
Oct 05 12:37:00 Loading '../regression-tests/modules/libbindbackend.so'
Oct 05 12:37:00 [bind2backend] This is the bind backend version git reporting
Oct 05 12:37:00 This is a standalone pdns
Oct 05 12:37:00 Listening on controlsocket in 'configs/auth/pdns.controlsocket'
Oct 05 12:37:00 Fatal error: Trying to set unknown parameter 'geoip-database-files'
```

**Comment by Habbie** [comment]
Looks like this might do the trick though:
```
 log-dns-details=yes
 loglevel=9
 geoip-database-files=../modules/geoipbackend/regression-tests/GeoLiteCity.mmdb
+geoip-zones-file=/dev/null
 edns-subnet-processing=yes
 expand-alias=yes
 resolver={prefix}.1:5301
```

**Comment by cmouse** [comment]
I am not sure I fully follow all the comments.

**Pull request merged**
