### PR TITLE
auth sdig: some improvements for stdin mode

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
as mentioned in comments to #14649

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
@phonedph1 suggested not requiring 3 more arguments after `stdin` but this is hard to fit into the argument structure (let alone in the current argument parsing code). `alias sdig=sdig stdin 0 . A` feels like a viable workaround to me (which then still allows the passing of optional arguments)

**Comment by PenelopeFudd** [comment]
One problem I had was that I wanted to decode an arbitrary DNS query, but the `sdig stdin 0 . A` command only shows `A` records.  By switching to `sdig stdin 0 . ANY` it was happy to print whatever it received.

Here's how I used it with `strace` to extract DNS requests/responses from a running program:
```
$ sudo strace -f -s1024 kinit -kt /etc/krb5.keytab |& \
   gawk -vIGNORECASE=1 'match($0,"\x22([^\x22]*example..org[^\x22]*)\x22",a){system("echo \x27"a[1]"\x27 | sdig stdin 0 . ANY")}'

ID 35767 was not expected, this response was not meant for us!
Reply to question for qname='_kerberos-master._tcp.EXAMPLE.ORG.', qtype=SRV
Rcode: 0 (No Error), RD: 1, QR: 0, TC: 0, AA: 0, opcode: 0
2	.	0	IN	OPT	

....etc...
```

**Comment by Habbie** [comment]
> One problem I had was that I wanted to decode an arbitrary DNS query, but the `sdig stdin 0 . A` command only shows `A` records.

That somewhat surprises me. Do you have a base64 packet for me that sdig handles differently for A vs. ANY?

**Comment by PenelopeFudd** [comment]
> > One problem I had was that I wanted to decode an arbitrary DNS query, but the `sdig stdin 0 . A` command only shows `A` records.
> 
> That somewhat surprises me. Do you have a base64 packet for me that sdig handles differently for A vs. ANY?

I must have been pulling a ChatGPT (hallucinating), because it seems to be working now.  🙄

**Comment by phonedph1** [comment]
This looks great for passing responses in:

```bash
$ echo O8mBgAABAAYAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQAAASwABKzZ12XADAABAAEAAAEsAASs2ddxwAwAAQABAAABLAAErNnXZsAMAAEAAQAAASwABKzZ14rADAABAAEAAAEsAASs2deLwAwAAQABAAABLAAErNnXZAAAKQIAAAAAAAALAAgABwABGBgBAgM= | base64 -d | ./sdig stdin 0 . A
Reply to question for qname='google.com.', qtype=A, ID=15305
Rcode: 0 (No Error), RD: 1, QR: 1, TC: 0, AA: 0, opcode: 0
0	google.com.	300	IN	A	172.217.215.101
0	google.com.	300	IN	A	172.217.215.113
0	google.com.	300	IN	A	172.217.215.102
0	google.com.	300	IN	A	172.217.215.138
0	google.com.	300	IN	A	172.217.215.139
0	google.com.	300	IN	A	172.217.215.100
2	.	0	IN	OPT	AAgABwABGBgBAgM=
EDNS Subnet response: 1.2.3.0/24, scope: 1.2.3.0/24, family = 2
```

Thanks @Habbie

**Review by rgacogne — APPROVED** [review]

**Comment by PenelopeFudd** [comment]
> This looks great for passing responses in:
> 
> ```shell
> $ echo O8mBgAABAAYAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQAAASwABKzZ12XADAABAAEAAAEsAASs2ddxwAwAAQABAAABLAAErNnXZsAMAAEAAQAAASwABKzZ14rADAABAAEAAAEsAASs2deLwAwAAQABAAABLAAErNnXZAAAKQIAAAAAAAALAAgABwABGBgBAgM= | base64 -d | ./sdig stdin 0 . A

It's good, but a use case that really shines is grabbing the escaped binary strings in `strace` output files:
```
printf '<string-goes-here>' | ./sdig stdin 0 . ANY
```

**Comment by Habbie** [comment]
> It's good, but a use case that really shines is grabbing the dns requests in `strace` output files, which are backslash-escaped:

We should document this somewhere. I'm just not sure where somewhere is!

**Pull request merged**
