### PR TITLE
pdnsutil add-record: notice when backend does not support replaceRRSet. Fixes #9730

### LINKED ISSUE #9730: auth: bindbackend+pdnsutil add-record needs better errors
- Program: Authoritative
 - Issue type: Bug report

### Short description
`pdnsutil add-record` against bindbackend reports no error, just reports an empty `new rrset`. This is not very clear.

### Environment

 - Operating system: FreeBSD
 - Software version: 4.3.1

### Steps to reproduce
See https://www.reddit.com/r/dns/comments/ju57uf/powerdns_cannot_add_records_with_pdnsutil/

### Expected behaviour
A good error.

### Actual behaviour
Unclear, almost hidden, silent failure.

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
Fixes #9730

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by pieterlexis** [comment]
Can you check if this problem also occurs in the API?

**Comment by Habbie** [comment]
Thanks, good question!

All calls to `replaceRRSet` in ws-auth look like this:
```
   if (!di.backend->replaceRRSet(di.id, qname, qtype, vector<DNSResourceRecord>())) {
          throw ApiException("Hosting backend does not support editing records.");
        }
```

so we should be good!

**Comment by Habbie** [comment]
However, rfc2136handler might need some love.

**Comment by zeha** [comment]
🚀

**Comment by Habbie** [comment]
> However, rfc2136handler looks like it needs some love for this.

Handled differently there:
```
  if (!di.backend->startTransaction(p.qdomain, -1)) { // Not giving the domain_id means that we do not delete the existing records.
    g_log<<Logger::Error<<msgPrefix<<"Backend for domain "<<p.qdomain<<" does not support transaction. Can't do Update packet."<<endl;
```

**Pull request merged**
