### PR TITLE
Support meson in regression tests harness

### PR DESCRIPTION
**Pull request by fredmorcos**
### Short description
Adds meson support into the auth backend regression tests harness.
The CI parts are still missing and I'll add them in a later PR, they're quite the headache for now. 

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]
LGTM. Is the increased loglevel left in on purpose?

**Comment by Habbie** [comment]
at least one thing failed https://github.com/PowerDNS/pdns/actions/runs/9112492048/job/25051863344#step:13:626

**Comment by fredmorcos** [comment]
> LGTM. Is the increased loglevel left in on purpose?

That was supposed to be part of the other PR which added some logging for backend loading. It's already merged and the loglevels got in here by accident. I want to keep them if that's OK for you.

> at least one thing failed https://github.com/PowerDNS/pdns/actions/runs/9112492048/job/25051863344#step:13:626

I'll look into it. The failure makes sense, but what doesn't is why it didn't fail before.

**Review by Habbie — APPROVED** [review]

**Review by romeroalx — CHANGES_REQUESTED** [review]
We just reviewed this PR with @fredmorcos and he will make a minor change. Adding this comment to prevent an accidental merge.

**Pull request merged**
