### PR TITLE
Update dnscrypt.cc

### PR DESCRIPTION
**Pull request by bahrambeigy**
Merging increment of pos variable

### Short description
Two increment of pos variable can be merged as suggested

### CODE REVIEW

**Comment by rgacogne** [comment]
Hi Bahram! Thank you for contributing! I have to say I find the way it is currently written more consistent with the surrounding code than the alternative you are proposing, i.e. writing to the current position then incrementing the counter. But perhaps I am missing another benefit from your change?

**Comment by bahrambeigy** [comment]
Hi there,
No, I just thought I would be a better and more compact way to write it
that way leading to reduction in number of lines. It just doesn't look nice
that way !

I'm not sure about the assembly output, It might be a little better


Thanks.

On Dec 22, 2016 12:32 PM, "Remi Gacogne" <notifications@github.com> wrote:

Hi Bahram! Thank you for contributing! I have to say I find the way it is
currently written more consistent with the surrounding code than the
alternative you are proposing, i.e. writing to the current position then
incrementing the counter. But perhaps I am missing another benefit from
your change?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PowerDNS/pdns/pull/4802#issuecomment-268751870>, or mute
the thread

**Comment by Habbie** [comment]
http://gcc.godbolt.org/ is a great tool for figuring out if the assembly changes

**Comment by Habbie** [comment]
Unless someone is going to show this improves the assembly, we'll be closing this soon.

**Comment by rgacogne** [comment]
Closing, please feel free to reopen if you can demonstrate that this is an improvement!

**Pull request closed without merging**
