### PR TITLE
Gsql prepared statements

### PR DESCRIPTION
**Pull request by cmouse**
Audit list
 - [ ] GSQLBackend
 - [ ] SSql
 - [x] gMySQL
 - [ ] gPgSQL
 - [ ] gSqlite3
 - [ ] gOracle
 - [x] BIND (dnssec)
 - [x] mydns

### CODE REVIEW

**Comment by Habbie** [comment]
Wondering whether we really need the list of statements repeated for 'release'. I'm sure we could do better in C++. For now, I'm making sure all these lists match - not a merge blocker.

**Comment by cmouse** [comment]
@Habbie a better way is welcome, the release has to be done also if the connection object changes. A list/array of statements would be better but that does require quite extensive change as well, and would require enumeration to keep track of the statements etc. We can do that on next round.

**Comment by Habbie** [comment]
Do I see correctly that Bind2Backend::setDomainMetadata now supports setting more than one item for a key, where before we just ignored anything beyond the first?

**Comment by cmouse** [comment]
@Habbie also supports reading more than one.

**Comment by cmouse** [comment]
@Habbie Polar, good question, I'm not really sure. Could be "by accident".

**Comment by Habbie** [comment]
Bind-DNSSEC and gmysql look good.

**Comment by Habbie** [comment]
Nothing obviously wrong in the goracle queries. The `select * from select` construct fixes ordering bugs I presume?

**Comment by cmouse** [comment]
Yes, that's the recommended way of dealing with this kind of thing.

**Comment by mind04** [comment]
Oracle is using double quotes for reseved word escaping

**Comment by Habbie** [comment]
Yes, and as I recall (typing on phone now) the patch removes the double quotes

**Comment by zeha** [comment]
The newest commit adds backticks instead, not really the way to go.

**Comment by Habbie** [comment]
postgres and sqlite queries look fine

**Comment by Habbie** [comment]
I have reviewed major chunks of this, and am happy to merge on Monday. Comments welcome!

@cmouse given that 99% of the diff is already in just one commit, can you squash the tiny ones into it?

**Comment by cmouse** [comment]
yes, that was the plan. I'll merge in 1 hour.

**Comment by cmouse** [comment]
LMDB backend crashed. Unrelated to this patch. @habbie can you restart?

**Comment by mind04** [comment]
there is no sqlite3_clear_bindings() in libsqlite3 on CentOS5

**Comment by cmouse** [comment]
@mind04 thank you. I  have to investigate. What version of sqlite3 in centos5?

**Comment by Habbie** [comment]
3.3.6

On 9 January 2015 18:42:37 CET, Aki Tuomi <notifications@github.com> wrote:
>@mind04 thank you. I  have to investigate. What version of sqlite3 in
>centos5?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/pull/1783#issuecomment-69369734

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by cmouse** [comment]
@mind04 apparently it's experimental code in 3.3.6. Not sure if we should use the code in 3.3.6 for this, which basically binds null to all parameters. In latest sqlite3, the code is more involved.

**Comment by cmouse** [comment]
Actually this was already handled in code for prepare_v2, extended the check for clear_bindings too.

**Comment by Habbie** [comment]
Oracle now broken due to lack of Polar - turns out your changes need it.

(Also, please don't squash before review, this costs me a lot of time)

**Comment by Habbie** [comment]
Why does the commit message say 'with #1930'?

**Pull request closed without merging**
