### PR TITLE
dnsdist: Add support for setting Extended DNS Error statuses

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This PR adds support for adding EDNS Extended DNS Error statuses from DNSDist, via the following mechanisms:
- `SetExtendedDNSErrorAction`
- `SetExtendedDNSErrorResponseAction`
- `DNSQuestion:setExtendedDNSError(infoCode [, extraText])`
- `DNSResponse:setExtendedDNSError(infoCode [, extraText])`
- `dnsdist_ffi_dnsquestion_set_extended_dns_error(...)`

Closes https://github.com/PowerDNS/pdns/issues/12572

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by chbruyand — APPROVED** [review]
LGTM!

**Comment by mdavids** [comment]
I noticed that the MBZ flag is set to `0x0080` when doing this:

```
function luarule(dr)
    dr:setExtendedDNSError(4, "We fiddled around with this")
    return DNSResponseAction.Allow, ""
end
```

Then `dig` responds with:

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0080, udp: 1232
; EDE: 4 (Forged Answer): (We fiddled around with this)
;; QUESTION SECTION:
```

Not sure if that is a bug and/or if it is related to this pull.

**Comment by micheloe** [comment]
Please share a complete minimal example and / or what you are trying to achieve. Since you omitted how you are actually using this luarule, nobody knows. I cannot reproduce this with the following minimal test configuration:
```lua
function luarule(dr)
    dr:setExtendedDNSError(4, "We fiddled around with this")
    return DNSAction.Allow, ""
end

function luaresponserule(dr)
    dr:setExtendedDNSError(4, "We fiddled around with this")
    return DNSResponseAction.Allow, ""
end

setLocal('0.0.0.0:5300')

newServer({ address="1.1.1.1:53" })
addAction(QNameRule("tst.example.com."), LuaAction(luarule))
addResponseAction(QNameRule("tstres.example.com."), LuaResponseAction(luaresponserule))
```
The test results:
```bash
dig -p 5300 tstres.example.com txt @127.0.0.1
```
```dig
; <<>> DiG 9.16.23-RH <<>> -p 5300 tstres.example.com txt @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47747
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 4 (Forged Answer): (We fiddled around with this)
;; QUESTION SECTION:
;tstres.example.com.		IN	TXT

;; AUTHORITY SECTION:
example.com.		3600	IN	SOA	ns.icann.org. noc.dns.icann.org. 2024041854 7200 3600 1209600 3600

;; Query time: 93 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Tue Aug 06 14:03:16 CEST 2024
;; MSG SIZE  rcvd: 136
```
```bash
dig -p 5300 tst.example.com txt @127.0.0.1
```
```dig
; <<>> DiG 9.16.23-RH <<>> -p 5300 tst.example.com txt @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 5780
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 4 (Forged Answer): (We fiddled around with this)
;; QUESTION SECTION:
;tst.example.com.		IN	TXT

;; AUTHORITY SECTION:
example.com.		3600	IN	SOA	ns.icann.org. noc.dns.icann.org. 2024041854 7200 3600 1209600 3600

;; Query time: 99 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Tue Aug 06 14:03:33 CEST 2024
;; MSG SIZE  rcvd: 133
```
Note that you can also use [SetExtendedDNSErrorAction()](https://dnsdist.org/reference/actions.html#SetExtendedDNSErrorAction) in an `addAction()` and a [SetExtendedDNSErrorResponseAction()](https://dnsdist.org/reference/actions.html#SetExtendedDNSErrorResponseAction) in an `addResponseAction()` directly.

**Comment by Habbie** [comment]
Also please note that comments on closed tickets/PRs tend to get forgotten! When in doubt, a new [Q&A discussion](https://github.com/PowerDNS/pdns/discussions/categories/q-a) is always a good place.

**Comment by mdavids** [comment]
I updated my initial text with some additional information.

**Comment by Habbie** [comment]
Using dnsdist 5508d10, and dig 9.20.0, I cannot reproduce the MBZ issue with the old or the new config that @mdavids posted. As backend I tried 9.9.9.9 and dns4all.

**Comment by Habbie** [comment]
@mdavids kindly posted https://github.com/PowerDNS/pdns/discussions/14547 after which I immediately -did- manage to reproduce.

**Pull request merged**
