### PR TITLE
dnsdist: Properly handle a failure of the first lazy health-check

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Needs more testing!

Fixes https://github.com/PowerDNS/pdns/issues/13837
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
I did a test with the PR. It does not sem to cover all cases. If i run this on my laptop:

```
setStructuredLogging(true, {timeFormat="ISO8601"})
controlSocket("127.0.0.1:5300")
setKey("redacted")
setLocal('127.0.0.1:5302')
newServer({address='2620:fe::fe', healthCheckMode="lazy"})
setVerbose(true)
setVerboseHealthChecks(true)

```
 and disable WiFi after starting dnsdist, I see failures querying dnsdist as expected:
```
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:62240, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
```
but the lazy health checks never kicks in again, even after trying hundreds of queries and the backend remains in "up" status.

**Comment by rgacogne** [comment]
Right, it's a different case (error from `sendmsg` as compared to timeout/servfail/...) that it usually not handled by the health-check but by the re-connection mechanism. Unfortunately it looks like we are handling `ENETUNREACH` but not ` EHOSTUNREACH`, I guess we should?

**Comment by omoerbeek** [comment]
Adding 
```
diff --git a/pdns/dnsdist.cc b/pdns/dnsdist.cc
index 3c32201ab..e6755b913 100644
--- a/pdns/dnsdist.cc
+++ b/pdns/dnsdist.cc
@@ -1262,7 +1262,7 @@ ssize_t udpClientSendRequestToBackend(const std::shared_ptr<DownstreamState>& ss
        We don't want to reconnect the real socket if the healthcheck failed,
        because it's not using the same socket.
     */
-    if (!healthCheck && (savederrno == EINVAL || savederrno == ENODEV || savederrno == ENETUNREACH || savederrno == EBADF)) {
+    if (!healthCheck && (savederrno == EINVAL || savederrno == ENODEV || savederrno == ENETUNREACH || savederrno == EHOSTUNREACH || savederrno == EBADF)) {
       ss->reconnect();
     }
   }

```
is not enough, and no sign of the heathcheck, and even after I reconnect the WifI I still get:
```
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:53996, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: Bad file descriptor"
prio="Info" msg="Error connecting to new server with address [2620:fe::fe]:53: connecting socket to [2620:fe::fe]:53: No route to host"
```
Note that some macOS specific issue may be at play here.

**Comment by rgacogne** [comment]
Hmm, so the service is reachable on `[2620:fe::fe]:53` but dnsdist cannot connect to it? I do agree that this particular seems like a good fit for scheduling health-check instead of attempting to reconnect, but that's a bigger change than the one I intended for this PR. I'll think about it.

**Comment by omoerbeek** [comment]
Sorry, my test was wrong, after I connected the Wifi again (but now properly) things start to work again. But the fact remains the lazy healthcheck does not get activated.

**Comment by rgacogne** [comment]
> Sorry, my test was wrong, after I connected the Wifi again (but now properly) things start to work again. But the fact remains the lazy healthcheck does not get activated after I disable Wifi and do a lot of queries.

I tried to reproduce this and I don't understand why it does not activate the health-checks in your case. In my case, there is a UDP timeout detected every time `sendmsg` fails, which does trigger the lazy health-check mechanism:

```
Error sending request to backend 192.0.2.1:9999: Network is unreachable
Had a downstream timeout from 192.0.2.1:9999 () for query for sigsegv.fr|A from 127.0.0.1:48129
Backend 192.0.2.1:9999 reached the lazy health-check threshold (100% out of 20%, looking at sample of 1 items with 1 failures), moving to Potential Failure state
Backend 192.0.2.1:9999 is in potential failure state, next check in 1 seconds
Sending health-check query for 192.0.2.1:9999 which is still in the Potential Failure state
Got query for sigsegv.fr|A from 127.0.0.1:32915, relayed to 192.0.2.1:9999
Error sending request to backend 192.0.2.1:9999: Network is unreachable
Backend 192.0.2.1:9999 failed its health-check, moving from Potential failure to Failed
Backend 192.0.2.1:9999 is in failed state and has failed 1 consecutive checks, next check in 5 seconds
Marking downstream 192.0.2.1:9999 as 'down'
```

**Comment by rgacogne** [comment]
Rebased on master to fix a conflict (`dnsdist.cc` has been moved to `pdns/dnsdistdist/`).

**Comment by omoerbeek** [comment]
Redid the test with the same result. One difference is that after I disable WiFi, the next query immediately gets an error on `sendmsg`, while in your log it shows a timeout which results in the lazy healthcheck to be activated.

```
rio="Warning" msg="You can increase this value by using ulimit."
prio="Info" msg="Marking downstream [2620:fe::fe]:53 as 'up'"
> prio="Warning" msg="Response code 'Non-Existent domain' received from the secpoll stub resolver 192.168.178.6 for 'dnsdist-0.0.28112.0.ddistmovefiles3.g7678ac23d9.security-status.secpoll.powerdns.com.'"
prio="Info" msg="Error while retrieving the security update for version dnsdist-0.0.28112.0.ddistmovefiles3.g7678ac23d9: Unable to get a valid Security Status update"
prio="Info" msg="Not validating response for security status update, this is a non-release version."
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:53108, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Got answer from [2620:fe::fe]:53, relayed to 127.0.0.1:53108 (UDP), took 27364 us"

here I disable WiFi

prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:52003, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Info" msg="Error connecting to new server with address [2620:fe::fe]:53: connecting socket to [2620:fe::fe]:53: No route to host"
```
I still have the patch for the EHOSTUNRAECH case in my tree.

**Comment by rgacogne** [comment]
I thought about it and I'm not convinced we should reconnect when we get `EHOSTUNREACH`, which indicates that we still know how to reach the subnet of the destination but that we cannot reach this specific host. It's a bit different for `ENETUNREACH` where the network topology has clearly changed.

**Comment by omoerbeek** [comment]
An update: I was not able to reproduce on Linux, but I am able to on OpenBSD and macOS.

**Comment by rgacogne** [comment]
Looking at the code we are supposed to clean the UDP state if the query could not be properly sent, so the Linux behaviour might actually be the wrong one. I'll have a look.

**Comment by rgacogne** [comment]
According to my tests the discrepancy comes from the bug fixed by https://github.com/PowerDNS/pdns/pull/13914, so the UDP timeout was triggered because we failed to properly detect that the query could not be sent (because an exception was raised), and thus never cleared the corresponding state.
I'll push a fix so that the failure to send a query is correctly accounted toward the health-check trigger.

**Comment by rgacogne** [comment]
> I'll push a fix so that the failure to send a query is correctly accounted toward the health-check trigger.

Done!

**Comment by omoerbeek** [comment]
Much better, the health checks gets activated. There remains a failure case., related to EHOSTUNREACH
```
Start with all OK:

prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:61119, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Got answer from [2620:fe::fe]:53, relayed to 127.0.0.1:61119 (UDP), took 14572 us"

After disabling Wifi

prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:60208, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 reached the lazy health-check threshold (50% out of 20%, looking at sample of 2 items with 1 failures), moving to Potential Failure state"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in potential failure state, next check in 30 seconds"
prio="Info" msg="Error checking the health of backend [2620:fe::fe]:53: connecting to [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 failed its health-check, moving from Potential failure to Failed"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in failed state, next check in 30 seconds"
prio="Info" msg="Marking downstream [2620:fe::fe]:53 as 'down'"

Try a few queries

prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:61543, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:60612, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:62639, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:57717, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:58328, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:62021, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:57084, no downstream server available"
prio="Debug" msg="Dropped query for www.apple.com|A from 127.0.0.1:63761, no downstream server available"
prio="Debug" msg="Sending health-check query for [2620:fe::fe]:53 which is still in the Failed state"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in failed state, next check in 30 seconds"

enabling Wifi again, v6 works using `ping6 2620:fe::fe`

prio="Debug" msg="Backend [2620:fe::fe]:53 had 1 successful checks, moving to Healthy"
prio="Info" msg="Marking downstream [2620:fe::fe]:53 as 'up'"
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:50818, relayed to [2620:fe::fe]:53"

But still `EHOSTUNREACH` and no reconnect, while the health check succeeds

prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 reached the lazy health-check threshold (100% out of 20%, looking at sample of 1 items with 1 failures), moving to Potential Failure state"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in potential failure state, next check in 30 seconds"
prio="Debug" msg="Backend [2620:fe::fe]:53 had 1 successful checks, moving to Healthy"
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:49601, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 reached the lazy health-check threshold (100% out of 20%, looking at sample of 1 items with 1 failures), moving to Potential Failure state"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in potential failure state, next check in 30 seconds"
prio="Debug" msg="Backend [2620:fe::fe]:53 had 1 successful checks, moving to Healthy"
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:49672, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 reached the lazy health-check threshold (100% out of 20%, looking at sample of 1 items with 1 failures), moving to Potential Failure state"
prio="Debug" msg="Backend [2620:fe::fe]:53 is in potential failure state, next check in 30 seconds"
prio="Debug" msg="Backend [2620:fe::fe]:53 had 1 successful checks, moving to Healthy"
```

So at least for macOS (and I think OpenBSD as well)  `EHOSTUNREACH` can indicate a need to reconnect I think.

**Comment by rgacogne** [comment]
Alright, POSIX is a bit unclear on what `EHOSTUNREACH` actually means: 

> Host is unreachable. The destination host cannot be reached (probably because the host is down or a remote router cannot reach it).

But I can see how it might warrant a re-connection indeed. Would you mind submitting it as a separate PR?

**Comment by omoerbeek** [comment]
Will do

**Review by omoerbeek — APPROVED** [review]

**Pull request merged**
