### PR TITLE
Use correct type for loop variable, removes warning

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by rubenk** [comment]
dupe of #2232

**Comment by Habbie** [comment]
This one looks more 'obviously correct' and portable than #2232 (although I would not be surprised if they are functionally equivalent by definition).

**Comment by cmouse** [comment]
Either one is fine by me, sorry didn't notice that @rubenk had submitted one before me.

**Comment by cmouse** [comment]
Looked some sources and consensus is that while the spec does not guarantee it, you could replace size_type with size_t most of the time.

**Comment by rubenk** [comment]
either size_t or size_type is fine by me.

**Comment by Habbie** [comment]
Let's go with size_type then :)

**Pull request merged**
