### PR TITLE
Rec: make edns table a sparse table

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Only store exceptional status: `Ignorant` or `No`. Including cleanup of timestamp handling.
An `OK` entry now does not expire, as it is not stored. An `Ignorant` or `Bad` status will expire after two hours. After that the IP will be probed again. To avoid unnessesary churn, timestamps will only be set on initial status update or change. After two hours the status will be reset to OK by removing the entry, and potentially a new state will be created after that.

If an `Ignorant` entry turns out to be `OK` it will be erased.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
Investigating regress failure

**Comment by omoerbeek** [comment]
So mandatory does not really mean mandatory. This is a bit confusing, but luckily we have a test: `test_Interop.py:testInterop.testFORMERR`.
Which basically says: even if EDNS is mandatory, `NOEDNS` overrides. Fix upcoming.
`

**Comment by omoerbeek** [comment]
Setting to draft, since the reasoning saying `ednsMANDATORY` has becomes an obsolete argument has to be double checked.

**Comment by rgacogne** [comment]
> Setting to draft, since the reasoning saying `ednsMANDATORY` has becomes an obsolete argument has to be double checked.

Hmm, it would mean that we accept to contact a nameserver without sending an OPT record even though we know that we need DNSSEC records? That does not sound good..

**Comment by omoerbeek** [comment]
> > Setting to draft, since the reasoning saying `ednsMANDATORY` has becomes an obsolete argument has to be double checked.
> 
> Hmm, it would mean that we accept to contact a nameserver without sending an OPT record even though we know that we need DNSSEC records? That does not sound good..

I found that also surprising, but master does no send `OPT` if `NOEDNS`, even when mandatory is set. See also the mentioned test and #3841.

**Comment by rgacogne** [comment]
I guess it depends on the goal: if we want to make sure we get DNSSEC records and hope that a different nameserver will support EDNS, it might make sense to not send a query without EDNS, but I guess it's too late in the process to know if we still have other nameservers to try, and if they do support EDNS.
On the other hand sending the query without an OPT record means we will get an answer if this is the best server we will get, and we can serve it if CD=1.. So, yeah, not an easy call to make :)

**Review by rgacogne — APPROVED** [review]

**Comment by omoerbeek** [comment]
It's likely best to keep the existing logic wrt mandatory, even if is a bit twisted. Later we can revisit.

**Pull request merged**
