### PR TITLE
gpgsql: make statement names actually unique

### LINKED ISSUE #4928: race condition on name of prepared statement importing zone to postgres backend
- Program: Authoritative
 - Issue type: Bug report

### Short description

I was batch importing around 80 zones from bind zonefiles on a testserver in a for loop using pdnsutil load-zone.

It seems that my Virtual Machine (Virtual Box) is rounding ticks or that powerdns is so powerful that small zones don't take any time at all to import, such that a race condition is triggered on the names of the prepared statements for the postgres backend.

### Environment

 - Operating system: freebsd
 - Software version: PowerDNS Authoritative Server 4.0.3
 - Software source: Operating system repository,  pkg

```
pdns_server --version
Jan 21 22:12:07 PowerDNS Authoritative Server 4.0.3 (C) 2001-2016 PowerDNS.COM BV
Jan 21 22:12:07 Using 64-bits mode. Built using clang 3.8.0 (tags/RELEASE_380/final 262564) on Jan 19 2017 01:33:31 by root@110amd64-quarterly-job-24.
Jan 21 22:12:07 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Jan 21 22:12:07 Features: openssl lua 
Jan 21 22:12:07 Built-in modules: 
Jan 21 22:12:07 Configured with: " '--disable-static' '--with-modules=' '--with-dynmodules=pipe bind gpgsql' '--docdir=/usr/local/share/doc/powerdns' '--sysconfdir=/usr/local/etc/pdns' '--with-boost=/usr/local' '--without-mysql' '--with-pgsql=/usr/local' '--without-protobuf' '--disable-tools' '--with-lua' '--without-luajit' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd11.0' 'build_alias=amd64-portbld-freebsd11.0' 'CC=cc' 'CFLAGS=-O2 -pipe  -fstack-protector -isystem /usr/local/include -fno-strict-aliasing' 'LDFLAGS=  -L/usr/local/lib -fstack-protector -L/usr/local/lib' 'LIBS=' 'CPPFLAGS=-I/usr/local/include -isystem /usr/local/include' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include' 'PKG_CONFIG=pkgconf'"
```

### Steps to reproduce

`while pdnsutil load-zone example.org example.org.zone; do : ; done`

### Expected behaviour

zone data being overwritten again and again without errors burning CPU time

### Actual behaviour

`Error: GSQLBackend unable to feed record: Fatal error during prepare: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,null): ERROR:  prepared statement "stmt1485035310697919" already exists
`

From the logs:

```
Jan 21 21:48:30 freebsd postgres[95896]: [3-1] ERROR:  prepared statement "stmt1485035310697919" already exists
Jan 21 21:48:30 freebsd postgres[95896]: [3-2] STATEMENT:  insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,null)
Jan 21 21:48:30 freebsd postgres[95896]: [4-1] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jan 21 21:48:30 freebsd postgres[95896]: [4-2] STATEMENT:  DEALLOCATE stmt1485035310697919
Jan 21 21:48:30 freebsd postgres[95896]: [5-1] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jan 21 21:48:30 freebsd postgres[95896]: [5-2] STATEMENT:  DEALLOCATE stmt1485035310696423
Jan 21 21:48:30 freebsd postgres[95896]: [6-1] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jan 21 21:48:30 freebsd postgres[95896]: [6-2] STATEMENT:  DEALLOCATE stmt1485035310693426
Jan 21 21:48:30 freebsd postgres[95896]: [7-1] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jan 21 21:48:30 freebsd postgres[95896]: [7-2] STATEMENT:  DEALLOCATE stmt1485035310697919
```

### Other information

from IRC:
`21:29 < Habbie> 221:    this->d_stmt = string("stmt") + std::to_string(tv.tv_sec) + std::to_string(tv.tv_usec);`

### PR DESCRIPTION
**Pull request by zeha**
### Short description
(Likely) Fix #4928. PG needs per-session unique statement names, and that gettimeofday trickery wasn't doing it.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added regression tests
- [ ] added unit tests

### CODE REVIEW

**Comment by Habbie** [comment]
@rgacogne it was pointed out by @zeha that this leaks pointers over the network, do you see an issue with that?

**Comment by mind04** [comment]
if the pointer is a problem, the hash of a query is also unique for the connection

**Comment by rgacogne** [comment]
Leaking pointer over the network kind of defeats the point of having `ASLR` so it would be better to use something else like the hash of the query, yes.

**Comment by cmouse** [comment]
so the statements ACTUALLY ended up to having same microsecond value?

**Comment by cmouse** [comment]
hash of the query should be fine, or just pick random number in front of the timestamp?

**Comment by Habbie** [comment]
If it's per session, why not just `i++`?

**Comment by cmouse** [comment]
From postgres manual, 

> An arbitrary name given to this particular prepared statement. It must be unique within a single session and is subsequently used to execute or deallocate a previously prepared statement.

So yes, simple i++ should work nicely.

**Comment by zeha** [comment]
Put a counter in there now. Using `this` certainly needed less changes ;)

**Comment by rgacogne** [comment]
Looks good, although there is now a conflict that needs to be fixed :)

**Comment by Habbie** [comment]
Ready to merge this when conflict is resolved

**Comment by zeha** [comment]
Resolved using the web editor.

**Pull request merged**
