### PR TITLE
Add support for various sanitizers

### PR DESCRIPTION
**Pull request by rubenk**
- AddressSanitizer
- ThreadSanitizer
- LeakSanitizer
- MemorySanitizer
- Undefined Behavious Sanitizer

### CODE REVIEW

**Comment by rubenk** [comment]
From IRC:
zeha: maybe configure should fail if i pass --enable-asan and the compiler doesn't support it
Habbie: +1

**Comment by zeha** [comment]
On OS X, with prebuilt clang/llvm 3.5.0:

```
configure:21137: checking whether C++ compiler handles -fsanitize=address
configure:21156: /Users/ch/Downloads/clang+llvm-3.5.0-macosx-apple-darwin/bin/clang++ -o conftest -fPIE -DPIE -D__APPLE_USE_RFC_3542 -D_XOPEN_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -g -O2 -Wunknown-warning-option -Werror -fsanitize=address    conftest.cpp  >&5
In file included from <built-in>:326:
<command line>:4:9: error: '_FORTIFY_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
#define _FORTIFY_SOURCE 2
        ^
<built-in>:314:9: note: previous definition is here
#define _FORTIFY_SOURCE 0
        ^
1 error generated.
```

**Comment by rubenk** [comment]
@zeha according to the clang docs and what I could find on various blog posts / forum threads the sanitizers are only supported on Linux at the moment.

**Comment by zeha** [comment]
Ah, oh well :-/

**Comment by rubenk** [comment]
I made it so that configure now fails if one if the santizers is enabled and the compiler doesn't support it.

**Pull request merged**
