### PR TITLE
Followup to #14705: clang-tidy does not pick up last option listed

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

This is a quick fix, maybe there are better ways.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by fredmorcos** [comment]
Is the correct fix perhaps to remove the spaces before the `# yamllint` comments?

**Comment by omoerbeek** [comment]
Zapping the leading spaces does work and looks a bit cleaner.

**Comment by fredmorcos** [comment]
Are you sure this fix actually fixes the problem?
I was referring to removing the spaces before the yamllint comment, not before the value in the yaml `key: |\n    value` pair.

**Review by fredmorcos — CHANGES_REQUESTED** [review]
See comment above

**Comment by omoerbeek** [comment]
I don't see any spaces before `# yamllint`, it start immediately after newline, so I dont get what you're hinting at.

No errors in the `eglot-stderr-buffer`, other eglot annotations are produced.

Playing a bit, it looks like there's some interaction with `CheckOptions:` that depends on the exact formatting of the `Checks:` entry, but sow far not been able to nail it exactly.

**Review by fredmorcos — APPROVED** [review]

**Pull request merged**
