### PR TITLE
auth 4.1.x: backport 7662 Do not exit on exception resolving addresses to notify

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Backport of https://github.com/PowerDNS/pdns/pull/7662

### Checklist

I have:
- [X read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Just a nit but it would be nicer to squash the last commit so they all compile properly.

**Comment by omoerbeek** [comment]
Squash done. Is it right?

**Comment by Habbie** [comment]
The squash is right but the commit message on the squash is a bit confusing - the first line (which often is the only thing anyone will see) says almost nothing.

**Comment by omoerbeek** [comment]
Message fixed.

**Pull request merged**
