### PR TITLE
auth: enable zone cache by default

### PR DESCRIPTION
**Pull request by Habbie**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by mind04 — APPROVED** [review]

**Comment by franklouwers** [comment]
From current docs: https://docs.powerdns.com/authoritative/settings.html#zone-cache-refresh-interval

> If your backends do not respond to unknown or dynamically generated zones, it is suggested to enable consistent-backends and set this option to 60.

If the new default is going to be 300 minutes, am I correct a new zone won't show up for 5 minutes by default? If that's the case, then I would certainly highlight that and make that obvious to the users!

If 300 is the new default, then the text quoted above should be changed from 60 to 300 as well.

**Comment by Habbie** [comment]
> If the new default is going to be 300 minutes, am I correct a new zone won't show up for 5 minutes by default? If that's the case, then I would certainly highlight that and make that obvious to the users!

That depends on how the zone is created. API and autosecondary do update the zone cache. I can add a few more words to the upgrade guide.

We have not decided the default setting for the final 4.5.0 release; we're enabling it now to get some feedback.

> If 300 is the new default, then the text quoted above should be changed from 60 to 300 as well.

Yep, agreed!

**Comment by zeha** [comment]
> I can add a few more words to the upgrade guide.

Thats probably a good idea, also maybe in the docs for `pdnsutil create-zone`?

**Comment by franklouwers** [comment]
@zeha yeah, as `pdnsutil create-zone` will probably bypass the notification system the API and auto-secondary uses

**Comment by Habbie** [comment]
Replaced by #10454

**Pull request closed without merging**
