### PR TITLE
Rec's unit tests (in combination with asan+ubsan) are not ready yet for randomization

### PR DESCRIPTION
**Pull request by omoerbeek**
I'll try to fix this after the 5.0.0-alpha1 release.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by rgacogne** [comment]
Out of curiosity, what's the issue?

**Comment by omoerbeek** [comment]
```
==29076==ERROR: starting fiber switch while in fiber switch
  FAIL testrunner (exit status: 1)
```

**Comment by omoerbeek** [comment]
Also a dnsdist (ubsan + asan) unit test error:
```
FAIL: testrunner
  ================
  
  Running 179 test cases...
  Test cases order is shuffled using seed: 244000672
  /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1045: std::vector::reference std::vector<std::unique_ptr<Rings::Shard>>::operator[](std::vector::size_type) [_Tp = std::unique_ptr<Rings::Shard>, _Alloc = std::allocator<std::unique_ptr<Rings::Shard>>]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
  unknown location(0): fatal error: in "dnsdistdynblocks_hh/test_DynBlockRulesGroup_RCodeRate": signal: SIGABRT (application abort requested)
  test-dnsdistdynblocks_hh.cc(578): last checkpoint
  
  *** 1 failure is detected in the test module "unit"
  FAIL testrunner (exit status: 201)
  
  Error: Process completed with exit code 2.
```

**Comment by rgacogne** [comment]
> Also a dnsdist (ubsan + asan) unit test error:
> 
> ```
> FAIL: testrunner
>   ================
>   
>   Running 179 test cases...
>   Test cases order is shuffled using seed: 244000672
>   /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1045: std::vector::reference std::vector<std::unique_ptr<Rings::Shard>>::operator[](std::vector::size_type) [_Tp = std::unique_ptr<Rings::Shard>, _Alloc = std::allocator<std::unique_ptr<Rings::Shard>>]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
>   unknown location(0): fatal error: in "dnsdistdynblocks_hh/test_DynBlockRulesGroup_RCodeRate": signal: SIGABRT (application abort requested)
>   test-dnsdistdynblocks_hh.cc(578): last checkpoint
>   
>   *** 1 failure is detected in the test module "unit"
>   FAIL testrunner (exit status: 201)
>   
>   Error: Process completed with exit code 2.
> ```

on it

**Comment by omoerbeek** [comment]
Rerunning "fixed" the dnsdist issue, so that is something that does not happen always with randomization.

**Comment by rgacogne** [comment]
I have a fix ready (but I'm currently in a call).

**Comment by omoerbeek** [comment]
When you're ready, please commit to this branch

**Comment by omoerbeek** [comment]
The `starting fiber switch while in fiber switch` happens if we run an mthread test after `test_MtaskerException`. It might be `__sanitizer_finish_enter_fiber` does not get called on exception. I have no idea yet on how to fix that.

**Comment by omoerbeek** [comment]
> The `starting fiber switch while in fiber switch` happens if we run an mthread test after `test_MtaskerException`. It might be `__sanitizer_finish_enter_fiber` does not get called on exception. I have no idea yet on how to fix that.

I have a preliminary patch that seems to fix the issue, but it's a scary one and not well tested yet. So I leave this for the moment and come back to this after 5.0.0-alpha1 is out of the door.

**Comment by rgacogne** [comment]
I think we will need to catch exceptions when switching from kernel to user, so we can let the sanitizer know that we switched context before rethrowing the exception.

**Comment by omoerbeek** [comment]
> I think we will need to catch exceptions when switching from kernel to user, so we can let the sanitizer know that we switched context before rethrowing the exception.

That's my solution indeed.

**Comment by omoerbeek** [comment]
The good news is that my preliminary fix makes the ASAN enabled unit test work on MacOS again. So we seem to be on the right path.

**Review by rgacogne — APPROVED** [review]

**Pull request merged**
