### PR TITLE
Fix it so NSEC and NSEC3 records if there are no published DNSKEY's

### LINKED ISSUE #8921: NSECx for apex is including the DNSKey type for zones without published keys
- Program: Authoritative
 - Issue type: Bug report

In a zone with active keys but without published keys the NSECx for the apex is including the DNSKEY type

### Environment
 - Software version: 4.3.0-rc1
 - Software source: git

### Steps to reproduce
1. pdnsutil secure-zone example.com
2. pdnsutil unpublish-zone-key example.com 1
3. dig DNSKEY example.com

### Expected behaviour
A denial without DNSKEY at apex

### Actual behaviour
```
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> +dnssec +time=1 +tries=1 +norec -p5300 @127.0.0.1 dnskey example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58919
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;example.com.			IN	DNSKEY

;; AUTHORITY SECTION:
example.com.		86400	IN	SOA	ns1.example.com. ahu.example.com. 2847484148 28800 7200 604800 86400
example.com.		86400	IN	RRSIG	SOA 13 2 100000 20200319000000 20200227000000 14848 example.com. PKGnKtz7VgV5519dTbNjVpcyB50JWAUm5LdfbKFXYuYf1JVBfWy0zdG2 IgCGAaTNMS5K5HxAnL4gcBFEpy6aWQ==
example.com.		86400	IN	NSEC	_imap._tcp.example.com. NS SOA MX RRSIG NSEC DNSKEY
example.com.		86400	IN	RRSIG	NSEC 13 2 86400 20200319000000 20200227000000 14848 example.com. 4k+5YYb7P1FkC872oQgpvrn6U96orS31Rpk6wgxkGJtviCdDnngpdwg7 2sjZnAuEluDdS5XXdrqSK+jSJMz8qA==

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Wed Mar 11 13:40:32 CET 2020
;; MSG SIZE  rcvd: 343
```
This issue is also present in the axfr output

### Other information
It is unlikely this will result in operational issues since the zone is technically not signed when this is happening.

### PR DESCRIPTION
**Pull request by RobinGeuze**
### Short description
Fixes #8921 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by RobinGeuze** [comment]
Funnily AXFR was already correct for this case since it actually checks what types exist rather than just blindly adding types.

**Comment by mnordhoff** [comment]
Does the issue also apply to `CDNSKEY` and `CDS`?

**Comment by RobinGeuze** [comment]
No, the code there already ignores the DNSKEY if it is unpublished. The NSECx records were an oversight.

**Comment by mnordhoff** [comment]
I meant, it also affects the `NSEC`/`NSEC3` bitmap for `CDNSKEY` and `CDS`. (It was a question before because I didn't check it until just now.)

```
$ dig +dnssec +norecurse @ns10.mattnordhoffdns.org unpublished.mattnordhoffdns.work cds

; <<>> DiG 9.16.0 <<>> +dnssec +norecurse @pdns0 unpublished.mattnordhoffdns.work cds
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16883
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;unpublished.mattnordhoffdns.work. IN   CDS

;; AUTHORITY SECTION:
unpublished.mattnordhoffdns.work. 3600 IN SOA   pdns0.mattnordhoff.net. rname.mn0.us. 2020031300 1800 900 2678400 3600
unpublished.mattnordhoffdns.work. 3600 IN RRSIG SOA 13 3 3600 20200326000000 20200305000000 4819 unpublished.mattnordhoffdns.work. n6kmQDRVQoJgbMlcuplTY8e36V+Rsk+jy6dwZK8f6qD3Xc1rC+Ph7c3O ZN6LZYeq/Sf9va9FkKFaBc5YuYb4Aw==
unpublished.mattnordhoffdns.work. 3600 IN NSEC  unpublished.mattnordhoffdns.work. NS SOA RRSIG NSEC DNSKEY CDS CDNSKEY
unpublished.mattnordhoffdns.work. 3600 IN RRSIG NSEC 13 3 3600 20200326000000 20200305000000 4819 unpublished.mattnordhoffdns.work. x4gXOrJsueBGN1PuDRiAMl1KaJSSGabKqgOaNF2DINuu9Qm4WXw7q7ZV Gi44kZ2cGT51lGikMi84PoKSM8dANg==

;; Query time: 0 msec
;; SERVER: 2600:3c00::2:b422#53(2600:3c00::2:b422)
;; WHEN: Fri Mar 13 23:01:56 UTC 2020
;; MSG SIZE  rcvd: 443
```

**Comment by RobinGeuze** [comment]
Ah, right, I will amend the MR tomorrow.

**Comment by RobinGeuze** [comment]
Done, CDS and CDNSKEY case should be correct as well now.

**Pull request merged**
