### PR TITLE
Rename QType.getName() to QType.toString()

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Creating a PR to double check compilcation with CI.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
```
ldapbackend.cc:207:63: error: expected ')'
            if (qtype2 != QType(local_result.qtype).toString()continue;
                                                              ^
ldapbackend.cc:207:16: note: to match this '('
            if (qtype2 != QType(local_result.qtype).toString()continue;
               ^
ldapbackend.cc:207:71: warning: if statement has empty body [-Wempty-body]
            if (qtype2 != QType(local_result.qtype).toString()continue;
                                                                      ^
ldapbackend.cc:207:71: note: put the semicolon on a separate line to silence this warning
ldapbackend.cc:216:62: error: expected ')'
            if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
                                                             ^
ldapbackend.cc:216:16: note: to match this '('
            if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
               ^
ldapbackend.cc:216:87: warning: if statement has empty body [-Wempty-body]
            if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
                                                                                      ^
ldapbackend.cc:216:87: note: put the semicolon on a separate line to silence this warning
2 warnings and 2 errors generated.
make[3]: *** [Makefile:649: ldapbackend.lo] Error 1
```

**Comment by Habbie** [comment]
```
ixfrdist.cc:472:81: error: no member named 'getName' in 'QType'
  g_log<<Logger::Debug<<logPrefix<<"Had "<<mdp.d_qname<<"|"<<QType(mdp.d_qtype).getName()<<" query from "<<saddr.toStringWithPort()<<endl;
                                                             ~~~~~~~~~~~~~~~~~~ ^
ixfrdist.cc:475:70: error: no member named 'getName' in 'QType'
    info_msg.push_back("QType is unsupported (" + QType(mdp.d_qtype).getName() + " is not in {SOA,IXFR})");
                                                  ~~~~~~~~~~~~~~~~~~ ^
ixfrdist.cc:479:70: error: no member named 'getName' in 'QType'
    info_msg.push_back("QType is unsupported (" + QType(mdp.d_qtype).getName() + " is not in {SOA,IXFR,AXFR})");
                                                  ~~~~~~~~~~~~~~~~~~ ^
ixfrdist.cc:495:90: error: no member named 'getName' in 'QType'
    g_log<<Logger::Warning<<logPrefix<<"Refusing "<<mdp.d_qname<<"|"<<QType(mdp.d_qtype).getName()<<" query from "<<saddr.toStringWithPort();
                                                                      ~~~~~~~~~~~~~~~~~~ ^
ixfrdist.cc:817:95: error: no member named 'getName' in 'QType'
    g_log<<Logger::Warning<<"Could not send reply for "<<mdp.d_qname<<"|"<<QType(mdp.d_qtype).getName()<<" to "<<saddr.toStringWithPort()<<": "<<strerror(savedErrno)<<endl;
                                                                           ~~~~~~~~~~~~~~~~~~ ^
5 errors generated.
make[3]: *** [Makefile:3314: ixfrdist.o] Error 1
  CXX      zone2ldap.o
zone2ldap.cc:323:97: error: no member named 'getName' in 'QType'
                                                        callback(g_domainid, rr.qname, rr.qtype.getName(), encode_non_ascii(rr.content), rr.ttl);
                                                                                       ~~~~~~~~ ^
zone2ldap.cc:352:73: error: no member named 'getName' in 'QType'
                                callback(g_domainid, rr.qname, rr.qtype.getName(), encode_non_ascii(rr.content), rr.ttl);
                                                               ~~~~~~~~ ^
2 errors generated.
make[3]: *** [Makefile:3314: zone2ldap.o] Error 1
```

**Comment by omoerbeek** [comment]
> ```
> ldapbackend.cc:207:63: error: expected ')'
>             if (qtype2 != QType(local_result.qtype).toString()continue;
>                                                               ^
> ldapbackend.cc:207:16: note: to match this '('
>             if (qtype2 != QType(local_result.qtype).toString()continue;
>                ^
> ldapbackend.cc:207:71: warning: if statement has empty body [-Wempty-body]
>             if (qtype2 != QType(local_result.qtype).toString()continue;
>                                                                       ^
> ldapbackend.cc:207:71: note: put the semicolon on a separate line to silence this warning
> ldapbackend.cc:216:62: error: expected ')'
>             if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
>                                                              ^
> ldapbackend.cc:216:16: note: to match this '('
>             if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
>                ^
> ldapbackend.cc:216:87: warning: if statement has empty body [-Wempty-body]
>             if (rdata == QType(local_result.qtype).toString()local_result.auth = false;
>                                                                                       ^
> ldapbackend.cc:216:87: note: put the semicolon on a separate line to silence this warning
> 2 warnings and 2 errors generated.
> make[3]: *** [Makefile:649: ldapbackend.lo] Error 1
> ```

This was a botched search & replace, dunno how i did that

**Comment by omoerbeek** [comment]
Rebased to fix conflict.

**Comment by omoerbeek** [comment]
BTW, I have a branch here to fix #7389 (logging QType and QClass), but it is dependent on this branch

**Comment by zeha** [comment]
Does this want to land in auth 4.5.0 to avoid later backporting pain?

**Review by mind04 — APPROVED** [review]

**Review by Habbie — CHANGES_REQUESTED** [review]
Content is approved, but this needs to be squashed, so bisects cannot hit that broken commit.

**Comment by omoerbeek** [comment]
Squased

**Review by Habbie — APPROVED** [review]

**Pull request merged**
