### PR TITLE
Stop using incbin and use od & sed to generate constant string data

### LINKED ISSUE #9835: auth does not run with asan
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==20439==ERROR: AddressSanitizer: SEGV on unknown address 0x562cae3d24e0 (pc 0x7fde13afa6a7 bp 0x7ffc30ff9860 sp 0x7ffc30ff95a8 T0)
==20439==The signal is caused by a WRITE memory access.
    #0 0x7fde13afa6a6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1206a6)
    #1 0x562cade59f04 in __static_initialization_and_destruction_0 /home/peter/projects/powerdns/pdns/pdns/apidocfiles.h:4
    #2 0x562cade5a0b6 in _GLOBAL__sub_I__ZN13AuthWebServerC2Ev /home/peter/projects/powerdns/pdns/pdns/ws-auth.cc:2333
    #3 0x562cae28a244 in __libc_csu_init (/home/peter/projects/powerdns/pdns/pdns/pdns_server+0x173e244)
    #4 0x7fde1367d029 in __libc_start_main ../csu/libc-start.c:264
    #5 0x562cad485689 in _start (/home/peter/projects/powerdns/pdns/pdns/pdns_server+0x939689)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1206a6) in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&)
==20439==ABORTING
```

This was introduced in #8911. When this is fixed, we should try enabling asan (and ubsan) in CircleCI for auth.

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Fixes #9835

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
TODO: make it robust against embbedded NULs and remove incbin remains in ws-wauth.cc

**Comment by Habbie** [comment]
I expected:
```
swagger: '2.0'
info:
  version: "0.0.13"
  title: PowerDNS Authoritative HTTP API
  license:
    name: MIT
```

I got:
```
gaws:reg.2' i
'0:ofnv  
isre :no0.0""31.t  
eltioP :DrewA SNohtuatirevitTTH PA P  
Iecil:esn   
man M :eb
TIPesa:htapa/ 1v/inoc
```

**Comment by Habbie** [comment]
Yes! I was just testing `x1` myself. That works. :)

**Review by Habbie — APPROVED** [review]

**Comment by omoerbeek** [comment]
Aslo did rec and dnsdist, fixing a bug in rec while there: the handler code potentially modifies the map.

**Comment by omoerbeek** [comment]
> Yes! I was just testing `x1` myself. That works. :)

yes, alternatively get a machine with proper endianess. ;-)

**Comment by Habbie** [comment]
> yes, alternatively get a machine with proper endianess. ;-)

Yes, I figured that's how you cheated :D

**Comment by Habbie** [comment]
'Test package building for specific distributions / centos-6 (dnsdist)' failure is unrelated and can be ignored.

**Comment by Habbie** [comment]
@rgacogne any objections?

**Review by rgacogne — APPROVED** [review]
Looks good to me! It would be nice to remove the ext/inbcin/ directories and their content but that can be done later.

**Pull request merged**
