### PR TITLE
rec: Enable SNMP for debian and ubuntu builds.

### LINKED ISSUE #11999: rec: enable snmp on debian/ubuntu builds

### PR DESCRIPTION
**Pull request by omoerbeek**
Fixes #11999

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
Tested this by doing a build for all debian derived versions currently supported. All show `configure: SNMP: yes` for the actual build part. The `sdist` part shows `configure: SNMP: no` but I do not think that matters.

**Comment by Habbie** [comment]
> The `sdist` part shows `configure: SNMP: no` but I do not think that matters.

Indeed, it does not (or, that is to say, it should not - we've had bugs in the past, but if the package builds are happy, all is good).

**Comment by omoerbeek** [comment]
Mopped the test commit up and force pushed

**Comment by omoerbeek** [comment]
While builds went ok, we should be very careful, on some targets `libsnmp-dev` adds extra flags we do not want

**Comment by omoerbeek** [comment]
So pre-jammy version of ubuntu do not have a pkgconfig for netsnmp. This works and avoids the introduction of extra compiler flags:
```
NET_SNMP_LIBS="-lnetsnmpmibs -lnetsnmpagent -lnetsnmp" ./configure ...

But I do not know yet how to get that into the build in a proper way.

**Comment by Habbie** [comment]
This looks like it might break if the headers live in a weird path. Then again, meanwhile this improves compilation on every other platform (which is more common). I suggest merging this, and, if necessary, finding this comment later so we can say "see, we told ourselves so!"

**Review by Habbie — APPROVED** [review]

**Pull request merged**
