### PR TITLE
pdnsutil: complain about missing quotes around TXT record data

### PR DESCRIPTION
**Pull request by zeha**
Need this to match API behaviour.

Found by @stbuehler.

### CODE REVIEW

**Comment by mind04** [comment]
Can you explain why this need to go?
This code is here to detect duplicate TXT records where the presence of quotes is the only difference. Duplicates like this result in bogus signatures.

In slave zones all TXT records are quoted, so i guess the quoted version the preferred format. Maybe the api should follow this behaviour?

**Comment by zeha** [comment]
I don't see how this helps with duplicates?

Anyway, when our preferred format is with quotes, we should warn about missing quotes.

**Comment by zeha** [comment]
Ok, figured out the duplicate thing.

Changed this to write a dedicated warning and keep the automatic quote addition.

Output is now:
```
[Warning] TXT record is missing quotes around content: fred.example.org. IN TXT asdf
[Error] Duplicate record found in rrset: 'fred.example.org. IN TXT "asdf"'
Checked 10 records of 'example.org.', 1 errors, 1 warnings.
```

**Comment by zeha** [comment]
Turned this into an error now, as this breaks API usage.

**Comment by mind04** [comment]
Documentation for TXT says "PowerDNS understands content not enclosed in quotes.". If you turn this in an error this also need an update. But I think is best if the API can deal with quoted and unquoted versions of TXT records. Or maybe, add missing quotes in read operations and require them for insert/update ones?

**Comment by zeha** [comment]
I don't want any (extra) hacks in the API for record types. Core should just get it right.

If gsql wants to store TXT records without quotes, it should add the quotes during read, and remove during write. Or getZoneRepresentation should be fixed, and then everybody uses no-quotes.

**Comment by zeha** [comment]
Actually I'm a bit at a loss on what to do with all of this. I had hoped getZoneRepresentation would be something that gives the correct output for the output and input side (depending on parameters), but this isn't really true (as seen here with quotes). I guess there are other cases where this is not true.

In the API I really need these:
1. convert from canonical format (api thinks of this mostly as bind zone file format, so, dots, quotes, etc.) to backend format
2. convert from backend format to canonical format

What makes this harder is that, IIRC, bindbackend gives dots and stuff, where gsql doesn't.

Any help/insight appreciated.

**Comment by zeha** [comment]
Had a discussion with @pieterlexis and @rgacogne, summary:

- (gsql)backend should just deal with quoting if needed
- core should assume everything's quoted (and reject unquoted)

Let's hope this is actually viable.

**Comment by stbuehler** [comment]
@zeha wrote in https://github.com/PowerDNS/pdns/pull/3150#issuecomment-269679309:
> - (gsql)backend should just deal with quoting if needed
> - core should assume everything's quoted (and reject unquoted)

Maybe someone can clean up all the duplicates of this issue and link them all to a new issue with this todo list?

**Comment by zeha** [comment]
> Maybe someone can clean up all the duplicates of this issue and link them all to a new issue with this todo list?

So, for reference, the underlying TXT issue according to @mind04 is #3503.
This needs fixing first, and then we can see if/what else needs to be done.

**Pull request closed without merging**
