### PR TITLE
dnsdist: do not allocate 16-byte aligned objects through lua(jit)

### LINKED ISSUE #13766: dnsdist: init of ServerPolicies crashes on FreeBSD stable/14
Originally reported by jostreff

```
* thread #1, name = 'dnsdist', stop reason = signal SIGBUS: object-specific hardware error
    frame #0: 0x000035570a927bc5 dnsdist`ServerPolicy::ServerPolicy(ServerPolicy const&) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(this="", __str="roundrobin") at string:899:20
   896 	  _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(const basic_string& __str)
   897 	      : __r_(__default_init_tag(), __alloc_traits::select_on_container_copy_construction(__str.__alloc())) {
   898 	    if (!__str.__is_long())
-> 899 	      __r_.first() = __str.__r_.first();
   900 	    else
   901 	      __init_copy_ctor_external(std::__to_address(__str.__get_long_pointer()), __str.__get_long_size());
   902 	  }
```
The backtrace looks like this (using `lldb`):
```
* thread #1, name = 'dnsdist', stop reason = signal SIGBUS: object-specific hardware error
  * frame #0: 0x000035570a927bc5 dnsdist`ServerPolicy::ServerPolicy(ServerPolicy const&) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(this="", __str="roundrobin") at string:899:20
    frame #1: 0x000035570a927bb4 dnsdist`ServerPolicy::ServerPolicy(this=0x00000000000824f8, (null)=0x0000355f2b9711a0) at dnsdist-lbpolicies.hh:32:7
    frame #2: 0x000035570a9279ce dnsdist`LuaContext::PushedObject LuaContext::Pusher<ServerPolicy, void>::push<ServerPolicy&>(state=0x0000000000076378, value=0x0000355f2b9711a0) at LuaContext.hpp:1647:37
    frame #3: 0x000035570a9278c0 dnsdist`void LuaContext::setTable<ServerPolicy, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, ServerPolicy&>(state=0x0000000000076378, (null)=Globals, index="roundrobin", data=0x0000355f2b9711a0) at LuaContext.hpp:1010:23
    frame #4: 0x000035570a882fd7 dnsdist`setupLuaBindings(LuaContext&, bool, bool) [inlined] void LuaContext::writeVariable<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, ServerPolicy&>(this=<unavailable>, data=<unavailable>, data=<unavailable>) at LuaContext.hpp:737:9
    frame #5: 0x000035570a882faf dnsdist`setupLuaBindings(luaCtx=<unavailable>, client=<unavailable>, configCheck=<unavailable>) at dnsdist-lua-bindings.cc:90:12
    frame #6: 0x000035570aa79c13 dnsdist`setupLua(luaCtx=0x000035570abe8a28, client=<unavailable>, configCheck=false, config="/usr/local/etc/dnsdist.conf") at dnsdist-lua.cc:3399:3
    frame #7: 0x000035570ab7bcc5 dnsdist`main(argc=1, argv=0x0000355f2b971e40) at dnsdist.cc:3272:17
    frame #8: 0x0000355f31eb15ca libc.so.7`__libc_start1(argc=1, argv=0x0000355f2b971e40, env=0x0000355f2b971e50, cleanup=<unavailable>, mainX=(dnsdist`main at dnsdist.cc:3181)) at libc_start1.c:157:7
    frame #9: 0x000035570a664cfd dnsdist`_start at crt1_s.S:83
```

It might be related to the use of _placement new_. During the call of the copy ct, it looks like the string library code assumes `this` is already initialized, which it isn't. When I have the opportunity, I'll try to isolate this into a smaller test.

Not using the full `ServerPolicy` object but a using a const pointer to it works around the issue, in the sense that `dnsdist` no longer crashes.

```
diff --git a/pdns/dnsdist-lua-bindings.cc b/pdns/dnsdist-lua-bindings.cc
index 69638e23e..16121b05d 100644
--- a/pdns/dnsdist-lua-bindings.cc
+++ b/pdns/dnsdist-lua-bindings.cc
@@ -78,7 +78,7 @@ void setupLuaBindings(LuaContext& luaCtx, bool client, bool configCheck)
   luaCtx.registerFunction("toString", &ServerPolicy::toString);
   luaCtx.registerFunction("__tostring", &ServerPolicy::toString);
 
-  ServerPolicy policies[] = {
+  static const ServerPolicy policies[] = {
     ServerPolicy{"firstAvailable", firstAvailable, false},
     ServerPolicy{"roundrobin", roundrobin, false},
     ServerPolicy{"wrandom", wrandom, false},
@@ -86,8 +86,8 @@ void setupLuaBindings(LuaContext& luaCtx, bool client, bool configCheck)
     ServerPolicy{"chashed", chashed, false},
     ServerPolicy{"leastOutstanding", leastOutstanding, false}
   };
-  for (auto& policy : policies) {
-    luaCtx.writeVariable(policy.d_name, policy);
+  for (const auto& policy : policies) {
+    luaCtx.writeVariable(policy.d_name, &policy);
   }
 
 #endif /* DISABLE_POLICIES_BINDINGS */
```

But I have little idea if that affects Lua code in the wild.
Update: not using a `const` pointer (removing the two instances of `const` in the diff) gets me modifiable standard `ServerPolicies` again. Though I would not know why you would want to change those.

So far I did not succeed to reproduce in a smaller program.

### PR DESCRIPTION
**Pull request by omoerbeek**
luajit aligns only to 8 bytes by default, and some objects require 16 byte alignment.

Fixes #13766

Note that one `static_assert` in LuaContext.hpp is commented.  This trips on c++lib 17, but does not seem to be harmful right now as the code works.

The fundamental solution remains to have luajit agree with C++ on minimal alignment of its allocators.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
> Fatal Lua error: [string "chunk"]:3: Unable to convert parameter from userdata to 12ServerPolicy\nstack traceback:\n\t[C]: in function \'setServerPolicy\'\n\t[string "chunk"]:3: in main chunk\n

Crap

**Comment by jostreff** [comment]
> > Fatal Lua error: [string "chunk"]:3: Unable to convert parameter from userdata to 12ServerPolicy\nstack traceback:\n\t[C]: in function 'setServerPolicy'\n\t[string "chunk"]:3: in main chunk\n
> 
> Crap

Yep, i have found same result when I manually patched source yesterday...

**Comment by omoerbeek** [comment]
dnsdist regression test is happy with my experiment...

**Comment by rgacogne** [comment]
It would be good to also test:
- setPoolServerPolicy
- and that we can set these to the result of `newServerPolicy`
I can do that tomorrow.

**Comment by omoerbeek** [comment]
Adding regression tests is always good.

**Comment by rgacogne** [comment]
I added test, fixing the use of `newServerPolicy` and `setPoolServerPolicy` in the process. It turns out `newServerPolicy` has been broken for a while, perhaps it never worked..

**Review by rgacogne — APPROVED** [review]

**Comment by rgacogne** [comment]
Failing tests are caused by the broken zone used by the recursor's regression tests.

**Comment by rgacogne** [comment]
Otto, do you want to have a look before we merge this?

**Comment by omoerbeek** [comment]
No I'm happy, go ahead.

**Pull request merged**
