### PR TITLE
Docs 4 x Documentation Improvisation 

### PR DESCRIPTION
**Pull request by mail3dexter**
This is my first PR ever hence please disregard my mistakes.
This PR is not about code however is about documentation.
I have seen that [Pipe backend document](https://doc.powerdns.com/md/authoritative/backend-pipe/) mentions about ABI however there's no where it is written what ABI means.

Normally it means that it is an interface between 2 binary programs however in this case it is actually (literally) not.

Hence I would like to suggest that we document what ABI means to clearify things.
Suggestions on ABI acronym:
Application Backend Interface
Actual Backend Interface
Available Backend Interface
Authorative Backend Interface

Let us come to an agreemenet and document this.

### CODE REVIEW

**Comment by pieterlexis** [comment]
Thanks for this, docs-4x is for the 4.0 docs, please set the branch you want to merge into to `master` :)

**Comment by mail3dexter** [comment]
You want me to merge rel/auth-4.1.x into master after editing docs?

**Comment by pieterlexis** [comment]
> You want me to merge rel/auth-4.1.x into master after editing docs?

I want you to set the base branch for this PR to master, the docs in master are for 4.1 as well.

**Comment by Habbie** [comment]
This PR appears to contain a lot of unrelated changes..

**Comment by Habbie** [comment]
This PR contains no relevant changes, so I'm closing it.

**Pull request closed without merging**
