### PR TITLE
recursor: add 38696 root anchor

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
fetched from https://www.iana.org/dnssec/files after their 2024-07-24 update.

If you take just the first commit, you get a nice crash.  I did not squash because you might want to see if that crash could also happen to users.

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
About the crashing first commit: the code generated is:
```
// DEFAULT HANDLING for dnssec_trustanchors
fn default_value_dnssec_trustanchors() -> Vec<recsettings::TrustAnchor> {
    let deserialized: Vec<recsettings::TrustAnchor> = serde_yaml::from_str("[{name: ., dsrecords: ['20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d'], ['38696 8 2 683d2d0acb8c9b712a1948b27f741219298d0a450d612c483af444a4c0fb2b16']}]").unwrap();
    deserialized
}
```
And the error message is:
```
thread '<unnamed>' panicked at src/lib.rs:2394:262:
called `Result::unwrap()` on an `Err` value: Error(".[0]: invalid type: sequence, expected field identifier", line: 1, column: 103)
```
So the code assumes the default defined in `table.py` is valid yaml, while it is not. I think it is acceptable to crash in this case. OTOH a nice message would be more gentle. I'll play a bit.

**Comment by omoerbeek** [comment]
This looks good to me. i.e. it can be moved to "Ready for review".

**Comment by Habbie** [comment]
> moved to "Ready for review".

done, and squashed all commits

**Comment by omoerbeek** [comment]
I'm merging this into master now. Backports should be done so the next release of the stable branches have it.

**Comment by omoerbeek** [comment]
Rebased to run tests against master in CI

**Pull request merged**
