### PR TITLE
el-8: use gcc-toolset-13

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
needs build tests (auth did pass locally)

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
build tests for all 3 products (× all 3 EL because I touched that `if` that chooses toolsets):

* auth https://github.com/Habbie/pdns/actions/runs/11035245574
* rec https://github.com/Habbie/pdns/actions/runs/11035261783
* dnsdist https://github.com/Habbie/pdns/actions/runs/11035270773

**Comment by Habbie** [comment]
@rgacogne suggests that if this works, we should see if we can bump our baseline to C++20.

Also, I need to get rid of the el7-toolset check (in misc-dailies), add an el8 one, and see if el9 has (interesting) toolsets. Then depending on how the C++20 experiment goes, see if oldest ubuntu has a newer compiler available, etc.

**Comment by omoerbeek** [comment]
I have a branch to switch to c++20, saw only one thing break (easy fix), but a few warning here and there.

**Comment by omoerbeek** [comment]
For c++20, Boost needs at least 1.74, to fix a allocator use in `boost::format` that was dropped in c++20.

If this is merged and we switch to c++20, we need to also fix docs, configure and meson.build to mention the correct minimal boost version.

**Comment by Habbie** [comment]
New build tests

* [auth](https://github.com/Habbie/pdns/actions/runs/11234531812)
* [recursor](https://github.com/Habbie/pdns/actions/runs/11234542890)
* [dnsdist](https://github.com/Habbie/pdns/actions/runs/11234551355)

**Comment by Habbie** [comment]
auth build runs fine. Ready for review.

**Review by rgacogne — APPROVED** [review]

**Pull request merged**
