### PR TITLE
[feature] remove support for libdecaf

### PR DESCRIPTION
**Pull request by miodvallat**
### Short description

As suggested in #12953, there is need to support libdecaf any longer.

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code (quickly)
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
Recursor build failure due to missed auto* case: https://github.com/PowerDNS/pdns/actions/runs/12156498965/job/33900317485?pr=14926

**Comment by miodvallat** [comment]
I suppose I need to keep an empty `m4/pdns_with_libdecaf.m4` for `autoreconf` to operate correctly.

**Comment by omoerbeek** [comment]
Hmm, that should not be needed, I'll take a look why autoconf wants that file later today.

**Comment by miodvallat** [comment]
I agree that this shouldn't be needed, but if keeping a mostly empty file helps, then it doesn't hurt to carry that empty file for a while.

**Comment by omoerbeek** [comment]
> I agree that this shouldn't be needed, but if keeping a mostly empty file helps, then it doesn't hurt to carry that empty file for a while.

Sure, if I don't find the solution quickly, an empty file it is.

**Comment by omoerbeek** [comment]
Of course the issue doesn't reproduce locally. I avoid gaining too much auto* knowledge, so the proposed workaround it is.

**Comment by miodvallat** [comment]
> I avoid gaining too much auto* knowledge, so the proposed workaround it is.

Of course! You can't have both auto* knowledge and otto* knowledge.

**Review by omoerbeek — APPROVED** [review]

**Comment by Habbie** [comment]
> Recursor build failure due to missed auto* case: https://github.com/PowerDNS/pdns/actions/runs/12156498965/job/33900317485?pr=14926

this is -so weird-

**Comment by omoerbeek** [comment]
> > Recursor build failure due to missed auto* case: https://github.com/PowerDNS/pdns/actions/runs/12156498965/job/33900317485?pr=14926
> 
> this is -so weird-

caching is indeed hard... does the weirdness prevent merging?

**Comment by Habbie** [comment]
(no caching was involved at all)

**Comment by miodvallat** [comment]
Ah, I missed it due it being a symbolic link. Good catch!

**Comment by miodvallat** [comment]
> (no caching was involved at all)

It was DNS.

**Comment by omoerbeek** [comment]
I suspect I did my test with the workaround already in and didn't pay attention.

**Review by Habbie — APPROVED** [review]

**Pull request merged**
