### PR TITLE
Move internal QTypes to the private range

### LINKED ISSUE #2924: Stop using unassigned qtype numbers that may get assigned in the future
`ADDR=259, ALIAS=260,` in qtype.hh will bite us the moment those become IANA assigned, as has already happened with 256 (URI) and 257 (CAA) which 3.4.* cannot even support as a slave. We should move them into private space or outside of the 16 bit rrtype space.

### PR DESCRIPTION
**Pull request by pieterlexis**
Closes #2924

### CODE REVIEW

**Comment by Habbie** [comment]
Did you do any research in what private numbers are actively being used in other implementations?

**Comment by pieterlexis** [comment]
There is no mention of those number in the following sources:

* bind-9.10.3
* knot-1.6.6
* knot-2.0.2
* nsd-4.1.6

**Comment by Habbie** [comment]
:+1:

**Comment by Habbie** [comment]
LGTM

**Pull request merged**
