### PR TITLE
auth: Refuse queries for QType values of zero or OPT

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Follow-up of https://github.com/PowerDNS/pdns/pull/9290 for the authoritative server.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mnordhoff** [comment]
FWIW, I'd vote against this, unless there's a specific need for it. NODATA and NXDOMAIN are cacheable. If resolvers ask silly questions, I'd rather give them something that they can cache, so they'll go away instead of retrying.

**Comment by rgacogne** [comment]
That's a very good point, I'll wait for more feedback but I believe you might be right!

**Comment by mnordhoff** [comment]
Also FWIW, Knot DNS returns NOTIMP for type 0 and treats OPT queries normally.

**Comment by zeha** [comment]
> Also FWIW, Knot DNS returns NOTIMP for type 0 and treats OPT queries normally.

What does "normally" mean here?

**Comment by zeha** [comment]
It might be worthwhile changing the qclass not in (IN, ANY) branch above to whatever will be done for this case, too.

**Comment by zeha** [comment]
FORMERR appears to be a popular choice for OPT queries among other Auth servers.

**Comment by Habbie** [comment]
> FWIW, I'd vote against this, unless there's a specific need for it. NODATA and NXDOMAIN are cacheable. If resolvers ask silly questions, I'd rather give them something that they can cache, so they'll go away instead of retrying.

This makes sense to me.

**Comment by rgacogne** [comment]
Closing this PR, then! Thanks for the feedback :-)

**Pull request closed without merging**
