### PR TITLE
auth: prevent bind-hybrid+zone-cache

### LINKED ISSUE #10658: bind-hybrid mode doesn't play together with the zone cache
- Program: Authoritative
 - Issue type: Bug report

### Short description
PowerDNS doesn't serve bind zones in `bind-hybrid` mode when the zone cache is enabled (as is the default now)

### Environment

 - Operating system: Ubuntu Linux 20.04
 - Software version: 4.5.1-1pdns.focal
 - Software source: PowerDNS repository

### Steps to reproduce
see https://mailman.powerdns.com/pipermail/pdns-users/2021-August/027371.html

### Expected behaviour
PowerDNS is able to server bind zones in `bind-hybrid` mode when the zone cache is enabled

### Actual behaviour
PowerDNS responds with `REFUSED` for queries for bind zones when bind-hybrid mode and the zone cache are enabled.

### Other information
see https://mailman.powerdns.com/pipermail/pdns-users/2021-August/027371.html and https://mailman.powerdns.com/pipermail/pdns-users/2021-August/027356.html

possible workaround could be to use `bind-dnssec-db` instead of `bind-hybrid` mode

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
fixes #10658

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
I broke pdnsutil.

**Comment by Habbie** [comment]
I fixed pdnsutil.

**Comment by zeha** [comment]
I assume g_zoneCache.isEnabled doesn't work, also because of pdnsutil?

**Comment by Habbie** [comment]
> I assume g_zoneCache.isEnabled doesn't work, also because of pdnsutil?

It does. I amended the commit, much cleaner now, thanks!

**Review by zeha — APPROVED** [review]
Note: pdns_server quits as expected (`Fatal error: bind-hybrid and the zone cache currently interoperate badly. Please disable the zone cache or stop using bind-hybrid`), but pdnsutil does not. I guess thats fine, but please be aware of it.

**Comment by Habbie** [comment]
> but pdnsutil does not. I guess thats fine, but please be aware of it.

I was aware, thanks!

**Pull request merged**
