### PR TITLE
There is no bindbackend 1 anymore

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by mind04** [comment]
please no, this will clear history for these files.

**Comment by rubenk** [comment]
No it won't, git tracks the history of renamed files.

**Comment by mind04** [comment]
It does https://github.com/PowerDNS/pdns/commits/master/docs/make-thanks

**Comment by rubenk** [comment]
Github doesn't follow history, but git does. Try git log --follow on a file.

**Comment by Habbie** [comment]
While all technically correct, this makes using git a bit harder. Not a big fan.

**Comment by rubenk** [comment]
Understood :)

**Pull request closed without merging**
