### PR TITLE
enable code scanning

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
This should enable GitHub Code Scanning on all branches, all PRs, plus periodically.

This needs #9583 merged first.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
Right now this builds our code.. six times. Also for Python and JS scanning. Probably don't want the language matrix at all.

**Comment by zeha** [comment]
Might be good to keep the larger check set - I'm hoping in a PR it would only show new alerts?

**Comment by Habbie** [comment]
> Might be good to keep the larger check set

The options as I see them:

1. start small, clean out the large set, then go large
2. go large now and triage them all before we start scanning PRs
3. go large, accept that the list is big, clean up at some point

Having written it out like that, perhaps 3 is reasonable after all.

> I'm hoping in a PR it would only show new alerts?

I also assume so!

**Comment by Habbie** [comment]
> Having written it out like that, perhaps 3 is reasonable after all.

I have decided I like 3. We'll find out how noisy it is on PRs.

**Comment by Habbie** [comment]
#9583 was merged so I rebased this.

**Pull request merged**
