### PR TITLE
GH Actions - Meson: Build auth using meson in `build-and-test-all`.

### PR DESCRIPTION
**Pull request by romeroalx**
### Short description
Initial work as part of the tasks included in #13987 for building `auth` using Meson inside the `build-and-test-all` workflow.

Output binaries from the meson build are not installed but only generated (current `ci-make-install step`).

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by fredmorcos** [comment]
I had a short call with @romeroalx and we discussed moving more logic into `tasks.py` in a way that completely abstract build system internals from the user and from Github workflows.

**Review by fredmorcos — APPROVED** [review]
Awesome! This is fine by me to get merged for now.
Once we merge the `--enable-systemd` flag for meson you can fix that TODO and merge this PR.

One thing that irks me (but we shouldn't do anything about it just yet) is the use of environment variables. I think in the long term we want to move to being very explicit about everything we pass, so using invoke parameters would be better, and we can get rid of weird stuff like `echo SANITIZERS=... >> $GITHUB_ENV`.

**Comment by fredmorcos** [comment]
The systemd configure flag is added here: #14055

**Comment by fredmorcos** [comment]
> The systemd configure flag is added here: #14055

That was merged. So this PR can now be merged after the systemd configure flag is enabled on meson.

**Comment by Habbie** [comment]
This branch has conflicts that must be resolved

**Pull request merged**
