### PR TITLE
Enable Crypto++ in Travis

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by rubenk** [comment]
failure is #2068

**Comment by zeha** [comment]
Travis didn't like this with clang++ (but gcc built):

```
clang++ -DHAVE_CONFIG_H -I. -I..  -I.. -I.. -pthread  -I../pdns/ext/rapidjson/include -I../pdns/ext/yahttp -I../pdns/ext/polarssl/include/   -I/usr/include/p11-kit-1    -I/usr/include/lua5.1    -DSYSCONFDIR=\"/usr/local/etc\" -DPKGLIBDIR=\"/usr/local/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -g -O2 -c -o version.o version.cc
In file included from cryptoppsigners.cc:1:
In file included from /usr/include/cryptopp/osrng.h:10:
In file included from /usr/include/cryptopp/randpool.h:5:
In file included from /usr/include/cryptopp/filters.h:7:
/usr/include/cryptopp/secblock.h:91:3: error: use of undeclared identifier
      'CheckSize'
                CheckSize(n);
                ^
/usr/include/cryptopp/secblock.h:247:35: note: in instantiation of member
      function 'CryptoPP::AllocatorWithCleanup<unsigned char, false>::allocate'
      requested here
                : m_size(size) {m_ptr = m_alloc.allocate(size, NULL);}
                                                ^
/usr/include/cryptopp/algparam.h:16:2: note: in instantiation of member function
      'CryptoPP::SecBlock<unsigned char, CryptoPP::AllocatorWithCleanup<byte>
      >::SecBlock' requested here
        ConstByteArrayParameter(const char *data = NULL, bool deepCopy = false)
        ^
/usr/include/cryptopp/secblock.h:37:14: note: must qualify identifier to find
      this declaration in dependent base class
        static void CheckSize(size_t n)
                    ^
In file included from cryptoppsigners.cc:5:
/usr/include/cryptopp/eccrypto.h:169:4: error: use of undeclared identifier
      'GenerateRandom'
                {GenerateRandom(rng, params);}
                 ^
cryptoppsigners.cc:49:15: note: in instantiation of member function
      'CryptoPP::DL_PrivateKey_EC<CryptoPP::ECP>::Initialize' requested here
  privateKey->Initialize( prng, oid);
              ^
cryptoppsigners.cc:32:16: note: in instantiation of member function
      'CryptoPPECDSADNSCryptoKeyEngine<CryptoPP::SHA256,
      <anonymous>::WrapperSECP256R1, 256>::create' requested here
    return new CryptoPPECDSADNSCryptoKeyEngine(algorithm);
               ^
cryptoppsigners.cc:190:101: note: in instantiation of member function
      'CryptoPPECDSADNSCryptoKeyEngine<CryptoPP::SHA256,
      <anonymous>::WrapperSECP256R1, 256>::maker' requested here
  ...&CryptoPPECDSADNSCryptoKeyEngine<SHA256, WrapperSECP256R1, 256>::maker);
                                                                      ^
/usr/include/cryptopp/pubkey.h:779:7: note: must qualify identifier to find this
      declaration in dependent base class
        void GenerateRandom(RandomNumberGenerator &rng, const NameValueP...
             ^
In file included from cryptoppsigners.cc:5:
/usr/include/cryptopp/eccrypto.h:148:44: error: use of undeclared identifier
      'SetPublicElement'
                {this->AccessGroupParameters() = params; SetPublicElement(Q);}
                                                         ^
cryptoppsigners.cc:135:11: note: in instantiation of member function
      'CryptoPP::DL_PublicKey_EC<CryptoPP::ECP>::Initialize' requested here
  pubkey->Initialize(oid, q);
          ^
cryptoppsigners.cc:32:16: note: in instantiation of member function
      'CryptoPPECDSADNSCryptoKeyEngine<CryptoPP::SHA256,
      <anonymous>::WrapperSECP256R1, 256>::fromPublicKeyString' requested here
    return new CryptoPPECDSADNSCryptoKeyEngine(algorithm);
               ^
cryptoppsigners.cc:190:101: note: in instantiation of member function
      'CryptoPPECDSADNSCryptoKeyEngine<CryptoPP::SHA256,
      <anonymous>::WrapperSECP256R1, 256>::maker' requested here
  ...&CryptoPPECDSADNSCryptoKeyEngine<SHA256, WrapperSECP256R1, 256>::maker);
                                                                      ^
/usr/include/cryptopp/pubkey.h:657:15: note: must qualify identifier to find
      this declaration in dependent base class
        virtual void SetPublicElement(const Element &y) {AccessPublicPre...
                     ^
3 errors generated.
make[3]: *** [cryptoppsigners.o] Error 1
make[3]: Leaving directory `/home/travis/build/PowerDNS/pdns/pdns'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/home/travis/build/PowerDNS/pdns/pdns'
make[1]: *** [check] Error 2
make[1]: Leaving directory `/home/travis/build/PowerDNS/pdns/pdns'
make: *** [check-recursive] Error 1
```

**Comment by rubenk** [comment]
Building against the version of crypto++ in Ubuntu 12.04 with clang++ is basically broken:
http://crypto-users.996303.n3.nabble.com/error-when-compiling-with-clang-td463.html
and
https://github.com/zooko/cryptopp/commit/e1215ba319594a85c77c56d2909c3e6f86e63f13

**Comment by rubenk** [comment]
Let's look at this again when travis runs on 14.04

**Pull request closed without merging**
