### PR TITLE
Cleanup SOA editing

### PR DESCRIPTION
**Pull request by mind04**
fixes: #7361

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mnordhoff** [comment]
I just noticed that this line logs the unedited serial:

https://github.com/PowerDNS/pdns/blob/98423fe8b1439c7b12a0423955c8fc8764bc729a/pdns/tcpreceiver.cc#L1177

Worth changing in this PR? File a new bug? Not a bug?

**Comment by mind04** [comment]
@mnordhoff I like to keep things separated. Please open a new issue.

**Comment by Habbie** [comment]
This has conflicts, can you fix those?

**Comment by mind04** [comment]
@Habbie rebased

**Pull request merged**
