### PR TITLE
Remote: Implement getUnfreshSlaveInfos and setFresh

### PR DESCRIPTION
**Pull request by pieterlexis**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
@cmouse?

**Comment by pieterlexis** [comment]
> unit tests missing

This means adding full slave support the ruby script, which looks like a lot of work

**Comment by cmouse** [comment]
test-remotebackend.cc calls DNSBackend methods directly.

**Comment by pieterlexis** [comment]
> test-remotebackend.cc calls DNSBackend methods directly.

but it still seems that there is a responder needed that the remote backend talks to

**Comment by Habbie** [comment]
Pieter has solemnly promised to write tests soon.

**Pull request merged**
