### PR TITLE
rec: Check that DNSKEYs have the zone flag set

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

As required by rfc4034 Section 5.2. That should not make any difference in practice.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
Perhaps also https://tools.ietf.org/html/rfc4034#section-2.1.2 then?

> The Protocol Field MUST have value 3, and the DNSKEY RR MUST be
> treated as invalid during signature verification if it is found to be
> some value other than 3.

(also looks like 2.1.1 might be a better reference for the flags than 5.2)

**Comment by rgacogne** [comment]
> Perhaps also https://tools.ietf.org/html/rfc4034#section-2.1.2 then?

This one is already checked in `getByTag()`. In fact, perhaps I should move the "zone" bit check there as well.

> (also looks like 2.1.1 might be a better reference for the flags than 5.2)

Yes!

**Comment by Habbie** [comment]
Oh! What about the REVOKED bit?

**Comment by rgacogne** [comment]
Moved the "zone" check to `getByTag()` with the better reference, added a "not revoked" check and some unit tests.

**Comment by rgacogne** [comment]
Rebased to fix a conflict.

**Pull request merged**
