### PR TITLE
Fix Boost component library detection on ARM64 etc.

### LINKED ISSUE #3536: PowerDNS Recursor 4.0.0 Alpha 2: ./configure fails
```
...
checking boost/context/all.hpp usability... no
checking boost/context/all.hpp presence... yes
configure: WARNING: boost/context/all.hpp: present but cannot be compiled
configure: WARNING: boost/context/all.hpp:     check for missing prerequisite headers?
configure: WARNING: boost/context/all.hpp: see the Autoconf documentation
configure: WARNING: boost/context/all.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: boost/context/all.hpp: proceeding with the compiler's result
checking for boost/context/all.hpp... no
configure: error: cannot find boost/context/all.hpp
```
It seems only Boost<1.59 is affected.
[config_log.txt](https://github.com/PowerDNS/pdns/files/167303/config_log.txt)

### PR DESCRIPTION
**Pull request by nlyan**
On some platforms the Boost context headers are being shipped on architectures where the library can't be built. Here we patch boost.m4 to set HAVE_BOOST_<component> definitions based on whether the library actually exists.

This should also fix #3536 by avoiding the context/all.hpp header check.

### CODE REVIEW

**Comment by rubenk** [comment]
Thanks, LGTM.

**Comment by nlyan** [comment]
Fixes #3531

**Comment by Habbie** [comment]
@nlyan thanks! Want to upstream those boost.m4 changes?

**Comment by nlyan** [comment]
@Habbie : yes, it's something I will look in to, otherwise it'll cause grief down the line

**Comment by nlyan** [comment]
Upstreamed PRs relevent to this issue.

https://github.com/tsuna/boost.m4/pull/85

https://github.com/tsuna/boost.m4/pull/86

**Pull request merged**
