### PR TITLE
auth: have a global g_log (backport)

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Not really a backport, but a re-do because of too many conflicts.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [x] checked that this code was merged to master

### CODE REVIEW

**Comment by zeha** [comment]
is backporting this really a good idea...?

**Comment by Habbie** [comment]
> is backporting this really a good idea...?

We don't compile against Boost 1.67.0 without it (or, perhaps, something like it).

https://github.com/freebsd/freebsd-ports/blob/6fa3dca03cf2/dns/dnsdist/files/patch-boost-1.67

https://github.com/Homebrew/homebrew-core/pull/26812

**Comment by zeha** [comment]
> We don't compile against Boost 1.67.0 without it (or, perhaps, something like it).

I see. Maybe 4.1 should carry the "ugly" fix to keep the diff between 4.1.x -> 4.1.y small, so patches from 4.1.y can be applied to earlier versions more easily.

**Comment by pieterlexis** [comment]
> I see. Maybe 4.1 should carry the "ugly" fix to keep the diff between 4.1.x -> 4.1.y small, so patches from 4.1.y can be applied to earlier versions more easily.

patches _to_ 4.1.y would come from master and would be harder to apply though

**Pull request closed without merging**
