### PR TITLE
Update boost.m4

### LINKED ISSUE #6942: Boost context detection broken
- Program: Recursor
 - Issue type: Bug report

### Short description
configure is failing without boost context

### Environment
 - Operating system: CentOS armv7hl
 - Software version: git
 - Software source: git

### Other information

Last working commit 8491dcd
```
DEBUG: checking for Boost headers version >= 1.35.0... yes
DEBUG: checking for Boost's header version... 1_53
DEBUG: checking boost/container/flat_set.hpp usability... yes
DEBUG: checking boost/container/flat_set.hpp presence... yes
DEBUG: checking for boost/container/flat_set.hpp... yes
DEBUG: checking for the flags needed to use pthreads... -pthread
DEBUG: checking for the toolset name used by Boost for g++... gcc48 -gcc
DEBUG: checking whether Boost is new enough to use the context library...... yes
DEBUG: configure: checking whether the Boost context library actually links...
DEBUG: checking boost/context/fcontext.hpp usability... yes
DEBUG: checking boost/context/fcontext.hpp presence... yes
DEBUG: checking for boost/context/fcontext.hpp... yes
DEBUG: checking for boost/context/fcontext.hpp... (cached) yes
DEBUG: checking for the Boost context library... no
DEBUG: configure: Boost context library is missing
DEBUG: configure: MTasker will use System V ucontexts for context switching
```

First broken commit 1907d01

```
DEBUG: checking for Boost headers version >= 1.35.0... yes
DEBUG: checking for Boost's header version... 1_53
DEBUG: checking boost/container/flat_set.hpp usability... yes
DEBUG: checking boost/container/flat_set.hpp presence... yes
DEBUG: checking for boost/container/flat_set.hpp... yes
DEBUG: checking for the flags needed to use pthreads... -pthread
DEBUG: checking for the toolset name used by Boost for g++... gcc48 -gcc
DEBUG: checking whether Boost is new enough to use the context library...... yes
DEBUG: configure: checking whether the Boost context library actually links...
DEBUG: checking boost/context/fcontext.hpp usability... yes
DEBUG: checking boost/context/fcontext.hpp presence... yes
DEBUG: checking for boost/context/fcontext.hpp... yes
DEBUG: checking for boost/context/fcontext.hpp... (cached) yes
DEBUG: checking for the Boost context library... no
DEBUG: configure: error: cannot find flags to link with the Boost context library (libboost-context)
```

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Update to the latest boost.m4

* Fixes #6942 
* Fixes #8084

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
I ./configure'd 4c75f0296b691362cc8e706a83a21460269e0ef7 on s390x and that worked (did not try building it).

configure:22619: Context library: System V ucontexts

**Comment by zeha** [comment]
NB: on Linux boost.m4 needs 106 g++/ld invocations to find that the correct way of linking boost_system is `-lboost_system`. I hope it doesn't need another 106 invocations for `-lboost_thread`. Cutting down on that would be nice (at a later time?)...

**Comment by pieterlexis** [comment]
> NB: on Linux boost.m4 needs 106 g++/ld invocations to find that the correct way of linking boost_system is `-lboost_system`. I hope it doesn't need another 106 invocations for `-lboost_thread`. Cutting down on that would be nice (at a later time?)...

I'm quite sure it stores the last-correct link name.

**Comment by pieterlexis** [comment]
the changes to boost.m4 are merged upstream!

**Pull request merged**
