### PR TITLE
SSql: Use unique_ptr for statements

### PR DESCRIPTION
**Pull request by cmouse**
### Short description
Convert gSQLBackend and BindBackend to use unique_ptr for storing SSqlStatement pointers. This will prevent any accidentical copying or misuse of said pointers.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added regression tests
- [ ] added unit tests

### CODE REVIEW

**Comment by nlyan** [comment]
Why not make the prepare() function return a unique_ptr by value?

**Comment by cmouse** [comment]
I'll have to see what it causes.

**Comment by cmouse** [comment]
Seems to be doable, fixed.

**Comment by cmouse** [comment]
@mind04 has tested goracle that it compiles.

**Comment by nlyan** [comment]
Use of std::move() in setupStatements() is redundant, since the return value from prepare() is already an rvalue and will be moved-from by default

**Comment by cmouse** [comment]
fixed @nlyan's nit.

**Comment by nlyan** [comment]
LGTM

**Pull request merged**
