### PR TITLE
Only build epollmultiplexer on Linux

### PR DESCRIPTION
**Pull request by rubenk**
fixes make -C pdns pdns_recursor on OSX and FreeBSD

### CODE REVIEW

**Comment by ahupowerdns** [comment]
so with only a tiny bit of love this could link kqueuemplexer for freebsd!

**Comment by rubenk** [comment]
Sure, will do. Darwin doesn't use kqueue? What about the other BSD's?

**Comment by Habbie** [comment]
summary of `grep mplexer sysdeps/*`:
* FreeBSD = kqueue
* Linux = epoll
* SunOS = ports+devpoll

All other platforms get just the selectmplexer, which is portable but limited to 1024 FDs.

(Darwin claims to support kqueue; I haven't tested the Recursor with it)

**Comment by rubenk** [comment]
ok, that makes it a whole lotta easier :)

**Pull request merged**
