### PR TITLE
Make pdnsutil set-publish-cds default to SHA-256 only

### PR DESCRIPTION
**Pull request by mnordhoff**
### Short description
`pdnsutil set-publish-cds` defaults to enabling both SHA-1 and SHA-256. This changes it to use SHa-256 only.

(It's just a default, anyone can still enable SHA-1 if they want to.)

Reasons:

* ~~Burning hatred for all things SHA-1.~~
* Popular TLDs including .com use only SHA-256, so a resolver that only supports SHA-1 is terribly old and not very useful.
* `secure-zone` uses ECDSA by default. Are there even any resolvers that support ECDSA but don't support SHA-256?
* [BIND 9.15.0 did it.](https://ftp.isc.org/isc/bind9/9.15.0/RELEASE-NOTES-bind-9.15.0.html)

I've run part of the test suite, but not actually tried it.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mnordhoff** [comment]
I forgot the best rationalization: Packet size!

**Comment by mnordhoff** [comment]
There's a test failure, but it sounds unrelated: it has something to do with `edited_serial`.

https://circleci.com/gh/PowerDNS/pdns/4595

**Comment by Habbie** [comment]
I merged #7962 today, which introduces edited_serial..

**Comment by mnordhoff** [comment]
test-auth-api passed in another PR. :/

https://circleci.com/gh/PowerDNS/pdns/4629

**Comment by mnordhoff** [comment]
Okay, the current HEAD d0283b330465ee714fff20fb5cc24bd844c1be71 actually passes.

https://circleci.com/gh/PowerDNS/pdns/4736

Am I making a mistake? I don't get it.

**Comment by mnordhoff** [comment]
This time, a couple of the Travis builds failed with `E: Failed to fetch http://repo.powerdns.com/ubuntu/dists/trusty-auth-master/main/binary-amd64/Packages.gz  Hash Sum mismatch`.

;_;

**Pull request merged**
