### PR TITLE
Do not check slave domain freshness unless slave=yes

### PR DESCRIPTION
**Pull request by cmouse**
Before this, the code would perform initial AXFR from master(s) for slave domains on nameserver with slave=no.

### CODE REVIEW

**Comment by cmouse** [comment]
ready for review

**Comment by mind04** [comment]
To much behaviour change for 3.4.6 if you ask me.

**Comment by cmouse** [comment]
you mean people expect slave to work if slave is disabled?

**Comment by Habbie** [comment]
Agreeing with @mind04, this will break more things than it will fix *in practice*. Merged to master though!

**Pull request closed without merging**
