### PR TITLE
update the output of 'pdns monitor'

### PR DESCRIPTION
**Pull request by tfarina**
The current output is pretty out-of-date, it is back from 2002!

This patch updates the output to the version of 3.3.

### CODE REVIEW

**Comment by Habbie** [comment]
Hi, thanks for this. It looks like your update does not reflect the error condition deliberately demonstrated in the old version!

**Comment by tfarina** [comment]
@Habbie do I need to change anything or does it LGTY?

**Comment by Habbie** [comment]
You need to change it. That output in the docs needs to show the error of not having the pdns database, your version shows a working setup instead.

**Comment by tfarina** [comment]
@Habbie closing this as it has landed in https://github.com/PowerDNS/pdns/pull/3136.

**Pull request closed without merging**
