### PR TITLE
rec: Change dnssec default to `process`

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
This is a sane default nowadays. It will also greatly help if the aggressive NSEC cache (#10047) is enabled by default.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by omoerbeek — APPROVED** [review]

**Comment by pieterlexis** [comment]
>  ci/circleci: test-recursor-regression — Your tests failed on CircleCI 

seems like a legit failure

**Comment by rgacogne** [comment]
One drawback of that latest commit is that it adds 25s for each test suite because we start several auth processes, run secure-zone, etc. Perhaps we could start only the auth processes that we really need instead?

**Comment by pieterlexis** [comment]
> One drawback of that latest commit is that it adds 25s for each test suite because we start several auth processes, run secure-zone, etc. Perhaps we could start only the auth processes that we really need instead?

we do, just the root. As having no reachable root server breaks the recursor

**Comment by rgacogne** [comment]
> we do, just the root.

Ah, I was missing the fact that we only prepare the zones present in `_auth_zones`, and start the processes needed for these only. That's nice! You can indeed ignore my comment, then, sorry :)

**Comment by omoerbeek** [comment]
Failing test:

```
FAIL: testA (test_Protobuf.OutgoingProtobufDefaultTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/project/regression-tests.recursor-dnssec/test_Protobuf.py", line 372, in testA
    self.checkProtobufOutgoingQuery(msg, dnsmessage_pb2.PBDNSMessage.UDP, query, dns.rdataclass.IN, dns.rdatatype.A, name)
  File "/opt/project/regression-tests.recursor-dnssec/test_Protobuf.py", line 226, in checkProtobufOutgoingQuery
    self.checkOutgoingProtobufBase(msg, protocol, query, initiator, length=length)
  File "/opt/project/regression-tests.recursor-dnssec/test_Protobuf.py", line 166, in checkOutgoingProtobufBase
    self.assertEquals(msg.inBytes, len(query.to_wire()))
AssertionError: 32 != 44
```

**Pull request merged**
