### PR TITLE
calidns: macOS stubs for send/recvmmsg

### PR DESCRIPTION
**Pull request by wojas**
### Short description

Make calidns compile on macOS, by adding stubs for send/recvmmsg.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Just an idea, perhaps we could detect `sendmmsg()/recvmmsg()` during the configure, like is done in [1]  (from #5576, not yet merged), so the stubs can be used on other OS than macOS?

[1]: https://github.com/PowerDNS/pdns/pull/5576/commits/0beaa5c825059986d3ce108a4bd2578a08d6d1d0

**Comment by zeha** [comment]
@wojas ping?

**Comment by wojas** [comment]
A more general solution with would indeed be preferred. I just filed this PR as I had this hack sitting around locally and thought it might be useful.

Do I understand correctly that `#ifdef __APPLE__` needs to be replaced with `#ifndef HAVE_RECVMMSG` and friends? No other changes needed?

**Comment by rgacogne** [comment]
> Do I understand correctly that #ifdef __APPLE__ needs to be replaced with #ifndef HAVE_RECVMMSG and friends? No other changes needed?

It looks like this would be it, yes. But please feel free to let me know if you don't have the time to look into  it and I will!

**Comment by omoerbeek** [comment]
Was fixed by #7871. Never noticed this PR before...

**Pull request closed without merging**
