### PR TITLE
[WIP] CONTRIBUTING rules; release/branch management

### PR DESCRIPTION
**Pull request by Habbie**
Intentionally empty file just so we can have some discussion here.

Things I would like to demand/expect from contributions in the future:
* doc updates
* test updates
* changelog changes (semi-easily done with two WIP doc sections [auth and recursive]) but should think about how to do that without breaking it on every cherry-pick to a bugfix branch

Things we should document (perhaps not in CONTRIBUTING.md):
* what does 'master' mean
* how do we deal with stable branches/LTS versions

Please add further ideas, discussions, send me PRs for text suggestions!

### CODE REVIEW

**Comment by rubenk** [comment]
* should pass travis?
* I know this is going to be contentious, but something about code style? think about indentation, whitespace etc. Ideally checked with a script.

**Comment by Habbie** [comment]
Yes, certainly -something- about whitespace, if only "don't combine cleanup with actual work" -> in general something about splitting up commits to make reviewing, rebasing and cherrypicking easier.

**Comment by zeha** [comment]
Can't really think of anything else.

**Comment by pieterlexis** [comment]
Maybe make it clear that no CLA (Contributor Licence Agreement) is needed. Some free software projects backed by companies require it for legal reasons.

**Comment by rubenk** [comment]
This might be obvious for most people used to working with a VCS but, in the commit message:
* tell why the change does what it does, not how it does it.
* first line with short description, less than 50 chars, then a blank line and a more detailed explanation, wrapped to max 72 characters.

Here's a good example: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by Habbie** [comment]
http://keepachangelog.com/

**Comment by ahupowerdns** [comment]
Hi - some suggestions below, which might end up in 'CONTRIBUTING.MD'. Please let us know if this works!

The status of our tree needs to be clarified. "HEAD" is frequently good for production, especially when we are heading up for a major release. Running from HEAD at that point is in fact recommended. However, at times, stability may move to a release branch. 

This is particularly the case when we are doing major redevelopment, spring cleaning or even moving to a newer revision of C++. For the past year it has generally always been safe to run from HEAD, but the new guidance is: please check and ask. We may break HEAD during big work, but we'll make sure to announce this, and also let you know where stability can be found. For now, this would be in branches for auth-3.4 and recursor-3.7 development, for example.

In addition, we'll make sure to do pull requests to HEAD for things we worry might break. This will make sure everything gets tested and is visible before we merge. This includes merges from bert. Sorry about the c++2011 merge, which was badly tested and unannounced.

Finally, some attention to the alternate approach, trying to keep 'HEAD' stable at all times and do all testing in branches. This has been attempted here and there, but tends to lead to 'merge angst'.

The approach we favour is that HEAD is mostly stable and usable, except when we announce we are entering a phase of heavy development. If you want guarantees of security, make sure to follow branches that are labelled with version numbers.

**Comment by Habbie** [comment]
Probably should clarify that HEAD=master when using this text in CONTRIBUTING.md or in the, I suspect, pending email to pdns-dev. Otherwise, awesome!

**Comment by Habbie** [comment]
Suggestion: open up 'rel/rec-3.7.3' right after the release of rec-3.7.2, so we always have a place to backport fixes into; snapshots from such branches are always extremely safe to run, compared to master.

**Comment by rubenk** [comment]
One condition I think is that patches for the stable branches should go to master first.

**Comment by pieterlexis** [comment]
@habbie, this sounds like you want a system akin to [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) but then use a dual branch strategy (because the recursor is (somewhat) independent from the authoritative server).

**Comment by cmouse** [comment]
As a rule, would you make pull requests against master or rel branch?

**Comment by rubenk** [comment]
@pieterlexis gitflow works with 2 branches with infinite lifetime, which is a bit too complex IMHO. In Habbie's example, the stable branch for rec-3.7.3 would be closed after rec-3.7.3 is released, after which we open rec-3.7.4 and so on. These branches would only accept bugfixes, backported from master.

This doesn't say anything about how we should stabilize master for a new feature release of course. My suggestion is to branch of master at some point and bump the minor release number, so the next version of recursor would be 3.8.0. This is a bit similar to how the linux kernel does it. One additional advantage is that it's easier to divide the work, so you can have different people responsible for the master branch, the stable recursor branch and the stable auth branch.

**Comment by zeha** [comment]
.@cmouse IMO, PRs in general should go to master, and then have backport PRs for the versioned branches (not unlike how this is done today).

**Comment by Habbie** [comment]
Write down that docs live on master and on master only.

**Comment by pieterlexis** [comment]
Also important, when adding new functionality, functions and classes should be sufficiently documented for doxygen to generate useful documentation.

**Comment by ZaphodB** [comment]
as per request and explained by @Habbie:
in order to prevent confusion the following clarification on travis vs. jenkins CI should make it into documentation. Also i think its best kept in README.md so github users see it right away.

- jenkins (at autotest.powerdns.com) runs trusted code from a select few branches on -our- repo. it does not test pull requests, as it cannot deal with random untrusted code
- travis (at travis-ci.org, which is a free service) runs all pushes to all branches on all repos and forks that have it enabled, including any untrusted code, and including pull requests to those repos that have it enabled
- code changes should first be tested with the travis service before generating a pull request against the PowerDNS master branch

**Comment by zeha** [comment]
@pieterlexis I think this is asking too much for new contributions when the existing code base has none of it and there's no style to copy from.

**Comment by Habbie** [comment]
"The current code base is lacking in X" is not -generally- a valid argument against asking contributors to do more X. Lack of examples to make any X easy is a valid point, and we should fix that.

That said, I think it's important to distinguish between 'this is what a PR should look like when it comes in fresh' and 'this is what it looks like by the time we merge it'. Anyone should feel free to submit an incomplete PR and ask for help - including the doxygen or any other steps.

**Comment by Habbie** [comment]
Not a fan of pulls titled 'fixes issue #x'

**Pull request merged**
