### PR TITLE
Always build the pdns subdir first.

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by pieterlexis** [comment]
Hi Ruben,

Could you split the commit in 2? The changes to the `configure.ac` are not related to the ones in the `Makefile.am`.

**Comment by rubenk** [comment]
Sure, will do.

**Comment by rubenk** [comment]
Done :)

**Comment by mind04** [comment]
you can't build /pdns before /modules

**Comment by rubenk** [comment]
I just did, and so did Travis. Please explain why this shouldn't be possible.

**Comment by mind04** [comment]
I'm not sure why travis is ok with it but the error above is the result of:
```
git checkout pdns/pull/2517
git clean -dfx
./bootstrap
./configure --with-modules='bind' --with-dynmodules=''
make
```

**Comment by rubenk** [comment]
Ah yes, Travis does only dynamic builds, in which case it isn't a problem since the .so's are not linked-in.

This will have to wait until we stop doing static builds then. Thanks.

**Comment by pieterlexis** [comment]
@rubenk, I don't think this is about static vs dynamic, but more with compiled-in modules (that can still be dynamically linked) vs modules that are loadable at runtime. This patch will break for everyone who compiles modules needed into their `pdns_server`. Moving `modules` earlier in the `SUBDIRS` breaks as well (because of dependencies on code in `/pdns`).

This could be fixed by having the code correctly structured, but I don't think this will happen soon.. Unless we can make it part of the spring-cleaning (cc/ @Habbie @ahupowerdns)

**Comment by rubenk** [comment]
@pieterlexis I think we're talking about the same thing, by static I meant compiled-in modules, not that pdns itself is a (semi-)static binary.

Perhaps I misunderstood things but I always thought the long term plan was to drop the option to compile in modules and always use dynamic loading, which most distros do anyway.

This PR was indeed part of the bigger plan I started a year or so ago to untangle all this stuff without restructuring the code. I tried a few different alternatives like non-recursive make and a static libpnds.a convenience lib, but these all have their own sets of issues.

If you have any thoughts on how restructuring the code should fix this, I'm all ears :)

**Comment by pieterlexis** [comment]
Closing this PR, compiled-in modules will be supported for a long time in the future.

**Pull request closed without merging**
