### PR TITLE
builder: add ubuntu-oracular target

### LINKED ISSUE #14084: auth, rec: no ECDSA with OpenSSL 3.3
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
In OpenSSL 3.3 (at least as packaged in Alpine Edge and Debian Experimental), `pkg-config libcrypto --variable=prefix` returns nothing instead of `/usr`. This causes us to fail to find `ecdsa.h`

### Environment
 - Operating system: Alpine Edge, Debian Experimental (both as of today0
 - Software version: auth 4.9, rec 5, probably others
 - Software source: tarballs

### Steps to reproduce
1. build as usual

### Expected behaviour
Working ECDSA, passing tests.

### Actual behaviour
`checking for /include/openssl/ecdsa.h... no`

and the generic signers test fails. Note the path, it's missing `/usr` at the beginning.

### Other information
`--with-libcrypto=/usr` works around the issue

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
includes a workaround for libcrypto brokenness, which fixes #14084

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
need to check if dnsdist is actually happy

**Comment by Habbie** [comment]
> need to check if dnsdist is actually happy

`#37 113.5 checking whether compiling and linking against OpenSSL's libcrypto works... yes` it is!

**Review by romeroalx — APPROVED** [review]
LGTM! 

Tested here: [https://github.com/romeroalx/pdns/actions/runs/12028315662](https://github.com/romeroalx/pdns/actions/runs/12028315662)

**Comment by Habbie** [comment]
> Tested here: https://github.com/romeroalx/pdns/actions/runs/12028315662

oh nice, thanks!

**Pull request merged**
