### PR TITLE
builder-support: Enable missing dnsdist features on Amazon 2023, unbreak dnsdist package on EL8/9

### PR DESCRIPTION
**Pull request by rgacogne**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
with

```
diff --git a/builder-support/specs/dnsdist.spec b/builder-support/specs/dnsdist.spec
index f03301fcc..df9d6b7c4 100644
--- a/builder-support/specs/dnsdist.spec
+++ b/builder-support/specs/dnsdist.spec
@@ -101,7 +101,7 @@ export RANLIB=gcc-ranlib
   --with-libsodium \
   --with-net-snmp \
 %endif
-%if 0%{?rhel} >= 8
+%if 0%{?rhel} >= 8 || 0%{?amzn} == 2023
   --enable-dns-over-quic \
   --with-quiche \
 %endif
```

I get `configure: DNS over QUIC (DoQ): yes`. Build is running, will report back.

**Comment by Habbie** [comment]
> I get `configure: DNS over QUIC (DoQ): yes`. Build is running, will report back.

Patch is incomplete. Will fix and then push to this PR :)

**Comment by Habbie** [comment]
```
dnsdist 1.9.0-alpha2.1.ddistfixamz2023.g5f51ec9e1.dirty (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
Enabled features: cdb dns-over-quic dns-over-tls(gnutls openssl) dns-over-https(h2o nghttp2) ebpf fstrm ipcipher libedit lmdb protobuf re2 recvmmsg/sendmmsg systemd
```

(push coming)

**Comment by Habbie** [comment]
I rebased everything and added a commit. 

The last commit is quite important.

Besides making DoQ be included in the build on amzn2023, it prevents the RPM (on any DoQ-supporting platform) from generating a libdnsdist-quiche dependency in package metadata, while not providing it. To get out of that situation, I added `%define __requires_exclude libdnsdist-quiche\\.so` to remove the dep.

@phonedph1 mentioned https://github.com/cloudflare/quiche/pull/599/files to me, which would solve it differently - the dep would still be generated, but the Provides would also be. However, I don't think we want our package to say 'provides libdnsdist-quiche', so the filter I committed makes the most sense to me.

**Review by Habbie — APPROVED** [review]

**Comment by rgacogne** [comment]
> which is a great improvement, but I think we want DoQ to say 'yes'?

We do! :facepalm:

**Review by rgacogne — COMMENTED** [review]
Thanks!

**Pull request merged**
