### PR TITLE
pin protobuf to <= 3.20 because of incompatible changes

### PR DESCRIPTION
**Pull request by Habbie**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by omoerbeek — APPROVED** [review]

**Comment by Habbie** [comment]
https://builder.powerdns.com/#/builders/97/builds/2409

**Comment by rgacogne** [comment]
I wonder whether setting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` would be too slow for our usage. If that's fine it would prevent that kind of surprises from happening again in the future.

**Comment by Habbie** [comment]
I'll try that.

**Comment by Habbie** [comment]
replaced by #11658

**Pull request closed without merging**
