### PR TITLE
RFC2136: Support autoserial

### LINKED ISSUE #2066: autoserial and dnsupdate don't work together
Hello guys,

thanks for adding support for RFC 2136.

I think I found a minor issue with using that in conjunction with autoserial. Every time some record is added and/or changed by using the nsupdate command, the SOA record is updated and the serial is changed. You can select multiple ways in which that is done, but none of that seems to honour the autoserial setting (the serial is just 0 and if that is required, it will be computed by using the largest "change_date" value of any record of that zone).

In order to support autoserial I suppose that only two very simple things need to be done:
1) If the serial is 0, don't change it.
2) change_date of the new or changed record must be set accordingly. Currently it is NULL.

That should be it. Is there any reason why this is not supported right now?

### PR DESCRIPTION
**Pull request by mtremer**
Please merge these patches.

They introduce triggers that will automatically keep up the change_date column of the database when a row is inserted or updated and will update change_date of the SOA record if a record is deleted from the database.

If the autoserial feature is in use, all changes to the zone will leave the serial in the content field of the SOA record untouched if it is zero. PowerDNS will automatically replace that accordingly with the timestamp of the most recently changed record (fixes #2066).

### CODE REVIEW

**Comment by Habbie** [comment]
Not sure we want to introduce triggers to the default scheme, usage of change_date is extremely limited in our user base, and as said before, appropriate usage is a matter of local policy.

(If we did want the triggers, another issue would be that this PR only touches postgres).

**Comment by mtremer** [comment]
Well, the trigger will leave change_date untouched if it has been deliberately set to NULL.

Basically I would say that there has to be some sort of decision if autoserial is a feature that you are willing to support or not. I personally can rewrite my code (although I don't really want to as I think that autoserial does the job much better), but I wouldn't want to use an unsupported feature and run into serveral issues.

Filling change_date would not create much additional overhead. If a record is created or updated, the trigger will just fill in the change_date field and create no additional query. If a record is removed, there will be one additional UPDATE on the SOA record. I think that this is pretty cheap and on the plus hand everyone who uses autoserial cannot ever run into any problems with serials going backwards.

Adding the triggers to the other database backends is easy to do. I just don't have a spare Oracle installation to test this with.

**Comment by mtremer** [comment]
Is there anything going on with this?

**Comment by Habbie** [comment]
Hi Michael,

we are currently focused on getting recursor 3.7.0 and auth 3.4.2 released - this PR is relevant to neither. Please feel free to ping us after those releases!

**Comment by mtremer** [comment]
Hello there,

just wanted to send my reminder as the two releases are done...

**Comment by mtremer** [comment]
Great that this is making a little bit of progress in #2147. I am just not entirely sure if it is required to print a log message at the notice level for every RFC2136 update though.

Autoserial still does *not* work unless the database triggers are added to the default layout or the SQL queries are changed.

**Comment by Habbie** [comment]
> Basically I would say that there has to be some sort of decision if autoserial is a feature that you are willing to support or not. I personally can rewrite my code (although I don't really want to as I think that autoserial does the job much better), but I wouldn't want to use an unsupported feature and run into serveral issues.

This question is valid, and we need to answer that. We can do that in an issue. This PR, as it stands, is not mergeable for various reasons.

**Comment by mtremer** [comment]
So I take it that using RFC2136 in combination with autoserial is broken and there is no interest in fixing it.

Thank you very much looking into this, but I am still disappointed that we could not get it fixed since the fix actually is very easy - even when not implemented as a trigger but in code.

**Pull request closed without merging**
