### PR TITLE
Properly handle domains with zero serial

### PR DESCRIPTION
**Pull request by cmouse**
Fixes bug where slave considers domain with no serial (missing) to be larger than master's and does not fetch it.

### CODE REVIEW

**Comment by cmouse** [comment]
ready for review

**Comment by pieterlexis** [comment]
lgtm

**Comment by cmouse** [comment]
Blocked by #3031

**Comment by Habbie** [comment]
Can you squash the tinydns changes a bit? Otherwise this set of commits looks fine to me.

**Comment by cmouse** [comment]
Done.

**Comment by Habbie** [comment]
LGTM

**Comment by cmouse** [comment]
Fixed merge conflict.

**Pull request merged**
