### PR TITLE
Restart recursor / auth on failure (unlimited restarts)

### PR DESCRIPTION
**Pull request by 42wim**
Not that it ever crashes, but in the unlikely event that it does, please restart it.

### CODE REVIEW

**Comment by cmouse** [comment]
This actually touches both recursor and auth. Perhaps have them as separate commits?

**Comment by cmouse** [comment]
Travis error: took too long (50 min limit exceeded)

**Comment by Habbie** [comment]
I'm okay with this being one commit. Travis restarted.

**Comment by rubenk** [comment]
Can you explain your reasons for using StartLimitedInterval of 0 instead of the default?

**Comment by 42wim** [comment]
@Habbie wanted unlimited restarts, this only possible by disabling the ratelimit.(StartLimitInterval=0) afaik

**Comment by pieterlexis** [comment]
one thing I don't get, why the removal of `ExecStop`?

**Comment by Habbie** [comment]
Because signals are better :)

**Comment by pieterlexis** [comment]
@Habbie this looks good to me (if you agree with unlimited restarts)

**Comment by rubenk** [comment]
Note that systemd makes it quite easy to override the defaults for users by dropping an include file in /etc/systemd/system. I don't want to be a pain in the ass, but we should only diverge from the default when there's a good reason for it. I for one would rather have that the pdns service is stopped after 3 failed attempts at restarting, so that my monitoring can detect it, than that it keeps reconnecting, perhaps using a lot of resources in the process.

**Comment by pieterlexis** [comment]
Even though @rubenk's point is valid, losing the DNS service is worse than it restarting quickly by default. As this filke is in `contrib/`, people are still free to choose to do it differently.

**Pull request merged**
