### PR TITLE
all: DNSName, speeds up toString() conversion

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
This PR speeds up the `DNSName::toString()` process by avoiding unnecessary memory copies.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by ahupowerdns** [comment]
just wondering - was this measured to actually deliver a speedup?

**Comment by pieterlexis** [comment]
> just wondering - was this measured to actually deliver a speedup?

@chbruyand: `pdns/speedtest.cc`

**Comment by chbruyand** [comment]
@ahupowerdns I measured a 20% time decrease to perform basic `toString()` conversions. Maybe you have better suggestions ?

**Comment by rgacogne** [comment]
FWIW I wrote a very similar optimization a few weeks ago when I was trying to make protobuf logging faster, and it had a measurable impact. I forgot to PR it when we realized that the real pain was syscall-related (fixed in #7428).

**Comment by Habbie** [comment]
The Travis failure appears to be unrelated. Do we want to merge this?

**Comment by rgacogne** [comment]
For the record, I'm currently doing some benchs with protobuf export enabled, and this PR makes the cost of `DNSName::toString()` go from 2% of the total CPU usage in my flame graphs to ~1%.

**Pull request merged**
