### PR TITLE
Backport 7822 to rec-4.2.x: Update gen-version to use latest tag for version nunmbers

### PR DESCRIPTION
**Pull request by omoerbeek**
### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [X]  checked that this code was merged to master

### CODE REVIEW

**Comment by pieterlexis** [comment]
Updating the `builder/` subproject won't hurt either :)

**Comment by omoerbeek** [comment]
> Updating the `builder/` subproject won't hurt either :)

My git foo is lacking to do this without errors and confidence. Can you do that part?

**Comment by Habbie** [comment]
I'll do it.

**Comment by pieterlexis** [comment]
> My git foo is lacking to do this without errors and confidence. Can you do that part?

something like:
```bash
cd builder; git remote update; git reset --hard origin/master; cd ..; git commit -am 'update builder'
```

**Comment by Habbie** [comment]
> I'll do it.

I'll wait and see if Otto gets it done with Pieter's hints :)

**Pull request merged**
