### PR TITLE
remove hardcoding of port 53 for TCP/IP forwarded zones in recursor, …

### PR DESCRIPTION
**Pull request by ahupowerdns**
…to address #4799

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code (I removed code!)
- [ ] added regression tests
- [ ] added unit tests
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by kutunet** [comment]
please help me pach on my pdns server for this issue. trims

**Comment by Habbie** [comment]
@kutunet I don't think I understand your question - what can we do for you?

**Comment by kutunet** [comment]
apologize for my shortcomings in the english language,

I misunderstood the configuration so that when I do find an error in the configuration-recursor PDNs (/etc/pdns-recursor/recursor.conf), the following is my configuration

forward-zones =. = 208.67.222.222:5353, 208.67.220.220:5353,
forward-zones-recurse =. = 208.67.222.222:5353, 208.67.220.220:5353,

Dec 29 01:28:14 ns1.mydomain.tld pdns_recursor [10288]: Dec 29 01:28:14 PowerDNS recursor itself will distribute queries over threads
Dec 29 01:28:14 ns1.mydomain.tld pdns_recursor [10288]: Dec 29 01:28:14 Redirecting queries for zone '.' to: 208.67.222.222:5353
Dec 29 01:28:14 ns1.mydomain.tld pdns_recursor [10288]: Dec 29 01:28:14 Exception: Error parsing '208.67.220.220:5353', missing =
Dec 29 01:28:14 ns1.mydomain.tld systemd [1]: PDNs-recursor.service: main process exited, code = exited, status = 1 / FAILURE
Dec 29 01:28:14 ns1.mydomain.tld systemd [1]: Failed to start PowerDNS recursor.

but after I noticed back and make configuration changes as follows:
 
forward-zones =. = 208.67.222.222:5353;208.67.220.220:5353,
forward-zones-recurse =. = 208.67.222.222:5353;208.67.220.220:5353,


PDNs-recursor can return goes well, I guess this is the difference between powerdns version 3.X with 4.x. the initial configuration is my configuration on PDNs 3.x and can run normally but not on PDNs 4.x


Thank you for your response

**Comment by Habbie** [comment]
@kutunet your first configuration is broken; your second configuration is correct. If you have further questions, please use our mailing lists or IRC channel. Our GitHub issue system is not a support forum, and your question is not about this bug ticket.

**Pull request merged**
