### PR TITLE
dnsdist, recursor: EDNSOptionView improvements

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
Doc fix; Lua tables fix (may need upgrade notes?).

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by rgacogne** [comment]
Sorry about that, I think I will never wrap my head around `Lua` tables starting at 1. The tests in `test_EDNSOptions.py` needs to be updated, since the code there relies on the index starting at 0. We have the exact same code in `lua-recursor4.cc` by the way.

**Comment by Habbie** [comment]
> Sorry about that, I think I will never wrap my head around `Lua` tables starting at 1.

I wonder if a simpler vector could be convinced to automatically do the right thing so we have to worry less about it on the C++ side.



> The tests in `test_EDNSOptions.py` needs to be updated, since the code there relies on the index starting at 0.

I suspected that was the reason of the test failures :)



> We have the exact same code in `lua-recursor4.cc` by the way.

Thanks!

**Comment by Habbie** [comment]
> I wonder if a simpler vector could be convinced to automatically do the right thing so we have to worry less about it on the C++ side.

Looks like we can - see commit 'simplify vector indexing'. As discussed elsewhere, we wonder why we didn't do that before.

**Comment by Habbie** [comment]
To find accidental 0-indexing, apply this patch, then run all tests, see what fails, then weed out false negatives. I cannot think of a good way to apply this to our usual testing.

```diff
diff --git a/ext/luawrapper/include/LuaContext.hpp b/ext/luawrapper/include/LuaContext.hpp
index b4c9ef15e..124349eaf 100644
--- a/ext/luawrapper/include/LuaContext.hpp
+++ b/ext/luawrapper/include/LuaContext.hpp
@@ -2137,6 +2137,56 @@ struct LuaContext::Pusher<std::unordered_map<TKey,TValue,THash,TKeyEqual>> {
     }
 };
 
+
+
+
+// vectors of int, X pairs
+template<typename TType2>
+struct LuaContext::Pusher<std::vector<std::pair<int,TType2>>> {
+    static const int minSize = 1;
+    static const int maxSize = 1;
+
+    static PushedObject push(lua_State* state, const std::vector<std::pair<int,TType2>>& value) noexcept {
+        static_assert(Pusher<typename std::decay<int>::type>::minSize == 1 && Pusher<typename std::decay<int>::type>::maxSize == 1, "Can't push multiple elements for a table key");
+        static_assert(Pusher<typename std::decay<TType2>::type>::minSize == 1 && Pusher<typename std::decay<TType2>::type>::maxSize == 1, "Can't push multiple elements for a table value");
+
+        auto obj = Pusher<EmptyArray_t>::push(state, EmptyArray);
+
+        if(value.size() && value.begin()->first == 0) {
+            throw std::runtime_error("0-indexed vector spotted");
+        }
+
+        for (auto i = value.begin(), e = value.end(); i != e; ++i)
+            setTable<TType2>(state, obj, i->first, i->second);
+        
+        return obj;
+    }
+};
+
+// vectors of short, X pairs
+template<typename TType2>
+struct LuaContext::Pusher<std::vector<std::pair<short,TType2>>> {
+    static const int minSize = 1;
+    static const int maxSize = 1;
+
+    static PushedObject push(lua_State* state, const std::vector<std::pair<short,TType2>>& value) noexcept {
+        static_assert(Pusher<typename std::decay<short>::type>::minSize == 1 && Pusher<typename std::decay<short>::type>::maxSize == 1, "Can't push multiple elements for a table key");
+        static_assert(Pusher<typename std::decay<TType2>::type>::minSize == 1 && Pusher<typename std::decay<TType2>::type>::maxSize == 1, "Can't push multiple elements for a table value");
+
+        auto obj = Pusher<EmptyArray_t>::push(state, EmptyArray);
+
+        if(value.size() && value.begin()->first == 0) {
+            throw std::runtime_error("0-indexed vector spotted");
+        }
+
+        for (auto i = value.begin(), e = value.end(); i != e; ++i)
+            setTable<TType2>(state, obj, i->first, i->second);
+        
+        return obj;
+    }
+};
+
+
 // vectors of pairs
 template<typename TType1, typename TType2>
 struct LuaContext::Pusher<std::vector<std::pair<TType1,TType2>>> {
```

**Comment by Habbie** [comment]
> We have the exact same code in `lua-recursor4.cc` by the way.

Also fixed now.

**Pull request merged**
