### PR TITLE
Include LuaContext.hpp for LuaContext::ExecutionErrorException

### PR DESCRIPTION
**Pull request by swegener**
```
test-lua_auth4_cc.cc: In member function ‘void lua_auth4_cc::test_prequery::test_method()’:
test-lua_auth4_cc.cc:37:53: error: expected unqualified-id before ‘&’ token
   37 |   } catch (const LuaContext::ExecutionErrorException& e) {
      |                                                     ^
```

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
Hello! We have a very nice pull request template, that, when filled in, tells us a bunch of useful stuff about your PR. I've re-inserted it for you above; please fill it out.

**Comment by zeha** [comment]
For further ref, testing the Lua integration only makes sense if the build has been configured with Lua.

**Comment by Habbie** [comment]
> For further ref, testing the Lua integration only makes sense if the build has been configured with Lua.

Indeed, I found it now: a non-lua build fails during `make check` with the errors posted above. However, the fix in this PR is wrong.

**Comment by zeha** [comment]
> However, the fix in this PR is wrong.

Indeed. Once again one could ask "should Lua stay optional?" 💣

**Comment by Habbie** [comment]
> Indeed. Once again one could ask "should Lua stay optional?" bomb

You're right. Let's change that.

**Comment by Habbie** [comment]
#8744 makes Lua mandatory for Auth builds, so this PR is no longer useful. Closing this, thank you!

**Pull request closed without merging**
