### PR TITLE
use the vars

### PR DESCRIPTION
**Pull request by stasic**
These variables are defined so we use them everywhere

### CODE REVIEW

**Comment by Habbie** [comment]
@pieterlexis

**Comment by Habbie** [comment]
@zeha

**Comment by pieterlexis** [comment]
This script is only used inside our buildbot environment (see the README.md), let me set these variables correctly before pulling.

**Comment by pieterlexis** [comment]
Ok, I modified our buildbot config to explicitly set these environment vars. so lgtm.

@stasic Are you using this script in your environment to create packages?

**Comment by zeha** [comment]
The Debian custom is to use DEBFULLNAME with a fall back to NAME, and DEBEMAIL with a fallback to EMAIL. Maybe by now it's better to just require + call `dch` ...

**Comment by pieterlexis** [comment]
I had a `dch` implementation when I started, but it was more painful (from memory: setting `EDITOR` and `VISUAL` to `cat`, needing a changelog file in the repo, no way to automatically set the message)

**Comment by stasic** [comment]
@pieterlexis no, I am not using it. I just thought this patch might be helpful or is at least making usage of already defined vars.

**Pull request merged**
