### PR TITLE
dnsdist: Document how to generate a console key without dnsdist

### PR DESCRIPTION
**Pull request by rgacogne**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]
I also had a macOS user test the line, works there too.

`openssl rand -base64 32` would work on many systems as well. I'm pondering which version is better, or whether we should just mention both? Approved in any case.

**Comment by rgacogne** [comment]
Good one, I'll add `openssl rand -base64 32` as well!

**Comment by phonedph1** [comment]
If we add the `-C /dev/null` trick to the dnsdist command example wouldn't that solve most issues people have had with making a key too?

**Comment by rgacogne** [comment]
> If we add the `-C /dev/null` trick to the dnsdist command example wouldn't that solve most issues people have had with making a key too?

Yes and no, I understand some people are generating the configuration on a machine where dnsdist is not installed. But I'll add it as well!

**Comment by rgacogne** [comment]
Done.

**Review by Habbie — APPROVED** [review]

**Pull request merged**
