### PR TITLE
The refresh verification should be added to the negcache getRootNXTrust() function.

### PR DESCRIPTION
**Pull request by zjs604381586**
### Short description

When the qname of the domain name resolution request is an illegal and non-existent top-level domain, the root domain "." will return the response result of nxdomain. When the TTL of 3600s expires, if the resolution request is made again, and this resolution request triggers For the stale function, the asynchronous task generated at this time will not go out of the network and be requested again, because the stale function adds a TTL of 30 seconds and directly hits the cache in the **getRootNXTrust()** function and returns it. The expectation is that asynchronous tasks can be parsed out of the network. Therefore, the judgment logic of refresh and stale should be added when searching the cache of **negcache**.

         // We have something
          if (now.tv_sec < ni->d_ttd && !(refresh && ni->d_servedStale > 0)) {
            ne = *ni;
            moveCacheItemToBack<SequenceTag>(content->d_map, ni);
            return true;
          }

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
I wonder if it's possible to call `get(...)` in `getRootNXTrust()`, so we don't have to duplicate the refresh and serve-stale logic.

**Comment by zjs604381586** [comment]
> I wonder if it's possible to call `get(...)` in `getRootNXTrust()`, so we don't have to duplicate the refresh and serve-stale logic.

Calling the **get** function in the **getRootNXTrust** function can reduce some code redundancy, but it will add some additional judgment logic, which will make it complicated for people to understand, and it feels like the single responsibility principle of the function will be lost.

**Comment by omoerbeek** [comment]
I think I disagree, the diff I uploaded looks simpler that the alternative.
[x.diff.txt](https://github.com/PowerDNS/pdns/files/12991333/x.diff.txt)

**Comment by zjs604381586** [comment]
> I think I disagree, the diff I uploaded looks simpler that the alternative. [x.diff.txt](https://github.com/PowerDNS/pdns/files/12991333/x.diff.txt)

I checked the logic before and after the modification. The modification looks good and the code is very concise.

**Comment by omoerbeek** [comment]
OK, I'll make a PR from the attached diff soon.

**Comment by omoerbeek** [comment]
Superseded by #13409

**Pull request closed without merging**
