### PR TITLE
Issue #4475: Return absolute values from MySQL to work around serial overflow

### PR DESCRIPTION
**Pull request by opeter**
What about using the database (in my case MySQL) to do the sanatizing by an abs() envelope?

Any non-positive number or string will be returned as 0 and overwritten with the current timestamp by the daemon.

### CODE REVIEW

**Comment by rgacogne** [comment]
I'm not sure we want to silently ignore invalid serial values, especially at the database level, since it would prevent any chance of reporting that something is wrong.

**Comment by opeter** [comment]
It would be ignored, yes, but since the absolute value of an invalid/negative/whatever entry would be 0, it will be overwritten during the next run with a fine value (certainly current unix timestamp) and everything will be alright - no crash, no additional code needed.

**Comment by zeha** [comment]
Can we please not do this? Is there an issue that explains the actual problem so another fix can be found?

**Comment by opeter** [comment]
@zeha Somehow we ended up with negative values for last_check and notified_serial in our database.  I do not have an explanation for this but the server process ended up with a crash / serial overflow.
To be honest, the fix of the overflow within the code definitely exceeds my knowledge of C++ so gave this PR a try.
The content in our database is quiet old (started ~2005) and it is not guaranteed that something besides PowerDNS inserted bad values into the tables, so this might not be an issue either.

We were able to fix the problem itself by updating negative values to 0.

The issue along with he PR can both be omitted.

**Comment by Habbie** [comment]
This just hides problems. Not doing this.

**Pull request closed without merging**
