### PR TITLE
Allow setting notify_allowed in Recursor API for forwarded zones

### LINKED ISSUE #14116: Recursor: Allow setting notify_allowed when creating zone with API
- Program: Recursor
 - Issue type: Feature request

### Short description
I'm not sure if this would be considered a bug or feature request.  Currently when creating a new forwarding zone on Recursor using the API, setting `notify_allowed` has no effect.  It looks to be hard-coded in the webserver.  Also, the current setting is not shown when viewing zones using the API.

### Usecase
I would like to create forwarding zones using the API, and have `notify_allowed` set to true to allow clearing the zone cache by sending a NOTIFY.  I realize the cache can be cleared using the cache manipulation API endpoint, but I would prefer to make it automatically clear when the Authoritative server it is forwarding to receives a NOTIFY.  So the Authoritative server (set up as Secondary) receives a NOTIFY and does an AXFR, and also using `forward-notify` setting it forwards the NOTIFY to the Recursor telling it to clear cache for that zone.

### Code Reference
https://github.com/PowerDNS/pdns/blob/5e386641f208cf843e40094269e12de4e84170c5/pdns/recursordist/ws-recursor.cc#L278-L288

Please let me know if there is a reason this should not be an option.  Thanks!

### PR DESCRIPTION
**Pull request by bakern**
Closes #14116

### Short description
Allows setting `notify_allowed` when adding forwarded zones through the Recursor API.  This works with the new YAML settings and the old-style settings.  If `notify_allowed` is not sent or is set to false, the behavior is unchanged.  If `notify_allowed` is set to true the Recursor will allow NOTIFY to clear cache for the given zone.

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by omoerbeek** [comment]
Hello, thanks for the PR. I'm wondering about the old config case. I do not see the code that handles notify_allowed for that I'll try to test soon.

**Comment by omoerbeek** [comment]
I was misdiagnosing earleir, theer is code to handle notify, also for ald-style configs.
Added one commit to make sure notify_allowed flag is also represented in zones objects returned. 
Before merging, this PR should get regression tests.

**Comment by bakern** [comment]
Thanks @omoerbeek!  

I compiled and tested with your change, that is very helpful.  One last thing I was wondering, should we also add the `notify_allowed` flag to the /zones endpoint when listing all zones, or is that too much detail for that endpoint?

> Before merging, this PR should get regression tests.

Please let me know if there is anything I need to do for this.

**Comment by omoerbeek** [comment]
Added simple test and rebased.

**Review by omoerbeek — APPROVED** [review]

**Pull request merged**
