### PR TITLE
fix ldap-strict autoptr feature, including a test

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Habbie** [comment]
Fixes #3165

**Comment by zeha** [comment]
> do we need to init m_qtype in ctor

No. Calling ::get before ::lookup is wrong and broken, so having that uninit' is fine. (Actually, gsql would deref a nullptr in that path...)

**Comment by Habbie** [comment]
Ready for review.

**Comment by zeha** [comment]
lgtm

**Pull request merged**
