### PR TITLE
Replace include guard ifdef/define with pragma once

### PR DESCRIPTION
**Pull request by zeha**
### Short description
To quote a great mind:
```
// it is 2012, deal with it
```

Happy 2019 holidays!

In some files this also adds the license header.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by rgacogne** [comment]
Travis failure is unrelated (see https://github.com/PowerDNS/pdns/pull/8632).

**Comment by Habbie** [comment]
@omoerbeek @rgacogne any opinion on when to merge this to master? I'm fine with any time as soon as I've branched auth-4.3 which I should have done at beta1 but have not done yet because it would mean doing around 30 backports at this point..

**Comment by rgacogne** [comment]
The sooner the better, I guess? I don't expect any issue with this PR, and the potential for conflicts seems limited even though it touches a lot of files.

**Comment by Habbie** [comment]
> The sooner the better, I guess? I don't expect any issue with this PR, and the potential for conflicts seems limited even though it touches a lot of files.

That's true, and any conflicts will be super easy to resolve. Might as well get it into auth-4.3 then.

@zeha want to fix the conflicts? :)

**Comment by zeha** [comment]
@Habbie Conflicts fixed.

**Pull request merged**
