### PR TITLE
Pkg breaks fix

### PR DESCRIPTION
**Pull request by pieterlexis**
@zeha ?

### CODE REVIEW

**Comment by zeha** [comment]
Unfortunately this is not supposed to work (see deb-control(5)). Maybe just throw out the Breaks/Conflicts on master?

**Comment by pieterlexis** [comment]
I don't read that in the manpage, I only see "The syntax of Depends, Pre-Depends, Recommends and Suggests fields is a list of groups of alternative packages. Each group is a list of packages separated by vertical bar (or 'pipe') symbols, '|'. The groups are separated by commas. Commas are to be read as 'AND', and pipes as 'OR', with pipes binding more tightly. Each package name is optionally followed by a version number specification in parentheses. ".

I'm currently building a test package to check this.

**Comment by zeha** [comment]
Further down it says:

The  syntax  of  Breaks,  Conflicts, Replaces and Provides is a list of package names, separated by commas (and optional whitespace).  In the Breaks and Conflicts fields, the comma should be read as `OR'. An optional version can also be given with the same syntax as above for the Breaks, Conflicts and Replaces fields.

(Now that I'm re-reading it, I don't know what this means.)

**Comment by pieterlexis** [comment]
I'd say that `pkg1 (<<0.1) AND pkg1 (>> 3.4) AND pkg2` is a valid thing in this syntax. But yes, the manpage is vague.

**Comment by zeha** [comment]
Ah, I think the man pages says there's no pipe syntax, and everything is OR.

**Comment by pieterlexis** [comment]
nope, this breaks in all kinds of ways :(... will remove

**Pull request merged**
