### PR TITLE
Do not use sqlite3_trace as it is unreliable

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by ahupowerdns** [comment]
looks good, any reference to why it is unreliable? I can't find anything about it.

**Comment by Habbie** [comment]
I generally find it hard to believe.

**Comment by cmouse** [comment]
Well @Habbie raised issue. I will take this with sqlite3 devs soon but as interim measures this is only thing i was able to make reliably show executed sqls

**Comment by ahupowerdns** [comment]
if this patch solves an issue for you I'm all for it! I thought this was theoretical. "The callback function registered by sqlite3_trace() is invoked at various times when an SQL statement is being run by sqlite3_step(). The sqlite3_trace() callback is invoked with a UTF-8 rendering of the SQL statement text as the statement first begins executing. Additional sqlite3_trace() callbacks might occur as each triggered subprogram is entered. The callbacks for triggers contain a UTF-8 SQL comment that identifies the trigger.
" may in any case not mean what we want btw.

**Comment by cmouse** [comment]
After discussing this issue on SQLite3 mailing list I am under the impression that this is a bug indeed in sqlite3. They provided me a patch that semi-fixed this issue, but it's not in road map or anything to fix it at the moment.

**Pull request merged**
