### PR TITLE
auth: fetch all metadata at once

### PR DESCRIPTION
**Pull request by mind04**
### Short description
Fetch all metadata at once when a query is being answered. This will reduce the number of backend/database queries by roughly 20%.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
> Looks great, my only worry is that a backend could implement `getDomainMetadata()` without implementing `getAllDomainMetadata()`, but given that this is required to work properly with several `pdnsutil` commands it's probably unlikely.

Perhaps we could (not necessarily now) remove `getDomainMetadata` from all backends, and implement it in `DNSBackend` on top of `getAllDomainMetadata` (which all backends then need to start supporting). Then your surprise can never happen.

**Comment by zeha** [comment]
I agree that we should remove getDomainMetadata soon, then.

**Comment by mind04** [comment]
I'm against backporting to 4.3.x The change in behaviour is too big for a minor release.

**Comment by zeha** [comment]
Right.

**Pull request merged**
