### PR TITLE
auth: send YXDOMAIN for too long DNAME synth

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Closes the auth-part of #9740

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
The tests are super unhappy.

**Comment by pieterlexis** [comment]
> The tests are super unhappy.

This PR may not be as finished as I thought it would be

**Comment by Habbie** [comment]
Can you rebase this please?

**Comment by Habbie** [comment]
Rebased

**Pull request merged**
