### PR TITLE
New recursor documentation (for 4.1 and up)

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description

This documentation project is a convert/rewrite of the existing documentation to sphinx/restructured text. The pros of this approach:

 * Finally a split between the Authoritative and Recursor docs
 * Documentation sources live in the recursordist directory
 * Inter-document linking is easier
 * The Lua Objects [can be concisely be described](https://doc.powerdns.com/recursor/lua-scripting/dnsname.html#the-dnsname-object)
 * The API documentation is also [more concise](https://doc.powerdns.com/recursor/common/api/endpoint-servers-config.html)
 * [PDF output](https://doc.powerdns.com/recursor/PowerDNS-Recursor.pdf)
 * Webpages for the manpages [look better](https://doc.powerdns.com/recursor/manpages/rec_control.html)
 * Sphinx is more extensible than mkdocs (no more perl, sed etc. hacks)
 * Website is static, but with a [working search](https://doc.powerdns.com/recursor/search.html?q=cache&check_keywords=yes&area=default)

A build of the current documentation can be found [here](https://doc.powerdns.com/recursor) and the PDF is [here](https://doc.powerdns.com/recursor/PowerDNS-Recursor.pdf). These URLs will probably become the canonical URLs.

Comments about:

 * Style
 * Language
 * Structure
 * Theme
 * Anything else

are welcome

Point of discussion:

* Do we want to include parts of the docs in the tarball (doc sources, PDF, html)?
* Do we want to remove the markdown docs for the recursor, or just but a marker on it with "for the latest (4.1) documentation see here)? The new docs are for 4.0 and up any way (4.1 changes have been marked as such)

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by jpmens** [comment]
I feel as though the `<HR>` which underlines a setting belongs, optically, above the setting. In the following screenshot, the red setting seems to belong to the description above it.


jmbp-3707

Maybe I just need new spectacles.

**Comment by pieterlexis** [comment]
would it help is the settings were not in a mono-spaced red font?

**Comment by jpmens** [comment]
I don't believe so. Au contraire: I'm all for a mono-spaced font for settings and things people type in.

**Comment by pieterlexis** [comment]
and here I was hoping not to edit css ;). I'll see what I can do

**Comment by jpmens** [comment]
This example, from the same documentation, works for me:

jmbp-3708

Here the individual setting clearly marks off a "section".

**Comment by jpmens** [comment]
BTW, to add insult to injury: it says `"DNSQuestion. data"` on that page, i.e. too many spaces in so
me of the settings. Consider this a bug report. :-)

**Comment by pieterlexis** [comment]
I made the font size match the header, I think this works:

**Comment by jpmens** [comment]
Much better

**Comment by Habbie** [comment]
> Do we want to include parts of the docs in the tarball (doc sources, PDF, html)?

I don't see the need.

**Comment by Habbie** [comment]
> Do we want to remove the markdown docs for the recursor, or just but a marker on it with "for the latest (4.1) documentation see here)? The new docs are for 4.0 and up any way (4.1 changes have been marked as such)

Either keep the 4.0 around, or make sure links redirect correctly (including anchors, somehow).

**Comment by pieterlexis** [comment]
> > Do we want to include parts of the docs in the tarball (doc sources, PDF, html)?
> I don't see the need.

I pondered this yesterday, it would be neat though to have docs for the exact version in the tarball for reference (this will also make it easier on the distros, as they can just include the docs in /usr/share/docs)

**Comment by pieterlexis** [comment]
Status: 

* All relevant content has been migrated.
* A new builder has been configured to generate and upload the docs.

TODO

* Put a link on the current docs for the recursor to new one.
* Put a link on the 3.X docs to these latest docs

**Pull request merged**
