### PR TITLE
Fix No SOA on ALIAS record types

### LINKED ISSUE #4556: No SOA on ALIAS record types - pdn recursor
Hopefully someone can help here - not sure if this is expected or not.

Im using pdns auth and rec. 

My pdns server is authoritative for the domain foo.mydomain.net and i am using the ALIAS record type to point to an external hostname on akamai. The problem im having is when i request an IPv6 record no SOA value is returned. 

```
dig foo.mydomain.net @localhost AAAA

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> foo.mydomain.net @localhost AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5163
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;foo.mydomain.net.      IN      AAAA

;; Query time: 31 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 11 06:47:06 UTC 2016
;; MSG SIZE  rcvd: 53`
```

however you can see in the logs that the akamai SOA value is returned its just not passed through to the client requesting.

```
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: 2 [1/1] question for 'XXX.com.akadns.net|AAAA' from 172.17.0.3
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Wants NO DNSSEC processing in query for AAAA
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Looking for CNAME cache hit of 'XXX.com.akadns.net|CNAME'
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: No CNAME cache hit of 'XXX.com.akadns.net|CNAME' found
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: No cache hit for 'XXX.com.akadns.net|AAAA', trying to find an appropriate NS record
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Cache consultations done, have 1 NS to contact
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net.: Nameservers: <empty>(7.50ms)
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Domain has hardcoded nameservers
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Resolved '.' NS (empty) to: 10.88.0.1, 10.88.0.2
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Trying IP 10.88.0.1:53, asking 'XXX.com.akadns.net|AAAA'
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: Got 2 answers from (empty) (10.88.0.1), rcode=0 (No Error), aa=0, in 21ms
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: accept answer 'akadns.net|SOA|internal.akadns.net. hostmaster.akamai.com. 1476167936 90000 90000 90000 180' from '.' nameservers? 2 YES! - This answer was received from a server we forward to.
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: OPT answer '.' from '.' nameservers
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: determining status after receiving this packet
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: got negative caching indication for 'XXX.com.akadns.net|AAAA'
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: [1] XXX.com.akadns.net: status=noerror, other types may exist, but we are done (have negative SOA) 
Oct 11 06:41:02 09d8cbc01d94 pdns_recursor[1981]: 2 [1/1] answer to question 'XXX.com.akadns.net|AAAA': 0 answers, 0 additional, took 1 packets, 21.317 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
```

If i request a record that passes straight through the recursor then there are no problems - the SOA is returned.

```
dig github.com @localhost AAAA

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> github.com @localhost AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19653
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.com.                    IN      AAAA

;; AUTHORITY SECTION:
github.com.             30      IN      SOA     ns1.p16.dynect.net. hostmaster.github.com. 1474079943 3600 600 604800 60

;; Query time: 18 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 11 06:52:34 UTC 2016
;; MSG SIZE  rcvd: 104
```

This only happens when using the ALIAS record type, other records are fine.

thanks.

### PR DESCRIPTION
**Pull request by tonysimpson**
This fixes #4556.

### CODE REVIEW

**Comment by Habbie** [comment]
Neat, roughly the approach I had in mind!

@gitshaw are you able to test this patch?

**Comment by gitshaw** [comment]
testing now

**Comment by gitshaw** [comment]
Looking good!! Results from DIG as expected.

```
root@6f7542676c2a:/# dig stg1.oogway.mydomain.net AAAA

; <<>> DiG 9.9.5-9+deb8u7-Debian <<>> stg1.oogway.mydomain.net AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24631
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;stg1.oogway.mydomain.net.      IN      AAAA

;; AUTHORITY SECTION:
stg1.oogway.mydomain.net. 84600 IN      SOA     ns1.oogway.mydomain.net. postmaster.oogway.mydomain.net. 2016101405 86400 1800 3600000 21600

;; Query time: 27 msec
;; SERVER: 172.17.0.2#53(172.17.0.2)
;; WHEN: Wed Oct 19 16:14:56 UTC 2016
;; MSG SIZE  rcvd: 104
```

**Comment by Habbie** [comment]
Is stg1 in fact your apex?

**Comment by Habbie** [comment]
@tonysimpson would you also like to submit a test for this?

**Comment by tonysimpson** [comment]
@Habbie I'd like to get a fix for this merged ASAP so if a test would help then I can have a go at writing one tomorrow, I'm not an expert on DNS or C++ though so I'm making no promises about quality ;)

**Comment by Habbie** [comment]
@gitshaw can you please stop changing your real domain to mydomain.net? We cannot trust edited output.

**Comment by gitshaw** [comment]
The output is unedited. although its a domain i do not own, its a made up domain that is in my zone file and served while testing. 

```
root@6f7542676c2a:/usr/local/etc# cat oogway.mydomain.net.zone 
;
; Zone file for oogway.mydomain.net
;
;
oogway.mydomain.net. 84600      IN      SOA     ns1.oogway.mydomain.net.      postmaster.oogway.mydomain.net. (
                        2016101405      ; Serial Number (date YYYYMMDD++)
                        86400           ; Refresh (24 hours)
                        1800            ; Retry (1/2 hour)
                        3600000         ; Expire (42 days)
                        21600)          ; Minimum (6 hours)
                        IN      NS      ns1.oogway.mydomain.net.

@                       IN      A       192.168.0.1

ns1                     IN      A       172.17.0.4
stg1                    IN      ALIAS   stg1.oogway.jpsnetworks.net.
```

Also stg1. is not the apex of the domain - we are using the ALIAS record in a slightly different way than what it was intended for however we expect the same outcome.

thanks.

**Comment by Habbie** [comment]
In that case the returned SOA is wrong, it should start with `oogway`.

**Comment by Habbie** [comment]
@tonysimpson yes, a test always helps - especially as from @gitshaw's results it appears something is wrong

**Comment by tonysimpson** [comment]
@Habbie I could create a test based on pdns/regression-tests/tests/alias-address/ but I need a DNS server to ALIAS to which doesn't have AAAA or A records, I'm unsure about using public DNS servers in these tests does anyone have any advice?

**Comment by gitshaw** [comment]
I included the SOA in my zone file paste above;

```
oogway.mydomain.net. 84600      IN      SOA     ns1.oogway.mydomain.net.      postmaster.oogway.mydomain.net. (
                        2016101405      ; Serial Number (date YYYYMMDD++)
                        86400           ; Refresh (24 hours)
                        1800            ; Retry (1/2 hour)
                        3600000         ; Expire (42 days)
                        21600)          ; Minimum (6 hours)
```

What do you feel is wrong with my output from the dig.

thank you.

**Comment by Habbie** [comment]
```
stg1.oogway.mydomain.net. 84600 IN      SOA     ns1.oogway.mydomain.net. postmaster.oogway.mydomain.net. 2016101405 86400 1800 3600000 21600
```

should be
```
oogway.mydomain.net. 84600 IN      SOA     ns1.oogway.mydomain.net. postmaster.oogway.mydomain.net. 2016101405 86400 1800 3600000 21600
```

**Comment by gitshaw** [comment]
Ah yes you are correct! @tonysimpson il speak to your offline about this.

**Comment by gitshaw** [comment]
Ok this is now giving me the correct host in the SOA Auth section.

```
root@6f7542676c2a:/# dig stg1.oogway.mydomain.net AAAA @localhost

; <<>> DiG 9.9.5-9+deb8u7-Debian <<>> stg1.oogway.mydomain.net AAAA @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25254
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;stg1.oogway.mydomain.net.      IN      AAAA

;; AUTHORITY SECTION:
oogway.mydomain.net.    21600   IN      SOA     ns1.oogway.mydomain.net. postmaster.oogway.mydomain.net. 2016101405 86400 1800 3600000 21600

;; Query time: 26 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Oct 24 13:54:14 UTC 2016
;; MSG SIZE  rcvd: 104
```

Peter what do you think of the updated code.

Thanks

**Comment by Habbie** [comment]
Looks fine at a quick glance!

**Comment by Habbie** [comment]
@tonysimpson for the test, a nice and stable target is `ipv4only.arpa` which has A but not AAAA. `root-servers.net` has no A and no AAAA.

**Comment by gitshaw** [comment]
Thanks peter - a glance is good enough for me lol! il let tony carry on with the test so we can check further. ;-)

**Comment by tonysimpson** [comment]
@Habbie thanks I'll write some tests :)

**Comment by Habbie** [comment]
Any progress on testing?

**Comment by pieterlexis** [comment]
ping!

**Comment by Habbie** [comment]
ping! This branch is conflicted and no tests have appeared. Also please be aware that the IETF dnsop ANAME draft will soon get a (much more correct than ALIAS) implementation in PowerDNS soon and thus this work may not be so relevant any more.

**Comment by tonysimpson** [comment]
I do not have time to do this. That may change in the future but it seems unlikely.

**Pull request closed without merging**
