### PR TITLE
Add -Werror=format-security and -D_GLIBCXX_ASSERTIONS on CircleCI

### LINKED ISSUE #7986: Build with -D_GLIBCXX_ASSERTIONS on Circle CI
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description
It would be nice to build and then run our tests with `-D_GLIBCXX_ASSERTIONS` enabled on Circle CI. This turns on cheap range checks for C++ arrays, vectors, and strings and helped uncovered several questionable uses of these containers in the past.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Closes #7986.

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
The dnsdist build (which is the only one that runs on Debian buster), config.log:
```
configure:3715: checking whether the C compiler works
configure:3737: gcc -O1 -Werror=vla -Werror=format-security   conftest.c  >&5
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
cc1: some warnings being treated as errors
configure:3741: $? = 1
configure:3779: result: no
configure: failed program was:
```

**Comment by Habbie** [comment]
Locally tested: `CFLAGS="-O1 -Werror=vla -Wformat -Werror=format-security" CXXFLAGS="-O1 -Werror=vla -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS"` - somehow CXXFLAGS does not need `-Wformat`.

**Comment by Habbie** [comment]
I've taken the liberty of pushing `-Wformat` for dnsdist CFLAGS in two places.

**Comment by rgacogne** [comment]
I indeed missed the fact that `-Wformat-security` is useless without `-Wformat`, so I just pushed a fix adding `-Wformat=2` for all products, since it should not hurt anyway. I also added it in `CXXFLAGS` since I guess that it currently works only because `CFLAGS` are passed to our C++ unit compilation, and that seems brittle.

**Pull request merged**
