### PR TITLE
stubresolver: Improve locking

### PR DESCRIPTION
**Pull request by cmouse**
### Short description
Improves locking in stub resolver to avoid race conditions.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by goestreicher** [comment]
So I couldn't reproduce the crash with this patch and *without* #6495, but could still reproduce it without any of them. So I guess it works for me :)

**Comment by goestreicher** [comment]
Additionally I've also tested this patch alone on Travis, where the job failed every time, and it now works.

**Comment by rgacogne** [comment]
@cmouse Ping! Do you disagree with my previous comment? I might be wrong, in which case I'd be happy to merge this :-)

**Comment by cmouse** [comment]
I'll revisit the locking code, it will take few days.

**Comment by cmouse** [comment]
Hoping it'll finally compile nicely.

**Pull request merged**
