### PR TITLE
Remove serializeSOAData, refactor calculate/edit/increaseSOA

### LINKED ISSUE #4515: AXFR from pdns auth returns different serial values in first and last SOA record
My setup:

Hidden powerdns master, running 0.0.1279g844b72d-1pdns.xenial. Two slaves running ancient nsd. 
Discovered this morning that both slaves returned SERVFAIL.

It turnes out that powerdns returns two different serial values in an AXFR request for the SOA records.

On the hidden master:

```
dig soa finux.nl @localhost -p 5300 +short
ns1.8rs.nl. henkjan.finux.nl. 2016092904 28800 7200 604800 3600
root@services:/var/log# pdnsutil increase-serial finux.nl                                                                  
SOA serial for zone finux.nl set to 2016092903
root@services:/var/log# dig soa finux.nl @localhost -p 5300 +short
ns1.8rs.nl. henkjan.finux.nl. 2016092905 28800 7200 604800 3600
```

On a slave:

```
root@sterling:/var/log# dig AXFR finux.nl @213.154.229.62 -p 5300|grep SOA
finux.nl.               600     IN      SOA     ns1.8rs.nl. henkjan.finux.nl. 2016092905 28800 7200 604800 3600
finux.nl.               600     IN      RRSIG   SOA 13 2 600 20161013000000 20160922000000 28352 finux.nl. 2dJAdgiuQ88PaBCBdImIwfF+esDRGDfr1w+UgQYykaZDPo6NNmg1W/jw eaDOt3hg2WPidlcl8N62uIuqYTh/MQ==
finux.nl.               3600    IN      NSEC    enoch.finux.nl. A NS SOA MX AAAA RRSIG NSEC DNSKEY
finux.nl.               600     IN      SOA     ns1.8rs.nl. henkjan.finux.nl. 2016092907 28800 7200 604800 3600
```

### PR DESCRIPTION
**Pull request by zeha**
This also fixes #4515 and #2377.

### CODE REVIEW

**Comment by zeha** [comment]
porkipin on IRC pointed out that SOA-EDIT "NONE" is documented but not implemented in the old code. This PR ... should probably fix that, too.

**Comment by Habbie** [comment]
This branch has conflicts that must be resolved.

**Comment by zeha** [comment]
Rebased; hoping it "just works" now :)

**Comment by zeha** [comment]
Recursor fails to build, which I believe is an issue on master, not introduced by this PR

**Comment by Habbie** [comment]
Looks ok at very quick review, will do a longer one when #4545 settles.

**Comment by zeha** [comment]
Rebased, compiled once.

**Comment by zeha** [comment]
Rebased.

**Comment by Habbie** [comment]
Still looks ok at a semi-quick review, a second look would be appreciated.

**Comment by zeha** [comment]
Rebased once more.

**Comment by ahupowerdns** [comment]
looks good, but let us also not backport this.

**Pull request merged**
