### PR TITLE
auth: Ensure that pdns can read pdns.conf when upgrading from an older package

### LINKED ISSUE #8333: PowerDNS fails to start, Unable to open /etc/powerdns/pdns.conf
- Program: pdns-backend-mysql/unknown,now 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic amd64  
pdns-server/unknown,now 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic amd64
 - Issue type: Bug report

### Short description
After updating to above version powerdns fails to start
### Environment

 - Operating system: ubuntu 18.04
 - Software version: master
 - Software source: PowerDNS repository

### Steps to reproduce
Upgrade pdns+backend-mysql Master version: 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic 
### Expected behaviour
Continued using working running config

### Actual behaviour
-- Unit pdns.service has begun starting up.
Sep 22 19:06:19 auth1 pdns_server[18159]: Sep 22 19:06:19 Unable to open /etc/powerdns/pdns.conf
Sep 22 19:06:19 auth1 pdns_server[18159]: Unable to launch, no backends configured for querying
Sep 22 19:06:19 auth1 systemd[1]: pdns.service: Main process exited, code=exited, status=99/n/a
Sep 22 19:06:19 auth1 systemd[1]: pdns.service: Failed with result 'exit-code'.
Sep 22 19:06:19 auth1 systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
### Other information

/etc/powerdns/pdns.conf
```lua
include-dir=/etc/powerdns/pdns.d
setgid=pdns
setuid=pdn
```

/etc/powerdns/pdns.d/pdns.conf
```lua
allow-axfr-ips=127.0.0.0/8,::1
allow-dnsupdate-from=127.0.0.0/8,::1
allow-notify-from=0.0.0.0/0,::/0
allow-unsigned-notify=yes
allow-unsigned-supermaster=yes
also-notify=[]
any-to-tcp=yes
api-key=
api=yes
axfr-lower-serial=yes
carbon-instance=auth
carbon-interval=30
carbon-namespace=pdns
carbon-ourname=auth1
carbon-server=37.252.122.50
config-name=auth1.fi.matrix.rocks
daemon=yes
default-ksk-algorithm=ECDSAP384SHA384
default-ksk-size=0
default-soa-mail=
default-soa-name=ns0.dns.matrix.rocks
default-ttl=3600
default-zsk-algorithm=ECDSAP384SHA384
default-zsk-size=0
disable-axfr=no
disable-syslog=no
distributor-threads=1
dname-processing=no
dnsupdate=yes
domain-metadata-cache-ttl=60
edns-subnet-processing=yes
expand-alias=yes
forward-dnsupdate=yes
forward-notify=[]
launch=gmysql
local-address-nonexist-fail=yes
local-address=127.0.0.1,
local-ipv6-nonexist-fail=yes
local-ipv6=
local-port=53
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
loglevel=4
master=yes
prevent-self-notification=yes
query-local-address6=::
query-local-address=0.0.0.0
resolver=
reuseport=no
send-signed-notify=yes
server-id=
setgid=pdns
setuid=pdns
slave-renotify=yes
slave=yes
soa-expire-default=604800
soa-minimum-ttl=60
soa-refresh-default=10800
soa-retry-default=3600
tcp-control-port=53000
tcp-control-range=127.0.0.0/8,
tcp-control-secret=
tcp-fast-open=1
version-string=anonymous
webserver-address=0.0.0.0
webserver-allow-from=
webserver-port=8081
webserver=yes
write-pid=yes
xfr-max-received-mbytes=0
```

### PR DESCRIPTION
**Pull request by mnordhoff**
### Short description
Fixes #8333, at least mostly. The Debuntu packages made sure that `pdns.conf` was readable in fresh installations, but not necessarily when upgrading.

This ensures that, IFF the file was owned by `root:root`, it's adjusted to be readable by `pdns`. This should help almost all users, while not harming many users with unusual configurations.

This also changes the default mode from `660` to `640` and the ownership from `pdns:root` to `root:pdns`.
 
This supersedes #8329 and #8330.

Note that the files in `/etc/powerdns/pdns.d/` are not adjusted, because they were typically world-readable anyway.

I'm not particularly sure that this is the right way to go about it, or that the sh is safe.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mnordhoff** [comment]
Criticizing my own PR:

* It's not idempotent if it gets killed in the middle, after `chown` runs but before `chmod` runs.

* If it used `pdns:root`, it wouldn't be necessary to mess with permissions at all, since it's safe to assume the file can be read by its own user.

**Comment by pieterlexis** [comment]
> If it used pdns:root, it wouldn't be necessary to mess with permissions at all, since it's safe to assume the file can be read by its own user.

tbf, pdns:root makes more sense to me

**Comment by omoerbeek** [comment]
Hmm, I missed this one when I amended #8329 
I'll close #8329  and #8330. If @pieterlexis  thinks this is ok,let's make sure rec and dnsdist also get a similar treatment.

**Comment by omoerbeek** [comment]
> Hmm, I missed this one when I amended #8329
> I'll close #8329 and #8330. If @pieterlexis thinks this is ok,let's make sure rec and dnsdist also get a similar treatment.


> > If it used pdns:root, it wouldn't be necessary to mess with permissions at all, since it's safe to assume the file can be read by its own user.
> 
> tbf, pdns:root makes more sense to me

After a short discussion it was decided that root:pdns is the generally accepted way.

**Pull request merged**
