### PR TITLE
enable structured logging by default in systemd

### PR DESCRIPTION
**Pull request by SjonHortensius**
when running as a systemd service - we want to enable structured logging, also allows removing some now-outdated settings

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

would you want me to propagate this change on other places as well?

### CODE REVIEW

**Comment by omoerbeek** [comment]
Well, that is a question of taste/opinion. I you prefer the journal stream it is easy to enable it, I do not want to enable it by default at this moment.

**Comment by SjonHortensius** [comment]
I'm not sure I follow. I modified the `.service`, which will only be used when running under systemd implying the journal stream is used anyway. The current output is already in this "structured" output but without the journal parsing it properly - how is this a matter of taste?
You literally say *The structured logging info in journal mode is pretty hard to read for humans* so why would you want to output it unparseable by default?

**Comment by omoerbeek** [comment]
I see your confusion. In both case structured logging infomration is stored.
The default is now to output all structured logging information in a text line containing a sequence of key=value pairs. I find that easy, as all information is there without the need to dig deeper with `journalctl`. This is also the same format as is logged to `syslogd` on other platforms or when not using `systemd`.

If we change this to journal format, only the `msg` part is shown by default by `journalctl`. It might be easier to read, but it also contains less information as the details are only shown if you specify extra `journalctl` arguments.

**Comment by SjonHortensius** [comment]
I applaud the structured logging and unification across logging backends but I'm not sure why you prefer replacing easy to read journal output with hard to read output, while all it takes is a setting to make the journal parse the field, allowing the user to output it in any way they like (for example, you could use `journalctl --output json` to have 'all information there without the need to dig deeper')

I'd be interested in other people's opinions on this. Your comments seem pretty conflicting

> structured logging info in journal mode is pretty hard to read for humans

> I find that easy, as all information is there

**Comment by omoerbeek** [comment]
You might want to read https://blog.powerdns.com/2022/10/03/structured-logging-in-powerdns-recursor/
It gives some background info.
When I introduced journal mode, it was the default. Within a few days I received complaints from a power user running the master branch, so I decided the keep the text line format as default. See #11705, #11706 and #11709

**Comment by SjonHortensius** [comment]
Okay, I see your predicament. I did notice the issue you mention with a few other messages as well, where `msg` is no longer unique and thus less useful without the details. Personally I'd prefer the structured logging to provide extra information (when necessary) which is why I think you should only log `msg` but ensure important details aren't moved to 'invisible' fields. 

I think the current solution goes against the very idea it's supposed to implement but I'm fine with changing this flag myself. Maybe in the future the default can be changed, hopefully after the `msg` has a better balance of being informational on its own.

Thanks for the detailed explanation!

**Comment by omoerbeek** [comment]
In general agreed; it will take some time to arrive there though.

**Pull request closed without merging**
