### PR TITLE
 pdnsutil increase-serial: under SOA-EDIT=INCEPTION-EPOCH, bump as if it is EPOCH

### LINKED ISSUE #8218: auth: pdnsutil increase-serial misbehaving under INCEPTION-EPOCH
- Program: Authoritative
 - Issue type: Surprising behaviour

### Short description
With `SOA-EDIT=INCEPTION-EPOCH`, `pdnsutil increase-serial` will bump the serial to the latest inception if necessary, and otherwise increase the existing number by one. Users might expect, instead, that the number is always bumped to the current UNIX time.

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
Fixes #8218.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by zeha** [comment]
Well, maybe this should be done more generally. We have documented this:

```
SOA-EDIT-INCREASE: Change the serial to whatever SOA-EDIT would provide. If what SOA-EDIT provides is lower than the current serial, increase the current serial by 1.
```

At the very least I think this needs a doc update; I'm not sure right now what is the least confusing behaviour.

**Comment by Habbie** [comment]
> Well, maybe this should be done more generally.

I agree, but I wasn't so confident that any other types were doing a surprising thing, so I figured I'd do a narrow fix here and give it some more thought for 4.3.

> `SOA-EDIT-INCREASE: Change the serial to whatever SOA-EDIT would provide. If what SOA-EDIT provides is lower than the current serial, increase the current serial by 1.`

Right, and my PR deviates from that. Then again, we only documented that for rfc2136..

**Comment by zeha** [comment]
> Right, and my PR deviates from that. Then again, we only documented that for rfc2136..

True, but the docs do refer to the rfc2136 rules when explaining related options. I couldn't find a separate explanation for SOA-EDIT-INCREASE in any case.

**Comment by Habbie** [comment]
> True, but the docs do refer to the rfc2136 rules when explaining related options. I couldn't find a separate explanation for SOA-EDIT-INCREASE in any case.

Fair enough. I'll think about how I can make the docs clear on what I did here.

**Comment by Habbie** [comment]
Doc update pushed.

**Pull request merged**
