### PR TITLE
Add support for live login to pkcs11

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by cmouse** [comment]
Ready for review

**Comment by pieterlexis** [comment]
Looks good to me (although wrt to pkcs#11, I trust you). There are no tests though. Is this possible with softshm? Or is this impossible without an actual HSM that allows for login?

**Comment by cmouse** [comment]
Testing is pretty tricky to setup, since it requires timing and stuff. Bsides, there are no tools (yet) to assing keys without storing PIN, so it would require direct database manipulation.

**Comment by pieterlexis** [comment]
Cool, I'll merge this in then. There might be a need for a PKCS#11 page in the docs that describes the feature later imho.

**Comment by cmouse** [comment]
There is one in this pr =)

**Pull request merged**
