### PR TITLE
auth 4.7 minicurl: stop leaking hostlist memory

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
inspired by #12292, but as a much smaller change. Hopefully helps for #12426

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
Packages are building at https://github.com/Habbie/pdns/actions/runs/3942071289

**Review by rgacogne — APPROVED** [review]

**Comment by omoerbeek** [comment]
Previous build expired, currently https://github.com/PowerDNS/pdns/actions/runs/4015891234 is building

**Comment by omoerbeek** [comment]
> Previous build expired, currently https://github.com/PowerDNS/pdns/actions/runs/4015891234 is building

That didn't work out. No idea if and how it is possible to refer to PR branches in a workflow.

**Comment by Habbie** [comment]
> That didn't work out. No idea if and how it is possible to refer to PR branches in a workflow.

I'm not sure you can. I did the previous build by using the workflow on my fork. I'll do that again.

**Comment by Habbie** [comment]
> I'll do that again.

Actually, I'll do it again when somebody who wants to test asks for it :)

**Pull request merged**
