### PR TITLE
Forward-zone NS speed tracking

### PR DESCRIPTION
**Pull request by phonedph1**
### Short description
Fix for #5187 by slightly abusing our current tracking mechanism by stuffing our ComboAddress in as a DNSName and reusing much of shuffleInSpeedOrder.

This also prints a + in the trace log if the query is recursive - much like previous versions did.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by phonedph1** [comment]
Moved this around a bit, only applies to hardcoded nameservers now, not everything (oops). The logging order is a bit more consistent with non-hardcoded nameservers now as well.

**Comment by pieterlexis** [comment]
Hi,

I'm putting this PR on hold for a little until we have landed our syncres refactor in master.

**Comment by phonedph1** [comment]
Is there any interest in this crazy PR? A bit of re-work and it still does work on 4.1.0-rc1. We've also been running it on 4.0.x with no issues.

**Comment by Habbie** [comment]
So the refactor has landed, but now we've done RC1 which means we are very careful. If I have to guess, this PR would be perfect to land (with review) on master once 4.1.0 is out. Certainly the concept of speed tracking for forwarded zones, like we do for zones 'out on the internet' is a good idea.

**Comment by Habbie** [comment]
4.2.0 milestone assigned.

**Comment by aerique** [comment]
@phonedph1 Could you please rebase on master, then I can merge it after another review.

**Comment by phonedph1** [comment]
I ended up in git hell. I'll re-do this pull.

**Pull request closed without merging**
