### PR TITLE
remove 'reverse backend' from core.

### PR DESCRIPTION
**Pull request by mind04**
the logic in this class was backend specific and doe not belong here.

### CODE REVIEW

**Comment by Habbie** [comment]
LMDB no longer relies on this?

**Comment by zeha** [comment]
+1, but `class LMDBBackend` indeed seems to still need this...

**Comment by mind04** [comment]
LMDB maybe need something like this, but... The current status of LMDB is very broken. Locking is a mess. Keys in the db do no longer make sense, as they are incompatible with DNSName. And most other hooks are already gone in pdns core. This is just the removal of some legacy code to make sure we do everything right in lmdb(2) backend. If, a future version of LMDB backend need logic like this it should be located inside the backend and not in core.

**Comment by Habbie** [comment]
:+1:

**Comment by zeha** [comment]
Travis gcc build ICEs, clang passes.

**Pull request merged**
