### PR TITLE
Import Javascript sources for libs shipped with Recursor

### PR DESCRIPTION
**Pull request by zeha**
* d3 v3.3.6
* jquery v1.8.3
* moment v2.9.0
* rickshaw v1.4.6
* underscore v1.8.3

Fixes last missing files in Recursor tarball for #3118.

### CODE REVIEW

**Comment by zeha** [comment]
dnsdist appears to use completely different versions of these libs.

**Comment by pieterlexis** [comment]
@rgacogne is it possible to sync these libraries between the recursor and dnsdist?

**Comment by rgacogne** [comment]
dnsdist has newer versions for every common lib. At a quick glance, the only upgrade that might cause some trouble is jquery 1.8.3 -> 1.12.X.

**Comment by Habbie** [comment]
This is the last open pull for recursor 4.0.0. Can we merge this to get 4.0.0 out the door and deal with dnsdist after that?

**Comment by zeha** [comment]
Not seeing why not. Syncing the lib versions after 4.0.0 is certainly possible :)

**Pull request merged**
