### PR TITLE
Geoip patches 3.4.7

### PR DESCRIPTION
**Pull request by cmouse**
Rollup patch with #2751, #2738 and #2736

### CODE REVIEW

**Comment by pieterlexis** [comment]
if you update the `.travis.yml` based on 1bc5f3a8e9ada9f3a9932dab2ac6ce715a94de8c we also test these changes in 3.4.X.

**Comment by cmouse** [comment]
@lieter can you check I got it right?

**Comment by pieterlexis** [comment]
```
make[3]: Entering directory `/home/travis/build/PowerDNS/pdns/modules/geoipbackend'
  CXX    geoipbackend.lo
geoipbackend.cc:132:89: error: macro "BOOST_FOREACH" passed 3 arguments, but takes just 2
geoipbackend.cc:153:70: error: macro "BOOST_FOREACH" passed 3 arguments, but takes just 2
geoipbackend.cc: In member function â€˜void GeoIPBackend::initialize()â€™:
geoipbackend.cc:132:5: error: â€˜BOOST_FOREACHâ€™ was not declared in this scope
geoipbackend.cc:132:91: error: expected â€˜;â€™ before â€˜{â€™ token
geoipbackend.cc:705:29: error: expected â€˜}â€™ at end of input
geoipbackend.cc:705:29: error: expected â€˜}â€™ at end of input
```

**Comment by cmouse** [comment]
fixed, test suites passed locally.

**Comment by pieterlexis** [comment]
If you'd be so kind to squash this, we can merge it in.

**Comment by cmouse** [comment]
done.

**Pull request merged**
