### PR TITLE
rec: make rec zone files with trailing dot

### PR DESCRIPTION
**Pull request by phonedph1**
### Short description
Without this you get zone files made that don't seem to work as expected.

There is probably a better way to fix this.

Before:
```
{
  "id": "test5.local.",
  "kind": "Native",
  "name": "test5.local.",
  "records": [
    {
      "content": "127.0.53.53",
      "name": "test5.local.test5.local.",
      "ttl": 3600,
      "type": "A"
    },
    {
      "content": "local.zone. hostmaster.test5.local.test5.local. 1 1 1 1 1",
      "name": "test5.local.test5.local.",
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "content": "127.0.53.53",
      "name": "*.test5.local.test5.local.",
      "ttl": 3600,
      "type": "A"
    }
  ],
  "recursion_desired": false,
  "servers": [],
  "url": "/api/v1/servers/localhost/zones/test5.local."
}
```

After:

```
{
  "id": "test6.local.",
  "kind": "Native",
  "name": "test6.local.",
  "records": [
    {
      "content": "127.0.53.53",
      "name": "test6.local.",
      "ttl": 3600,
      "type": "A"
    },
    {
      "content": "local.zone. hostmaster.test6.local. 1 1 1 1 1",
      "name": "test6.local.",
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "content": "127.0.53.53",
      "name": "*.test6.local.",
      "ttl": 3600,
      "type": "A"
    }
  ],
  "recursion_desired": false,
  "servers": [],
  "url": "/api/v1/servers/localhost/zones/test6.local."
}
```

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by phonedph1** [comment]
Future problem: `single_target_ip` isn't documented I don't think.

**Comment by omoerbeek** [comment]
I do not understand yet why your fix produces different output. Will look into this soon.

**Comment by omoerbeek** [comment]
Can you show the REST call you used for testing? Thanks.

**Comment by phonedph1** [comment]
This was based on what someone else was doing earlier in the day but:

```
curl --location --request POST 'http://127.0.0.1:8082/api/v1/servers/localhost/zones' --header 'X-API-Key: s3cret' --header 'Content-Type: text/plain' --data-raw '{
    "kind": "NATIVE",
    "name": "test6.local.", "single_target_ip": "127.0.53.53",
    "recursion_desired": false
}'
```

I think it's because it makes a DNSName and << is toLogString which is either . for root or the name without a trailing dot. This probably only affects the SOA and if you use the undocumented single_target_ip otherwise we'd probably have heard  of issues before?

**Comment by omoerbeek** [comment]
> This was based on what someone else was doing earlier in the day but:
> 
> ```
> curl --location --request POST 'http://127.0.0.1:8082/api/v1/servers/localhost/zones' --header 'X-API-Key: s3cret' --header 'Content-Type: text/plain' --data-raw '{
>     "kind": "NATIVE",
>     "name": "test6.local.", "single_target_ip": "127.0.53.53",
>     "recursion_desired": false
> }'
> ```
> 
> I think it's because it makes a DNSName and << is toLogString which is either . for root or the name without a trailing dot. This probably only affects the SOA and if you use the undocumented single_target_ip otherwise we'd probably have heard of issues before?

I suppose so. I think it is time for a test which includes at least one record and that both checks to produced zone and the json returned. I'll ask around about the ""single_target_ip" g as well.

**Comment by omoerbeek** [comment]
So it looks like the produced auth zone file is also wrong, the name are relative a as in the returned object.
Also, records in the REST call are ignored. This is only relevant for NATIVE (aka auth zones).

**Comment by omoerbeek** [comment]
master branch
```
+ curl -X POST --no-progress-meter -H X-API-Key: otto http://localhost:8083/api/v1/servers/localhost/zones --json {
    "kind": "NATIVE",
    "name": "test.example.", 
    "rrsets" : [
             { "name": "www", "ttl": "600", "type": "A",
               "records": [ {"content": "1.2.3.4" } ]
             } ],
    "recursion_desired": false
}
+ jq
{
  "id": "test.example.",
  "kind": "Native",
  "name": "test.example.",
  "records": [
    {
      "content": "local.zone. hostmaster.test.example.test.example. 1 1 1 1 1",
      "name": "test.example.test.example.",
      "ttl": 3600,
      "type": "SOA"
    }
  ],
  "recursion_desired": false,
  "servers": [],
  "url": "/api/v1/servers/localhost/zones/test.example."
}
```
Produces the above json and the following conmfig and zone file:
```
# Generated by pdns-recursor REST API, DO NOT EDIT
auth-zones+=test.example.=tmp/api-dir/zone-test.example..zone
```
```
; Generated by pdns-recursor REST API, DO NOT EDIT
test.example    IN      SOA     local.zone.     hostmaster.test.example 1 1 1 1 1
```

Note that the zone itself is `test.example.` while the names in the zone are relative. That means that the the SOA records has the name `test.example.test.example.`.
And indeed:
```
[otto@lou:15]$ dig -p 5301 test.example. SOA              

; <<>> dig 9.10.8-P1 <<>> -p 5301 test.example. SOA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 14498
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;test.example.                  IN      SOA

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5301(127.0.0.1)
;; WHEN: Fri Jun 10 09:22:27 CEST 2022
;; MSG SIZE  rcvd: 41

[otto@lou:16]$ dig -p 5301 test.example.test.example. SOA

; <<>> dig 9.10.8-P1 <<>> -p 5301 test.example.test.example. SOA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19001
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;test.example.test.example.     IN      SOA

;; ANSWER SECTION:
test.example.test.example. 3600 IN      SOA     local.zone. hostmaster.test.example.test.example. 1 1 1 1 1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5301(127.0.0.1)
;; WHEN: Fri Jun 10 09:22:32 CEST 2022
;; MSG SIZE  rcvd: 111
```

The PR fixes thsi but adding a dot to the name in the zone file, which also has the consequence of producing the proper JSON, as that gets generated fomr the zone info.
```
; Generated by pdns-recursor REST API, DO NOT EDIT
test.example.   IN      SOA     local.zone.     hostmaster.test.example. 1 1 1 1 1
```
```
+ curl -X POST --no-progress-meter -H X-API-Key: otto http://localhost:8083/api/v1/servers/localhost/zones --json {
    "kind": "NATIVE",
    "name": "test.example.", 
    "rrsets" : [
             { "name": "www", "ttl": "600", "type": "A",
               "records": [ {"content": "1.2.3.4" } ]
             } ],
    "recursion_desired": false
}
+ jq
{
  "id": "test.example.",
  "kind": "Native",
  "name": "test.example.",
  "records": [
    {
      "content": "local.zone. hostmaster.test.example. 1 1 1 1 1",
      "name": "test.example.",
      "ttl": 3600,
      "type": "SOA"
    }
  ],
  "recursion_desired": false,
  "servers": [],
  "url": "/api/v1/servers/localhost/zones/test.example."
}
```

**Review by fredmorcos — APPROVED** [review]

**Pull request merged**
