### PR TITLE
dnsdist: Log the content of webserver's exceptions

### PR DESCRIPTION
**Pull request by rgacogne**

### CODE REVIEW

**Comment by thomas-mangin** [comment]
May 13 16:39:18 pdns1.surfprotect.exa.net.uk dnsdist[5407]: Webserver thread died with exception: Was not able to extract a valid Request from stream

**Comment by Habbie** [comment]
So what are you sending it? ;)

**Comment by rgacogne** [comment]
So we get EOF before the HTTP received parser has a complete HTTP request. I'll bet my money on nothing being sent on the socket at all.

**Comment by thomas-mangin** [comment]
No idea, I "just" have the page refreshing on my browser - I done nothing sir, I am innocent !

**Comment by thomas-mangin** [comment]
Confirmed - telneting to the port and just closing the connection did trigger it: CED harmless.

**Pull request merged**
