### PR TITLE
auth: Always bind the results array after executing a MySQL statement

### LINKED ISSUE #6115: Caching is providing incorrect responses with gmysql backend and a stored procedure
- Program: Authoritative
 - Issue type: Bug report

### Short description
I can't get PowerDNS to provide consistent answers when using a stored procedure with the gmysql backend. It keeps providing different/incorrect answers when the backend data hasn't changed.

Relevant pdns.local.conf:
```
# Something in pdns caching is screwy
max-cache-entries=1
max-packet-cache-entries=1
cache-ttl=1
query-cache-ttl=1

# Launch gmysql backend
launch=gmysql:genericdns,gmysql:ridenips,gmysql:ridenmagic

# Used for generic DNS handling
gmysql-genericdns-socket=/var/run/mysqld/mysqld.sock
gmysql-genericdns-dbname=dns
gmysql-genericdns-user=...
gmysql-genericdns-password=...

# Used specifically for riden-jailed IP addresses
gmysql-ridenips-socket=/var/run/mysqld/mysqld.sock
gmysql-ridenips-dbname=riden
gmysql-ridenips-user=...
gmysql-ridenips-password=...

# Used for netrange scoring
gmysql-ridenmagic-socket=/var/run/mysqld/mysqld.sock
gmysql-ridenmagic-dbname=riden
gmysql-ridenmagic-user=pdns
gmysql-ridenmagic-password=...
gmysql-ridenmagic-any-id-query=CALL network_query(?, ?)
```

The network_query stored procedure looks like:
```
CREATE PROCEDURE network_query (name VARCHAR(255), whoknows VARCHAR(1))
network_query:begin
    declare ip_long int(10) unsigned default 0;
    declare return_value varchar(15) default '127.0.0.0';
    declare netrange_score float default 0;
    declare search int(10) unsigned default 0;
    declare offset int unsigned default 0;
    set offset = instr(name, '.rtidefense.net');
    if offset = 0 then
        select null as content, 600 as ttl, null as prio, 'A' as type, null as domain_id, null as disabled, name, null as auth;
        LEAVE network_query;
    end if;
    set search = inet_aton(substring(name, 1, offset - 1));
    if search is null then
        select null as content, 600 as ttl, null as prio, 'A' as type, 1 as domain_id, null as disabled, name, 1 as auth;
        LEAVE network_query;
    end if;
    set ip_long = ((search & 0x000000FF) << 24) + ((search & 0x0000FF00) << 8) + ((search & 0x00FF0000) >> 8) + (search >> 24);
    select `score` into netrange_score from netrange_scores where `range_start` <= ip_long and `range_end` >= ip_long;
    set return_value = concat('127.0.0.', cast(ceiling(netrange_score * 255) as char));
    select return_value as content, 120 as ttl, null as prio, 'A' as type, 1 as domain_id, 0 as disabled, name, 1 as auth;
end
```

So it should return null content for any request to subdomain.rtidefense.net where subdomain does not look like an IPv4 address in reverse octet order, and this part has been manually tested and seems to be working correctly. (Aside: returning null in the content field makes PowerDNS complain and return a SERVFAIL and I can't figure out how to get it to return NXDOMAIN instead, but that's a separate issue.)

Now, issue the following requests back-to-back:

```
$ dig nada.rtidefense.net @ourdns.domain.com

; <<>> DiG 9.9.5-9+deb8u14-Debian <<>> nada.rtidefense.net @ourdns.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43466
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;nada.rtidefense.net.           IN      A

;; ANSWER SECTION:
nada.rtidefense.net.    120     IN      A       127.0.0.0

;; Query time: 18 msec
;; SERVER: 159.89.130.198#53(159.89.130.198)
;; WHEN: Fri Dec 22 13:55:32 PST 2017
;; MSG SIZE  rcvd: 64

$ dig nada.rtidefense.net @ourdns.domain.com

; <<>> DiG 9.9.5-9+deb8u14-Debian <<>> nada.rtidefense.net @ourdns.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9978
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;nada.rtidefense.net.           IN      A

;; ANSWER SECTION:
nada.rtidefense.net.    120     IN      A       127.0.0.217

;; Query time: 17 msec
;; SERVER: 159.89.130.198#53(159.89.130.198)
;; WHEN: Fri Dec 22 13:55:45 PST 2017
;; MSG SIZE  rcvd: 64
```

Both of these answers are incorrect, and both of them happen after querying other subdomains, some which give the correct 127.0.0.0 answer, some which give the correct 127.0.0.217 answer, and some which give the incorrect of the two.

I have MySQL query logging turned on, and I can see pdns running the query in both cases:
```
2137 Execute   CALL network_query('nada.rtidefense.net', 1)
```
...but it then appears to be ignoring the result and returning something from a cache somewhere instead.

The pdns log is also showing a packetcache miss for both of these queries (timestamps exactly match the test output above):
```
Dec 22 13:55:32 Remote 198.0.235.49 wants 'nada.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Dec 22 13:55:45 Remote 198.0.235.49 wants 'nada.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
```

The weird thing here is that when it's not giving a cached answer, it hates the answer from the network_query stored procedure for this request:
```
Exception building answer packet for nada.rtidefense.net/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content '') sending out servfail
```

...but that doesn't appear in the pdns log when it's providing a cached answer, even though it still appears to be querying MySQL.

I have tried disabling its various caches and had no luck so far. Cache-related values are currently set to "1" in case it was ignoring a "0" setting. The behavior is unchanged.

### Environment
 - Operating system: Ubuntu 16.04.3 x64 on DigitalOcean (uses their repositories)
 - Software version: 4.0.0~alpha2-3build1 and 4.1.0
 - Software source: Ubuntu repository package (4.0.0) and https://downloads.powerdns.com/releases/ (4.1.0)

### Steps to reproduce

1. configure --with-modules="bind gmysql pipe" --without-lua; make; make install
2. Use the configuration and stored procedure shown above along with some test data
3. Results should be repeatable

### Expected behaviour
Caching should obey configuration settings and/or not provide erroneous answers to similar-but-different requests

Thank you.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

We will reuse the same array most of the time, but it turns out that calling `mysql_stmt_next_result()` followed by `mysql_stmt_store_result()` invalidates the existing binding (the first one sets `stmt->bind_result_done` to `false`, causing the second to reset the existing binding).

Fixes #6115.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by robsheldon** [comment]
This doesn't quite fix the issue. I pulled the most recent master branch and then merged this PR and restarted the server. From my console:

```
$ dig 42.33.22.11.rtidefense.net @ourns.domain.com

...

;; ANSWER SECTION:
42.33.22.11.rtidefense.net. 120 IN      A       127.0.0.217

...

$ dig nope.rtidefense.net @ourns.domain.com           

...
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 43412

...

$ dig 43.33.22.11.rtidefense.net @ourns.domain.com    

...

;; ANSWER SECTION:
43.33.22.11.rtidefense.net. 120 IN      A       127.0.0.217

...

$ dig 44.33.22.11.rtidefense.net @ourns.domain.com 

...

;; ANSWER SECTION:
44.33.22.11.rtidefense.net. 120 IN      A       127.0.0.217

...

$ dig 45.33.22.11.rtidefense.net @ourns.domain.com

...

;; ANSWER SECTION:
45.33.22.11.rtidefense.net. 120 IN      A       0.0.0.1

...

```

And the pdns output:
```
Jan 02 12:23:16 Remote 174.222.7.4 wants '42.33.22.11.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Jan 02 12:23:28 Remote 174.222.7.4 wants 'nope.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Jan 02 12:23:28 Exception building answer packet for nope.rtidefense.net/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content '') sending out servfail
Jan 02 12:23:37 Remote 174.222.7.4 wants '43.33.22.11.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Jan 02 12:23:43 Remote 174.222.7.4 wants '44.33.22.11.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Jan 02 12:23:48 Remote 174.222.7.4 wants '45.33.22.11.rtidefense.net|A', do = 0, bufsize = 1680: packetcache MISS
Jan 02 12:23:48 Result field at row 0 column 0 has been truncated, we allocated 1 bytes but at least 11 was needed
```

**Comment by rgacogne** [comment]
Could you confirm that you didn't get these with your previous patch? I can't reproduce them with my minimal testcase, and the parsing error looks like the content returned is wrong, which might be a different issue.

**Comment by robsheldon** [comment]
There are a couple of different test cases. The first, which I just verified is fixed by this commit, is where the same stored procedure is repeatedly called and returns a valid result but the mysql backend returns older results.

The second involves the stored procedure returning either null or "" for the content field. I haven't been able to figure out how to return NXDOMAIN from a stored procedure, and the only other reference I could find online (https://mailman.powerdns.com/pipermail/pdns-users/2015-June/011552.html) wasn't helpful. Returning null or "" causes a SERVFAIL, which is acceptable for our purposes for now.

However, with your commit, the second test case fails and returns the results shown above. My patch (although otherwise wrong) fixes this test case also.

The stored procedure is written to return "" for the content field when the remote wants a subdomain that doesn't look like an IP address. So, querying "nada.domain.com @test.dns.com" should break it.

I've just double-checked all of this, rerunning both test cases against both your changes and mine, on the current master branch.

**Comment by Habbie** [comment]
For NXDOMAIN, return zero rows.

**Comment by robsheldon** [comment]
Well, that seems obvious in hindsight. Thank you.

**Comment by Habbie** [comment]
> Well, that seems obvious in hindsight. Thank you.

Without having read everything - with that knowledge, and this PR, are your troubles resolved?

**Comment by robsheldon** [comment]
Yes, although I suspect that behavior (returning an incomplete address for stored procedures incorrectly returning null or "" content) will bite somebody in the future. Probably not many folks though.

**Pull request merged**
