### PR TITLE
auth: Trust EDNS Client Subnet from a trusted notification proxy

### LINKED ISSUE #4039: dnsdist : supermaster not working
Hello,

Supermaster fonctionnality is broken when using dnsdist in front of pdns slave server.
Slave server sees the NOTIFY request come from 127.0.0.1 because of dnsdist proxy, and tries to get the SOA and NS records from the host who sends the notify (127.0.0.1 here).

As the zone is not present on slave, request to 127.0.0.1 can not be replied :

Jun 24 15:52:29 Remote 127.0.0.1 wants 'domain.biz|SOA', do = 0, bufsize = 512: packetcache MISS
Jun 24 15:52:29 Received NOTIFY for domain.biz from 127.0.0.1 for which we are not authoritative
Jun 24 15:52:29 Remote 127.0.0.1 wants 'domain.biz|SOA', do = 0, bufsize = 512: packetcache MISS
Jun 24 15:52:29 Error resolving SOA or NS for domain.biz at: 127.0.0.1: Query to '127.0.0.1' for SOA of 'domain.biz' produced no answers

Regards,
Cédric

### PR DESCRIPTION
**Pull request by rgacogne**
This allows for example the use of dnsdist in front of supermaster
slaves.
dnsdist must be configured to send ECS to the backend with:
* `useClientSubnet=true` on the corresponding `newServer()`
* `setECSSourcePrefixV4(32)` and/or `setECSSourcePrefixV6(128)` so
the exact source is sent to the slave
* `setECSOverride(true)` so that any existing ECS information is
overridden

In addition, pdns must be configured to accept notification from
dnsdist with `trusted-notification-proxy` and to process ECS with
`edns-subnet-processing=yes`.

Closes #4039.

### CODE REVIEW

**Comment by spheron1** [comment]
Apologies if this isn't the right place for this.

I'm using the pdns-0.0.1187g5022750-1pdns.el7.x86_64 and dnsdist-0.0.1157g5022750-1pdns.el7.x86_64 RPMs from the "PowerDNS Authoritative Server - master branch" and "dnsdist - master branch" CentOS 7 repositories at https://repo.powerdns.com respectively.
These should both be the latest builds from long after this feature was merged.

I've got the following options set in /etc/pdns/pdns.conf:

```
edns-subnet-processing=yes
trusted-notification-proxy=::1 
```

And this is the relevant bit of /etc/dnsdist/dnsdist.conf:
```
setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)
setECSOverride(true)
newServer({address="[::1]:5300", useClientSubnet=True})
```

But I still see the following in the PowerDNS logs when a notification arrives from a supermaster via dnsdist:

```
pdns_server[16746]: Aug 12 13:41:00 Received NOTIFY for axfrtest.com from ::1 for which we are not authoritative
pdns_server[16746]: Aug 12 13:41:00 Received NOTIFY for axfrtest.com from ::1 for which we are not authoritative
pdns_server[16746]: Aug 12 13:41:01 Error resolving SOA or NS for axfrtest.com at: ::1: Query to '::1' for SOA of 'axfrtest.com.' produced no answers
pdns_server[16746]: Aug 12 13:41:01 Error resolving SOA or NS for axfrtest.com at: ::1: Query to '::1' for SOA of 'axfrtest.com.' produced no answers
```

What am I doing wrong?

**Comment by rgacogne** [comment]
So, either dnsdist didn't add the needed ECS information, or the auth isn't using it correctly. Would you by chance be able to see the content of the query sent by dnsdist using, for example, tcpdump?

**Comment by rgacogne** [comment]
> newServer({address="[::1]:5300", useClientSubnet=True})

Oh, please replace `True` by `true` here.

**Comment by spheron1** [comment]
Oh fail! That's working perfectly now, thank you :)

**Pull request merged**
