### PR TITLE
auth: Reconnect to the server if the My/Pg connection has been closed

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Test if the connection has been closed before trying to use it, and reconnect if it has.
Barely tested, comments welcome!

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
whats the expected interaction of reconnectIfNeeded and startTransaction?

**Comment by zeha** [comment]
👍

**Comment by pieterlexis** [comment]
Does this deprecate the work in #5005?

**Comment by Habbie** [comment]
> Does this deprecate the work in #5005?

yes

**Comment by Habbie** [comment]
Testing packages (based on the master branch + this PR) are now available at https://downloads.powerdns.com/autobuilt/. Browse to your flavour, then find the files with 'authsqlconnectionreset' in their name.

**Comment by Habbie** [comment]
We had one positive testing report. Merging this in the expection that we'll alpha or RC auth-4.1.0 before we release it.

**Pull request merged**
