### PR TITLE
Rec: split pdns_recursor.cc

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

A proposal to split `pdns_recursor.cc`. Some arbitrary decisions, but we can refine (or split more) later.

Rough split:

`pdns_recursor.cc`:  UDP handling and `startDoResolve` (maybe rename this file?)
`rec-main.cc`: startup and `recursorThread`
`rec-tcp.cc`: incoming TCP functions
`rec-main.hh`: header file common to these three

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
@rgacogne This conflicts now, but if this approach is ok I'll rebase or redo it.

**Comment by rgacogne** [comment]
I have not reviewed all the code changes, but the general approach looks good! Perhaps we could move some code out of rec-main.hh (mostly `UDPClientSocks` methods, I guess?), but that's a small nit.

**Comment by omoerbeek** [comment]
My plan is to re-do the split and the merge quickly to avoid conflicts.

**Review by rgacogne — APPROVED** [review]
I have not reviewed all of the changes (sorry!), but the way the files have been split looks good to me.

**Pull request merged**
