### PR TITLE
Change home directory to /var/lib/pdns

### PR DESCRIPTION
**Pull request by mortenstevens**
Check: https://bugzilla.redhat.com/show_bug.cgi?id=2262487

Fedora commit: https://src.fedoraproject.org/rpms/pdns/c/d6ae698064802c03bcf923cc0f97b02ddc2ee5c9?branch=rawhide

### CODE REVIEW

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
want to do pdns-recursor.spec and dnsdist.spec too?

**Review by omoerbeek — APPROVED** [review]
One nit

**Comment by rgacogne** [comment]
Looks ready for a merge apart from the whitespace spotted by Otto. Shall I fix it?

**Comment by rgacogne** [comment]
> Looks ready for a merge apart from the whitespace spotted by Otto. Shall I fix it?

done

**Comment by Habbie** [comment]
> want to do pdns-recursor.spec and dnsdist.spec too?

there's also this, but that does not prevent merging

**Comment by Habbie** [comment]
because of the observation in https://github.com/PowerDNS/pdns/pull/14083#issuecomment-2088536189 I am removing the backport labels

**Comment by Habbie** [comment]
I have now come to my senses and realise that this patch still makes sense for first installs. I'll put the labels back :clown_face:

**Pull request merged**
