### PR TITLE
dnsdist: Add my key to the list of those authorized to sign releases

### LINKED ISSUE #6953: dnsdist: detached signature created by unlisted key
- Program: dnsdist
 - Issue type: Bug report

### Short description

https://dnsdist.org/install.html lists four keys. None of these are the key used to create the detached signature.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Also remove the mention of the PowerDNS PGP keyblock since my key is not present in that keyblock and has been used to sign almost all dnsdist releases, except 1.0.0.
Closes #6953.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by zeha** [comment]
For some distributions that check signatures, it is beneficial if there's a single .asc file containing all keys...

**Comment by rgacogne** [comment]
> For some distributions that check signatures, it is beneficial if there's a single .asc file containing all keys...

Then we probably need to publish a separate keyblock for dnsdist.

**Comment by rgacogne** [comment]
@pieterlexis  I updated my PR but I guess I can't just put the dnsdist-keyblock.asc file in the docs directory and expect it to show up at the root of the dnsdist website, right?

**Comment by rgacogne** [comment]
For the record, I generated the keyblock with:
```
gpg --armor --export --export-options export-minimal 0xA208ED4F8AF58446 0xDCF513FA7EED19F3 0x1C5EE990D2E71575 0x5E50715BF2FFE1A7 0x6FFC33439B0D04DF
```

**Comment by pieterlexis** [comment]
If you put in a docs/static it will be copied along

**Comment by rgacogne** [comment]
> If you put in a docs/_static it will be copied along

Done, thanks!

**Pull request merged**
