### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by zeha**

### CODE REVIEW

**Comment by Fusl** [comment]
If I recall correctly remotes-ringbuffer-entries and other options that you removed have been working in older versions and you could simply mark them as "Available until:" like you did with the two other options.

**Comment by pieterlexis** [comment]
@fusl: the manpage has bene distributed with those versions, removing these options from the manpage in master is fine :)

**Comment by Fusl** [comment]
@pieterlexis That's correct but I still would prefer the old options in the manpage because I for example don't have `man` installed at all so I can't check what options there are. We could move the old, removed parameters to a sub header like "deprecated" or "removed" so it is visible that the options have been removed in newer versions, and still the options are described in detail because we have them on the public manpage.

**Comment by pieterlexis** [comment]
@Fusl I understand your point, but we like to keep the manpages in master current with the binaries produced (although we also mess up sometimes). If you run an older version and cannot view the on-system manpages, the settings page in the docs is where you must go.

**Comment by cmouse** [comment]
Also, man pages can be read using cat, more, less or some other pager.

**Pull request merged**
