### PR TITLE
Docker images: Remove capability requirements

### PR DESCRIPTION
**Pull request by nvaatstra**
### Short description
The current Docker images are built with a dependency on the NET_BIND_SERVICE capability which used to be required for binding to a privileged port. This capability included in the image causes problems when trying to deploy the image on a Kubernetes platform with restrictive security policies in place (which is becoming the norm).

This pull request removes those dependencies and adds instructions to:
- Avoid these privileged ports (by binding to non-privileged ports)
- Add the NET_BIND_SERVICE capability to containers

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
@omoerbeek @rgacogne a backport to 4.6 and 1.7 would be very convenient. Any objections?

**Comment by rgacogne** [comment]
I'm not sure I understand what happens by default after that PR is merged. The default ports are still privileged but the services no longer have the capability to bind to these ports, right? In that case can the services start without changing the configuration? Is running the container in privileged mode enough, even though we run under a non-privileged user?

**Comment by Habbie** [comment]
> Is running the container in privileged mode enough, even though we run under a non-privileged user?

Nico has just extended the README to note that since Docker 20.10.0, binding <1024 simply is allowed by default. Specifically, 20.10.0 and up set `net.ipv4.ip_unprivileged_port_start = 0` inside containers.

**Comment by rgacogne** [comment]
Ah, I missed that, thanks. That's nice. And I guess before that change we can't start even if the container runs in privileged mode?

**Comment by Habbie** [comment]
(users with other runtimes may need to do work, as the readme says, so perhaps upgrade notes are in order, I can do that)

**Comment by Habbie** [comment]
> Ah, I missed that, thanks. That's nice. And I guess before that change we can't start even if the container runs in privileged mode?

Before that, privileged mode works, or the `setcap` that this PR removes.

**Comment by rgacogne** [comment]
So when running in privileged mode and with a non-root user, we still keep all capabilities?

**Comment by Habbie** [comment]
> So when running in privileged mode and with a non-root user, we still keep all capabilities?

Uh, I think so yes.

**Review by rgacogne — APPROVED** [review]

**Comment by Habbie** [comment]
> So when running in privileged mode and with a non-root user, we still keep all capabilities?

After more investigation: yes, Docker's `USER` is not great at dropping capabilities, but dnsdist is, so we're safe.

**Comment by rgacogne** [comment]
Note that the recursor also calls `dropCapabilities` but it looks like the authoritative server doesn't.

**Comment by Habbie** [comment]
Proposed text for upgrade notes for all 3 products:

Privileged port binding in Docker
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In our Docker image, our binaries no longer get the ``net_bind_service`` capability, as this is unnecessary in many deployments.
For more information, see the section "Privileged ports" in [Docker-README](https://github.com/PowerDNS/pdns/blob/master/Docker-README.md#privileged-ports).

**Comment by jsoref** [comment]
> Proposed text for upgrade notes for all 3 products:
> 
> ```
> Privileged port binding in Docker
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> In our Docker image, our binaries no longer get the ``net_bind_service`` capability, as this is unnecessary in many deployments.

I'm not sure about the word `get`, do you mean `ask for`, `are assigned`, ...?

> For more information, see the section "Privileged ports" in [Docker-README](https://github.com/PowerDNS/pdns/blob/master/Docker-README.md#privileged-ports).
> ```

**Comment by rgacogne** [comment]
Or perhaps `are granted`?

**Comment by jsoref** [comment]
As `are no longer granted`

**Pull request merged**
