### PR TITLE
Drop libdecaf support

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Algo 15 is now provided by libsodium and recent versions of OpenSSL, 16 by recent versions of OpenSSL as well, but more importantly it looks like we don't really enable and test the libdecaf code.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mind04** [comment]
This is too soon. With this pull you are dropping ed448 support for distributions with a not recent enough openssl version, like centos7.

**Comment by rgacogne** [comment]
> This is too soon. With this pull you are dropping ed448 support for distributions with a not recent enough openssl version, like centos7.

I don't mind keeping that support a bit longer, but is decaf support actually enabled on our CentOS 7 builds?

**Comment by omoerbeek** [comment]
> > This is too soon. With this pull you are dropping ed448 support for distributions with a not recent enough openssl version, like centos7.
> 
> I don't mind keeping that support a bit longer, but is decaf support actually enabled on our CentOS 7 builds?

On our CentOS7 builds it is not:
```
checking whether we will be linking in libdecaf... no
...
configure: OpenSSL ecdsa: yes
configure: ed25519: yes
configure: ed448: no
```

**Comment by rgacogne** [comment]
Is libdecaf available there? If so, shall we enable it?

**Comment by omoerbeek** [comment]
> Is libdecaf available there? If so, shall we enable it?

https://pkgs.org/search/?q=decaf
Does not list a lot of platforms having it.

**Comment by omoerbeek** [comment]
> > Is libdecaf available there? If so, shall we enable it?
> 
> https://pkgs.org/search/?q=decaf
> Does not list a lot of platforms having it.

I think the conclusion is: libdecaf is generally unsupported and we can get rid of the support

**Comment by rgacogne** [comment]
Rebased to fix a conflict.

**Pull request closed without merging**
