### PR TITLE
dnsdist: Add debug messages to understand the "Advanced: includeDirectory()" failure on CI

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Hopefully it will fail for this PR as well.

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
> Hopefully it will fail for this PR as well.

It did!

**Comment by omoerbeek** [comment]
With my latest changes (rebase that removed some debug code and only run advanced test):
```
  ERROR: Advanced: includeDirectory()
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/test_Advanced.py", line 1038, in testAdvancedIncludeDirAllowed
      print(self.sendConsoleCommand('grepq("")'))
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/dnsdisttests.py", line 698, in sendConsoleCommand
      theirNonce = sock.recv(len(ourNonce))
  socket.timeout: timed out
```
This looks like a console command now times out. Will investigate later. I might have broken something with the rebase.

**Comment by omoerbeek** [comment]
I can't spot an error in the rebase. A possible explanation could be that dnsdist deadlocks somehow, but only if opendir and friends are used with tsan....????

**Comment by rgacogne** [comment]
I can't spot any error either. dnsdist's logs show that the console connection was accepted but then the process seems stuck indeed. I just pushed a few debugging lines..

**Comment by omoerbeek** [comment]
I have re-ran the test a many times yesterday and today and saw no failures yet. To be continued...

**Comment by omoerbeek** [comment]
Another couple of runs without failure. With the debug terminal I/O the failure does not seem to happen.
I think we can conclude that the issues is with tsan and specific I/O in the GH environment.

The pragamatic solution would be: do not run test in the test with the current env and call it a day.

It would be nice if the test gets re-enabled automatically if the compiler or runtime env changes. What would be the best way to achieve that?

**Comment by rgacogne** [comment]
> I think we can conclude that the issues is with tsan and specific I/O in the GH environment.

Agreed.

> The pragamatic solution would be: do not run test in the test with the current env and call it a day.

Yes, we have spent way too many man-days on this..

> It would be nice if the test gets re-enabled automatically if the compiler or runtime env changes. What would be the best way to achieve that?

Unsure, we can easily disable a test based on environment variables with unittest, but automatically detecting a change in the environment is not easy.
I'll open a PR to skip that test on GH actions for now.

**Comment by rgacogne** [comment]
Closing as the test is now disabled on GH actions.

**Pull request closed without merging**
