### PR TITLE
Rel/rec 4.9.x The reverse-solution request of dns64 records needs to add TTL to v4 cname

### PR DESCRIPTION
**Pull request by zjs604381586**
### Short description

For the reverse resolution of **dns64** records, the TTL of the v4 record after the cname is 0. Since the authority has not configured the reverse resolution of v4, it will cause some irrelevant resolution requests to reach the pdns-recursor service. You can set the v4 cname in **getFakePTRRecords()** Add ttl to improve cache hit rate
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by omoerbeek** [comment]
I'd rather not introduce yet another setting. Maybe we could borrow the TTL form the PTR records that's get added... have to think about it.

**Comment by omoerbeek** [comment]
> I'd rather not introduce yet another setting. Maybe we could borrow the TTL form the PTR records that's get added... have to think about it.

#13043 shows the alternative approach.

**Comment by zjs604381586** [comment]
> > I'd rather not introduce yet another setting. Maybe we could borrow the TTL form the PTR records that's get added... have to think about it.
> 
> #13043 shows the alternative approach.

Great, this solution looks simpler and more reasonable

**Comment by omoerbeek** [comment]
#13043 was merged.

**Pull request closed without merging**
