### PR TITLE
timestamp TTL limiting to fix Issue #7439 - Take 2

### PR DESCRIPTION
**Pull request by smellyspice**
### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
@smellyspice your persistence in navigating git, github, your editor, etc. in this is appreciated! I planned to, if necessary, get your contribution into our tree by hand, because I think the fix looks good and tooling issues should not prevent a fix from going in. I intend to get this in next week, no matter what.

**Comment by smellyspice** [comment]
@Habbie - Thanks for the good words, it's nice to know that my efforts and screw-ups are taken in stride! I really didn't know how else to proceed other than to start fresh after my editor ended up reformatting that file. It is a simple fix, which I've been running in production for over 6 months with no issues, so it would be nice to get it into master. Thanks!

**Comment by Habbie** [comment]
> I always feel that boundary conditions checks should be < and > not <= or >=

I agree, but in this specific case, it mirrors code from the original tinydns:

```
tdlookup.c-     if (newttl <= 2.0) newttl = 2.0;
tdlookup.c:     if (newttl >= 3600.0) newttl = 3600.0;
```

which also has readability benefits.

**Comment by Habbie** [comment]
I have a testcase for this sitting on a branch, will add it soon.

**Comment by pieterlexis** [comment]
@Habbie **poke**

**Comment by Habbie** [comment]
The 'large ttl' test i wrote turns out to not exercise this code. I'll push it to this branch anyway, to show that this code does not affect non-timestamp large TTLs.

**Pull request merged**
