### PR TITLE
Correct YaHTTP license

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by zeha** [comment]
Please keep use of the Expat name, as per DEP5

**Comment by cmouse** [comment]
what does Expat mean?

**Comment by Habbie** [comment]
ping

**Comment by cmouse** [comment]
There was some indication that MIT might be valid too. @zeha I know I asked this over IRC but could you comment here?

**Comment by zeha** [comment]
DEP5 says "use Expat". Not sure which point wasn't clear.

**Comment by cmouse** [comment]
Expat is not mit license. Why does it mandate different license?

**Pull request closed without merging**
