### PR TITLE
Remove hardcoded -lresolv, -lnsl and -lsocket

### LINKED ISSUE #1967: PowerDNS complains about missing '-lnsl' when building under musl
https://github.com/PowerDNS/pdns/blob/3d21a36bac3308e6ff53447661b3007458c1d04a/configure.ac#L303-L325 configure.ac lacks a check for non-glibc bases libc's at the above lines, appending `-lnsl` to the module flags, even though this library is absent under musl.

### PR DESCRIPTION
**Pull request by rubenk**
We already check for the functions we need in libnsl
and libsocket, and I assume we don't need libresolv

Should fix #1967

### CODE REVIEW

**Comment by rubenk** [comment]
I now check for gethostent in nsl, inet_aton in resolv and socket in socket with AC_SEARCH_LIBS

**Comment by cmouse** [comment]
Detection works on Solaris 9 and 10, compiles on Solaris 10.

**Comment by Habbie** [comment]
Please report what other OSes/environments have been tested :)

**Comment by rubenk** [comment]
OSX:
checking for library containing socket... none required
checking for library containing gethostent... none required
checking for library containing inet_aton... none required

**Comment by cmouse** [comment]
FreeBSD 9.3-RELEASE (could not test compile)

checking for library containing socket... none required
checking for library containing gethostent... none required
checking for library containing inet_aton... none required

**Comment by cmouse** [comment]
Arch Linux ARMPI

checking for library containing socket... none required
checking for library containing gethostent... none required
checking for library containing inet_aton... none required

**Pull request merged**
