### PR TITLE
Enable FORTIFY_SOURCE=3 when supported by the compiler

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Barely tested, we should at least measure the performance impact and ponder making that optional.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by appliedprivacy** [comment]
thanks!

When testing it I noticed that gcc (unlike clang) does not result in `-D_FORTIFY_SOURCE=3` on Ubuntu 22.10:

## gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

<details>

```
configure: Configuration summary
configure: =====================
configure: 
configure: PowerDNS Recursor 0.0.0.0.master.g44d305b302.dirty configured with: (no options)
configure: 
configure: CC: gcc
configure: CXX: g++ -std=c++17
configure: LD: /usr/bin/ld -m elf_x86_64
configure: CFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -fvisibility=hidden -g -O2 -g -O2
configure: CPPFLAGS: 
configure: CXXFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -fvisibility=hidden -g -O2 
configure: LDFLAGS: -Wl,-z -Wl,relro -Wl,-z -Wl,now  -rdynamic
configure: LIBS: 
configure: BOOST_CPPFLAGS:  -pthread
```

</details>

## Ubuntu clang version 15.0.2-1

<details>

```
configure: Configuration summary
configure: =====================
configure: 
configure: PowerDNS Recursor 0.0.0.0.master.g44d305b302.dirty configured with:  'CC=/usr/bin/clang' 'CXX=/usr/bin/clang++'
configure: 
configure: CC: /usr/bin/clang
configure: CXX: /usr/bin/clang++ -std=c++17
configure: LD: /usr/bin/ld -m elf_x86_64
configure: CFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 --param ssp-buffer-size=4 -fstack-protector -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -fvisibility=hidden -g -O2 -g -O2
configure: CPPFLAGS: 
configure: CXXFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 --param ssp-buffer-size=4 -fstack-protector -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -fvisibility=hidden -g -O2 
configure: LDFLAGS: -Wl,-z -Wl,relro -Wl,-z -Wl,now  -rdynamic
configure: LIBS: 
configure: BOOST_CPPFLAGS: 

```

</details>

**Comment by rgacogne** [comment]
It works for me with GCC 12.2.0 on Arch. It requires glibc >= 2.34, but Ubuntu 22.10 is supposed to have 2.36, so I don't know.

**Comment by rgacogne** [comment]
Oh, you have `-Werror`..

**Comment by rgacogne** [comment]
I just pushed a commit adding an `--enable-fortify-source` configure option. The option defaults to 2 to keep the existing behaviour, but 3 and auto are supported, with auto trying to select the highest version supported by the compiler.

**Review by fredmorcos — CHANGES_REQUESTED** [review]
This is behaving strangely for me. Using the latest clang and gcc on Archlinux I get:

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=3... no
checking whether C++ compiler handles -D_FORTIFY_SOURCE=2... no
```

Additionally, with the second commit (which add `--enable-fortify-source`) I get the following when I don't pass `--enable-fortify-source`:

```
checking whether FORTIFY_SOURCE is supported... checking whether C++ compiler handles -D_FORTIFY_SOURCE=2... no
checking whether C++ compiler handles -D_FORTIFY_SOURCE=1... no
no
```

1) The output is garbled.
2) It still says that none of the level are supported.
3) It sometimes can't find either `libcrypto` or `libdecaf` headers anymore, varies between runs:

```
checking whether compiling and linking against OpenSSL's libcrypto works... no
configure: error: OpenSSL/libcrypto not found
```

```
checking for decaf.hxx... no
configure: error: cannot find libdecaf headers
```

Although those work fine with the first commit. I can't tell what the second commit introduces that might break this.

**Comment by rgacogne** [comment]
I pushed a commit fixing the interleaving during the detection of `FORTIFY_SOURCE`.

As for the rest, I don't get it :-/
Here are my results on Arch, depending on the value of `--enable-fortify-source`:

- `default` (`--enable-fortify-source` not specified on the configure line)

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=2... yes
checking whether FORTIFY_SOURCE is supported... 2
```

- `auto`

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=3... yes
checking whether FORTIFY_SOURCE is supported... 3
```

- `3`

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=3... yes
checking whether FORTIFY_SOURCE is supported... 3
```

- `2`

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=2... yes
checking whether FORTIFY_SOURCE is supported... 2
```

- `1`

```
checking whether C++ compiler handles -D_FORTIFY_SOURCE=1... yes
checking whether FORTIFY_SOURCE is supported... 1
```

- `no`

```
checking whether FORTIFY_SOURCE is supported... no
```

And in all cases I get:
```
checking for decaf.hxx... yes
```

**Comment by fredmorcos** [comment]
My issues were caused by the fact that `FORTIFY_SOURCE` requires at least `-O` and I was configuring with `-O0`.

This output is still interleaved though:

```
checking whether FORTIFY_SOURCE is supported... checking whether C++ compiler handles -D_FORTIFY_SOURCE=3... yes
3
```

**Comment by rgacogne** [comment]
> My issues were caused by the fact that `FORTIFY_SOURCE` requires at least `-O` and I was configuring with `-O0`.

Ah, right. We could change the optimization when we check if the compiler supports this feature, but that doesn't feel right since it will not work in the end anyway.

> This output is still interleaved though:
> ```
> checking whether FORTIFY_SOURCE is supported... checking whether C++ compiler handles -D_FORTIFY_SOURCE=3... yes
> 3
> ```

Weird, it really shouldn't be with the latest commit.

**Comment by fredmorcos** [comment]
> Weird, it really shouldn't be with the latest commit.

Argh. Sorry. I fetched and forgot to rebase. It works fine now. Thank you!

**Pull request merged**
