### PR TITLE
auth: Fix a construction ordering issue between `StatBag` and `Logger`

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

By turning the global `StatBag` into a singleton.

Reported by Coverity as CID 1524949: Initialization or destruction ordering is unspecified.

This is only a draft because turning `StatBag` into a singleton might not be the way we want to tackle this. It's the only way I found that did not require an awful lot of refactoring in various places, but hopefully someone will get a better idea :)

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by Habbie** [comment]
> hopefully someone will get a better idea

like #13613? Or do we need both these PRs? If we're explicitly passing it always (in 13613) maybe that gives us enough control over when to construct it.

**Comment by rgacogne** [comment]
> > hopefully someone will get a better idea
> 
> like #13613? Or do we need both these PRs? If we're explicitly passing it always (in 13613) maybe that gives us enough control over when to construct it.

#13613 does not fix this issue, no. If we managed to always pass the `StatBag` along we could make it non-global which would solve the issue, but I really don't see that happening given how widespread its use is. I'd very happy to be proven wrong.

**Comment by Habbie** [comment]
> we managed to always pass the `StatBag` along

right, 13613 only does one file. Thank you for explaining!

**Comment by rgacogne** [comment]
Closing this PR since it is now conflicted and we seem to be aiming for a different approach.

**Pull request closed without merging**
