### PR TITLE
docs: Fix formatting typo in Recursor settings

### PR DESCRIPTION
**Pull request by mnordhoff**
### Short description
A link was broken.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by rgacogne — APPROVED** [review]

**Comment by omoerbeek** [comment]
"DNSEC enabled" is a somewhat ambiguous. Id' suggest: the value of `dnssec` should be `process`, `log-fail` or `validate`.

**Comment by mnordhoff** [comment]
I agree. I'm bikeshedding it in my text editor now. :D

**Comment by mnordhoff** [comment]
@omoerbeek I pushed something.

**Comment by mnordhoff** [comment]
Wait, typo.

**Comment by mnordhoff** [comment]
OKAY

**Pull request merged**
