### PR TITLE
Update migration.md

### PR DESCRIPTION
**Pull request by shimmi2**
Updated link to wiki for easy reach scripts for migrating from MyDNS

### CODE REVIEW

**Comment by Habbie** [comment]
Are you sure this makes the link clickable?

**Comment by shimmi2** [comment]
If You are talking about link to wiki from modified doc, I have not problem with it, on the contrary.

**Comment by Habbie** [comment]
Link works. Merged!

**Comment by shimmi2** [comment]
Thank You

     PowerDNS is a smaal little bit more usable than before, again :)

Have a nice day

T.


Dne 9. 2. 2015 v 15:15 Peter van Dijk napsal(a):
>
> Link works. Merged!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PowerDNS/pdns/pull/2210#issuecomment-73514532>.
>

-- 
*Ing. Tomáš Šimek*
ředitel společnosti
__________________________________________
NECOSS - *Ne*twork *Co*munication *S*ystems & *S*olutions
www.necoss.cz <http://www.necoss.cz> / www.vyladenyinternet.cz 
<http://www.vyladenyinternet.cz>

tel.: +420 800 55 66 55, mobil: +420 608 259 701
e-mail: tomas.simek@necoss.cz, tomas@simek.info

**Pull request merged**
