### PR TITLE
logger: Use a function-level static var for the logger object

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This PR includes the commit from #6625, replaces #6639. I don't like the macro trick at all but I don't see any other way to make sure that the `Logger` object is correctly initialized before any use. 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by tih** [comment]
I tested this on NetBSD/amd64, and verified that the authoritative server and the recursor both work correctly with this modification. Thus, it solves the issue I reported in #6624.

I will also test on NetBSD/arm, and report further once that has been done.

**Comment by tih** [comment]
The recursor still crashes in exactly the same way on NetBSD/arm, I'm afraid.

**Comment by rgacogne** [comment]
I'm now wondering whether the switch to `thread_local` is causing this issue on `NetBSD/arm`..

**Comment by tih** [comment]
Can I do something to test whether thread_local is working properly? Might be a platform specific bug in GCC 6.4, I suppose.

**Comment by tih** [comment]
Just to see what would happen, I built the authoritative server on the Pi, from the same code base, including the gpgsql module. It's running (and logging) just as it should, happily letting me create and modify zones, which it then serves correctly. Securing zones on it works, too.

So the crash in the recursor, the first time recursorThread() tries to log something, *may* of course be a GCC bug in the thread_local handling, but it doesn't seem all that likely to me.

For reference, the backtrace looks like this:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x7a5598c4 in std::string::append(std::string const&) ()
   from /usr/lib/libstdc++.so.8
[Current thread is 1 (process 2)]
(gdb) bt
#0  0x7a5598c4 in std::string::append(std::string const&) ()
   from /usr/lib/libstdc++.so.8
#1  0x088d8b74 in Logger::operator<< (s=..., this=0x8da7f6c <getLogger()::log>)
    at logger.cc:166
#2  Logger::operator<< (this=0x8da7f6c <getLogger()::log>, s=<optimized out>)
    at logger.cc:172
#3  0x08971ddc in recursorThread (n=<optimized out>, worker=<optimized out>)
    at pdns_recursor.cc:3436

**Pull request merged**
