### PR TITLE
auth-4.7.x catalog zones: simplify migration schemas by appending columns

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
backport of #11836

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by cwchristerw** [comment]
Column length too big for column 'options' (max = 16383); use BLOB or TEXT instead

**Comment by kpfleming** [comment]
This isn't really a good place to post problem reports, but you should at least indicate which database backend (and database, and version) you are using.

**Comment by cwchristerw** [comment]
I'm using MariaDB 10.10.2

**Comment by cwchristerw** [comment]
I fixed by using suggested TEXT

**Comment by kpfleming** [comment]
Have you added other columns to the `domains` table? The schema as designed fits within the 65,536 byte limit for MySQL/MariaDB. The error message you show above indicates that your table definition must have other columns consuming around 47,000 bytes of the maximum row size.

**Comment by Habbie** [comment]
Or a charset issue causing characters to consume (way) more than 1 byte each - we have seen this before.

**Pull request merged**
