### PR TITLE
pdns_control: exit 1 on unknown command

### LINKED ISSUE #1295: pdns_control show foo does not error
$ ./pdns_control --socket-dir=. show udp6-queries
    0
    $ ./pdns_control --socket-dir=. show foo
    0

(should also check rec_control)

### PR DESCRIPTION
**Pull request by rubenk**
Fixes #1295

### CODE REVIEW

**Comment by Habbie** [comment]
This seems hacky ;)

**Comment by rubenk** [comment]
The whole protocol seems hacky ;) It has no way of indicating error to the client.

**Comment by Habbie** [comment]
I'm fine with merging this, as soon as there are indications (in comments in the code, or in a new ticket) that this is terrible ;)

**Comment by rubenk** [comment]
I logged #2274 to track this.

**Pull request merged**
