### PR TITLE
Auth 4.2.x backports

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
I branched rel/auth-4.2.x at the rc2 point, to avoid some unwanted newer changes. This PR has the changes we do want.

Other candidates: 
* [x] #7550
* [x] #7699 
* [x] #7871
* [x] #7889
* [x] #7890
* [x] #7910
* [x] #7918
* [x] #7943
* [x] #7962
* [x] #7969
* [x] #7976
* [x] #7977
* [x] #7980
* [x] #7996
* [x] #8006
* [x] #8019 
* [x] #8028 
* [x] ~#7964~ #8037
* [ ] #8049
* [ ] #8050 
* [x] #8051 

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by James-TR** [comment]
#7980 would be good to include in this. This PR fixes issues where Uclibc pretends to be Glibc

**Comment by Habbie** [comment]
> #7980 would be good to include in this. This PR fixes issues where Uclibc pretends to be Glibc

Added to the list.

**Comment by Habbie** [comment]
> Added to the list.

Added to the PR!

**Comment by Habbie** [comment]
This PR has become huge. i will merge it as soon as CI is happy in the current state, and PR other backports separately.

**Pull request merged**
