### PR TITLE
use luaL_checkinteger for Lua 5.3

### PR DESCRIPTION
**Pull request by mind04**

### CODE REVIEW

**Comment by Habbie** [comment]
What about 5.0? I understand it doesn't have the define

**Comment by Habbie** [comment]
Makes me realise lua-auth also ignores 5.0 in the same way. Merging :)

**Comment by ahupowerdns** [comment]
5.0 support can die, I don't know anyone who has that.

**Comment by Habbie** [comment]
:+1:

**Comment by zeha** [comment]
As far as Debian is concerned, 5.1 support can go away, too.

**Comment by mind04** [comment]
undefined is also < 5.3 ;)
epel 5 has Lua 5.1

**Pull request merged**
