### PR TITLE
Update the pgp keys listed in docs

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Remove Bert and Pieter, add Remi and Otto
Same order as mentioned key file.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
Following the principle of least privileges, I don't think my key needs to be allowed to sign tarballs for the auth and the rec at this point.
For Bert and Pieter, perhaps we should add a paragraph explaining which past releases were signed with their keys, so it's still possible to validate old releases?

**Comment by omoerbeek** [comment]
> Following the principle of least privileges, I don't think my key needs to be allowed to sign tarballs for the auth and the rec at this point. For Bert and Pieter, perhaps we should add a paragraph explaining which past releases were signed with their keys, so it's still possible to validate old releases?

I was listing the keys in the current published in https://www.powerdns.com/powerdns-keyblock.asc, which includes your key. I can leave your key out, but the keyblock file will still contain it.

I will push an update that lists Bert's and Pieter's keys as only valid for old releases.

**Comment by rgacogne** [comment]
Ah, right, I'll have to check if my key has a good reason to be in there, then :)

**Comment by omoerbeek** [comment]
> Ah, right, I'll have to check if my key has a good reason to be in there, then :)

One scenario: an emergency release of rec or auth and nobody of the other three signers available. 
dnsdist has its own list and keyblock file which both need updates as well.

**Comment by rgacogne** [comment]
Alright, let's keep it that way then!

**Comment by omoerbeek** [comment]
> Alright, let's keep it that way then!

Also because of: https://github.com/PowerDNS/pdns/security/policy

**Review by rgacogne — APPROVED** [review]

**Pull request merged**
