### PR TITLE
dnsdist: Add ChangeLog and secpoll for 1.6.0-rc2

### PR DESCRIPTION
**Pull request by rgacogne**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by omoerbeek — APPROVED** [review]
rec uses secpoll status 3 for old pre-releases, but that's debatable

**Comment by rgacogne** [comment]
> rec uses secpoll status 3 for old pre-releases, but that's debatable

I'll think about it, as we can change that later :)

**Comment by omoerbeek** [comment]
> > rec uses secpoll status 3 for old pre-releases, but that's debatable
> 
> I'll think about it, as we can change that later :)

My motivation is mostly to stimulate people to use the latest pre-release.

**Comment by rgacogne** [comment]
Understood, but on the other hand I don't want to blur the line between 'unsupported' and 'known vulnerable'.

**Pull request merged**
