### PR TITLE
dnsdist: Set Server Name Indication on outgoing TLS connections (DoT, DoH)

### LINKED ISSUE #11249: dnsdist: SNI extension is missing on outgoing TLS connections
- Program:  dnsdist
 - Issue type: Bug report

### Short description
Adding DoT or DoH backends via `newServer({address="ip:port", tls="openssl", subjectName="dns.someserver.com"})` or `newServer({address="ip:port", tls="openssl", subjectName="dns.someserver.com", dohPath="/query"})` initiates the outgoing TLS connection without setting the SNI extension in the TLS ClientHello. This causes problems if the default certificate of responding server does not match the `subjectName` value. 

### Environment
 - Operating system: Voidlinux, Debian Bookworm
 - Software version: 1.7.0
 - Software source: Default OS repositories

### Steps to reproduce

1. Configure a TLS backend via `newServer({address="ip:port", tls="openssl", subjectName="dns.someserver.com"})`
2. Have the server responding on `dns.someserver.com` return a non-matching default certificate

### Expected behaviour
dnsdist should initialize the TLS context properly to ensure the server_name extension is sent in the ClientHello when the `subjectName` parameter is set.

### Actual behaviour
At least when using openssl, dnsdist appears to call `SSL_set1_host`, thus verifying the certificate against the specified `subjectName`. It doesn't seem to call `SSL_set_tlsext_host_name` or something similar to add the `subjectName` via the server_name extension to the ClientHello.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Fixes #11249 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by rgacogne** [comment]
dnsdist's regression tests failure is unrelated to this PR, but we actually have a race in that test making it fails if it takes more than one second for `check-config` to finish:
```
  ======================================================================
  ERROR: test suite for <class 'test_Lua.TestLuaThread'>
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/.venv/lib/python3.8/site-packages/nose/suite.py", line 210, in run
      self.setUp()
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/.venv/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
      self.setupContext(ancestor)
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/.venv/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
      try_run(context, names)
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/.venv/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
      return func()
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/dnsdisttests.py", line 146, in setUpClass
      cls.startDNSDist()
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/dnsdisttests.py", line 118, in startDNSDist
      raise AssertionError('dnsdist --check-config failed: %s' % output)
  AssertionError: dnsdist --check-config failed: b"Configuration 'configs/dnsdist_TestLuaThread.conf' OK!\ncounter says\tsetCounter\t1\n"
  
  ----------------------------------------------------------------------
  Ran 515 tests in 1295.153s
  
  FAILED (SKIP=1, errors=1)
  === end of nosetests log ===
  ```
  As to how `check-config` can actually take one second to do that on GH actions, I have no clue..

**Comment by rgacogne** [comment]
`test-auth-backend (gmysql, mariadb:10)` failure is unrelated as well (ALIAS).

**Comment by rgacogne** [comment]
The recursor failure might actually be related since the DoT tests are failing:
```
==============> configs/SimpleForwardOverDoT/recursor.log <==============
  Jan 31 09:52:45 PowerDNS Recursor 0.0.0-git1 (C) 2001-2022 PowerDNS.COM BV
  Jan 31 09:52:45 Using 64-bits mode. Built using clang 12.0.0  on Jan 31 2022 09:39:08 by runner@fv-az177-187.le1l2vivn1merivib3blaulaih.cx.internal.cloudapp.net.
  Jan 31 09:52:45 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
  Jan 31 09:52:45 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
  Jan 31 09:52:45 Enabling IPv4 transport for outgoing queries
  Jan 31 09:52:45 NOT using IPv6 for outgoing queries - add an IPv6 address (like '::') to query-local-address to enable
  Jan 31 09:52:45 allow-from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
  Jan 31 09:52:45 Redirecting queries for zone '.' with recursion to: 9.9.9.9:853
  Jan 31 09:52:45 Inserting rfc 1918 private space zones
  Jan 31 09:52:45 Listening for UDP queries on 127.0.0.1:5300
  Jan 31 09:52:45 Enabled TCP data-ready filter for (slight) DoS protection
  Jan 31 09:52:45 Listening for TCP queries on 127.0.0.1:5300
  Jan 31 09:52:45 Operating unthreaded
  Jan 31 09:52:45 Done priming cache with root hints
  Jan 31 09:52:45 Enabled 'epoll' multiplexer
  Jan 31 09:52:45 1 [1/1] question for 'dns.google|A' from 127.0.0.1:41049
  Jan 31 09:52:45 [1] : no TA found for 'dns.google' among 1
  Jan 31 09:52:45 [1] : no TA found for 'google' among 1
  Jan 31 09:52:45 [1] : got TA for '.'
  Jan 31 09:52:45 [1] dns.google: Wants DNSSEC processing, auth data in query for A
  Jan 31 09:52:45 [1] dns.google: No cache hit for 'dns.google|A', trying to find an appropriate NS record
  Jan 31 09:52:45 [1] dns.google: Cache consultations done, have 1 NS to contact
  Jan 31 09:52:45 [1] dns.google: Domain has hardcoded nameserver
  Jan 31 09:52:45 [1] dns.google.: Nameservers: +9.9.9.9:853(0.00ms)
  Jan 31 09:52:45 [1] dns.google: Resolved '.' NS (empty) to: 9.9.9.9
  Jan 31 09:52:45 [1] dns.google: Trying IP 9.9.9.9:853, asking 'dns.google|A'
  Jan 31 09:52:45 [1] dns.google: using DoT with 9.9.9.9:853
  lwres.cc:462:17: runtime error: load of value 208, which is not a valid value for type 'bool'
      #0 0x5643f93db6ab in asyncresolve(ComboAddress const&, DNSName const&, int, bool, bool, int, timeval*, boost::optional<Netmask>&, boost::optional<ResolveContext const&>, std::shared_ptr<std::vector<std::unique_ptr<RemoteLogger, std::default_delete<RemoteLogger> >, std::allocator<std::unique_ptr<RemoteLogger, std::default_delete<RemoteLogger> > > > > const&, std::shared_ptr<std::vector<std::unique_ptr<FrameStreamLogger, std::default_delete<FrameStreamLogger> >, std::allocator<std::unique_ptr<FrameStreamLogger, std::default_delete<FrameStreamLogger> > > > > const&, std::set<unsigned short, std::less<unsigned short>, std::allocator<unsigned short> > const&, LWResult*, bool*, TCPOutConnectionManager::Connection&) /home/runner/work/pdns/pdns/pdns/recursordist/lwres.cc:462:17
      #1 0x5643f93da5a2 in asyncresolve(ComboAddress const&, DNSName const&, int, bool, bool, int, timeval*, boost::optional<Netmask>&, boost::optional<ResolveContext const&>, std::shared_ptr<std::vector<std::unique_ptr<RemoteLogger, std::default_delete<RemoteLogger> >, std::allocator<std::unique_ptr<RemoteLogger, std::default_delete<RemoteLogger> > > > > const&, std::shared_ptr<std::vector<std::unique_ptr<FrameStreamLogger, std::default_delete<FrameStreamLogger> >, std::allocator<std::unique_ptr<FrameStreamLogger, std::default_delete<FrameStreamLogger> > > > > const&, std::set<unsigned short, std::less<unsigned short>, std::allocator<unsigned short> > const&, LWResult*, bool*) /home/runner/work/pdns/pdns/pdns/recursordist/lwres.cc:579:14
      #2 0x5643f9855a6d in SyncRes::asyncresolveWrapper(ComboAddress const&, bool, DNSName const&, DNSName const&, int, bool, bool, timeval*, boost::optional<Netmask>&, LWResult*, bool*) const /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:654:13
      #3 0x5643f98a6095 in SyncRes::doResolveAtThisIP(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DNSName const&, QType, LWResult&, boost::optional<Netmask>&, DNSName const&, bool, bool, DNSName const&, ComboAddress const&, bool, bool, bool&, bool&) /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:3989:18
      #4 0x5643f986eead in SyncRes::doResolveAt(std::unordered_map<DNSName, std::pair<std::vector<ComboAddress, std::allocator<ComboAddress> >, bool>, std::hash<DNSName>, std::equal_to<DNSName>, std::allocator<std::pair<DNSName const, std::pair<std::vector<ComboAddress, std::allocator<ComboAddress> >, bool> > > >&, DNSName, bool, DNSName const&, QType, std::vector<DNSRecord, std::allocator<DNSRecord> >&, unsigned int, std::set<SyncRes::GetBestNSAnswer, std::less<SyncRes::GetBestNSAnswer>, std::allocator<SyncRes::GetBestNSAnswer> >&, vState&, SyncRes::StopAtDelegation*) /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:4489:25
      #5 0x5643f985a629 in SyncRes::doResolveNoQNameMinimization(DNSName const&, QType, std::vector<DNSRecord, std::allocator<DNSRecord> >&, unsigned int, std::set<SyncRes::GetBestNSAnswer, std::less<SyncRes::GetBestNSAnswer>, std::allocator<SyncRes::GetBestNSAnswer> >&, vState&, bool*, SyncRes::StopAtDelegation*, bool) /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:1082:9
      #6 0x5643f984cf30 in SyncRes::doResolve(DNSName const&, QType, std::vector<DNSRecord, std::allocator<DNSRecord> >&, unsigned int, std::set<SyncRes::GetBestNSAnswer, std::less<SyncRes::GetBestNSAnswer>, std::allocator<SyncRes::GetBestNSAnswer> >&, vState&) /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:739:12
      #7 0x5643f984a69b in SyncRes::beginResolve(DNSName const&, QType, QClass, std::vector<DNSRecord, std::allocator<DNSRecord> >&, unsigned int) /home/runner/work/pdns/pdns/pdns/recursordist/syncres.cc:175:11
      #8 0x5643f947383c in startDoResolve(void*) /home/runner/work/pdns/pdns/pdns/recursordist/pdns_recursor.cc:1067:18
      #9 0x5643f94d8aaf in MTasker<std::shared_ptr<PacketID>, std::vector<unsigned char, noinit_adaptor<std::allocator<unsigned char> > >, PacketIDCompare>::makeThread(void (*)(void*), void*)::'lambda'()::operator()() const /home/runner/work/pdns/pdns/pdns/recursordist/./mtasker.cc:286:7
      #10 0x5643f94d804d in boost::detail::function::void_function_obj_invoker0<MTasker<std::shared_ptr<PacketID>, std::vector<unsigned char, noinit_adaptor<std::allocator<unsigned char> > >, PacketIDCompare>::makeThread(void (*)(void*), void*)::'lambda'(), void>::invoke(boost::detail::function::function_buffer&) /usr/include/boost/function/function_template.hpp:158:11
      #11 0x5643f9409764 in boost::function0<void>::operator()() const /usr/include/boost/function/function_template.hpp:763:14
      #12 0x5643f9408e06 in threadWrapper(boost::context::detail::transfer_t) /home/runner/work/pdns/pdns/pdns/recursordist/./mtasker_fcontext.cc:144:9
      #13 0x7f90f40681ce in make_fcontext (/lib/x86_64-linux-gnu/libboost_context.so.1.71.0+0x21ce)
  
  SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lwres.cc:462:17 in 
  
  + exit 1
  Error: Process completed with exit code 1.
```

**Comment by rgacogne** [comment]
It looks like `bool isNew` in `asyncresolve()` is used uninitialized when an exception occurs in `tcpconnect()`.

**Comment by rgacogne** [comment]
Trying to reproduce this locally yielded a new issue:
```
/usr/include/c++/11.1.0/bits/unique_ptr.h:179:32: runtime error: member call on null pointer of type 'struct __uniq_ptr_impl'
Jan 31 11:58:49 Done priming cache with root hints
    #0 0x555ed0fd5129 in std::__uniq_ptr_impl<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::reset(RecursorPacketCache*) /usr/include/c++/11.1.0/bits/unique_ptr.h:\
179
    #1 0x555ed0fd5129 in std::__uniq_ptr_impl<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::operator=(std::__uniq_ptr_impl<RecursorPacketCache, std::default_delet\
e<RecursorPacketCache> >&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:167
    #2 0x555ed0fd5129 in std::__uniq_ptr_data<RecursorPacketCache, std::default_delete<RecursorPacketCache>, true, true>::operator=(std::__uniq_ptr_data<RecursorPacketCache, std::de\
fault_delete<RecursorPacketCache>, true, true>&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:212
    #3 0x555ed0fd5129 in std::unique_ptr<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::operator=(std::unique_ptr<RecursorPacketCache, std::default_delete<Recursor\
PacketCache> >&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:371
    #4 0x555ed0fd5129 in recursorThread(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /work/pdns/pdns/recursordist/rec-main.c\
c:1931
    #5 0x555ecf8c52b7 in serviceMain /work/pdns/pdns/recursordist/rec-main.cc:1650
    #6 0x555ecf8c52b7 in main /work/pdns/pdns/recursordist/rec-main.cc:2496
    #7 0x7ff02bf79b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #8 0x555ecf8ec78d in _start (/work/pdns-rgacogne/pdns/recursordist/pdns_recursor+0x69ae78d)
```

**Comment by rgacogne** [comment]
Reproduced the initial issue using clang++ for now. What happens is that the recursor sets an empty hostname and `SSL_set_tlsext_host_name()` does not like that.

**Comment by rgacogne** [comment]
In case anyone was wondering, `X509_VERIFY_PARAM_set1_host` gracefully deals with an empty name.

**Comment by rgacogne** [comment]
> Trying to reproduce this locally yielded a new issue:
> 
> ```
> /usr/include/c++/11.1.0/bits/unique_ptr.h:179:32: runtime error: member call on null pointer of type 'struct __uniq_ptr_impl'
> Jan 31 11:58:49 Done priming cache with root hints
>     #0 0x555ed0fd5129 in std::__uniq_ptr_impl<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::reset(RecursorPacketCache*) /usr/include/c++/11.1.0/bits/unique_ptr.h:\
> 179
>     #1 0x555ed0fd5129 in std::__uniq_ptr_impl<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::operator=(std::__uniq_ptr_impl<RecursorPacketCache, std::default_delet\
> e<RecursorPacketCache> >&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:167
>     #2 0x555ed0fd5129 in std::__uniq_ptr_data<RecursorPacketCache, std::default_delete<RecursorPacketCache>, true, true>::operator=(std::__uniq_ptr_data<RecursorPacketCache, std::de\
> fault_delete<RecursorPacketCache>, true, true>&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:212
>     #3 0x555ed0fd5129 in std::unique_ptr<RecursorPacketCache, std::default_delete<RecursorPacketCache> >::operator=(std::unique_ptr<RecursorPacketCache, std::default_delete<Recursor\
> PacketCache> >&&) /usr/include/c++/11.1.0/bits/unique_ptr.h:371
>     #4 0x555ed0fd5129 in recursorThread(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /work/pdns/pdns/recursordist/rec-main.c\
> c:1931
>     #5 0x555ecf8c52b7 in serviceMain /work/pdns/pdns/recursordist/rec-main.cc:1650
>     #6 0x555ecf8c52b7 in main /work/pdns/pdns/recursordist/rec-main.cc:2496
>     #7 0x7ff02bf79b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
>     #8 0x555ecf8ec78d in _start (/work/pdns-rgacogne/pdns/recursordist/pdns_recursor+0x69ae78d)
> ```

That does not occur with clang's UBSAN, and I don't see any issue in the way we are setting a new value to a thread-local `std::unique_ptr` so I'm going to assume this is a bug in gcc's UBSAN.

**Comment by omoerbeek** [comment]
> It looks like `bool isNew` in `asyncresolve()` is used uninitialized when an exception occurs in `tcpconnect()`.

that looks wrong indeed.

**Comment by omoerbeek** [comment]
> Reproduced the initial issue using clang++ for now. What happens is that the recursor sets an empty hostname and `SSL_set_tlsext_host_name()` does not like that.

I'll look into passing the nameserver's name in, but form q quick glance it is not available in lwres.

**Comment by rgacogne** [comment]
> I'll look into passing the nameserver's name in, but from a quick glance it is not available in lwres.

I added a check so that `SSL_set_tlsext_host_name()` is not called when the hostname is empty so the tests should pass again. But it would be good to be able to pass the hostname at some point, yes :)

**Comment by rgacogne** [comment]
```
diff --git regression-tests.dnsdist/test_OutgoingDOH.py regression-tests.dnsdist/test_OutgoingDOH.py
index 217c885fe..3c3844d06 100644
--- regression-tests.dnsdist/test_OutgoingDOH.py
+++ regression-tests.dnsdist/test_OutgoingDOH.py
@@ -283,11 +283,17 @@ class TestOutgoingDOHOpenSSL(DNSDistTest, OutgoingDOHTests):
     addAction(SuffixMatchNodeRule(smn), PoolAction('cache'))
     """
 
+    @staticmethod
+    def sniCallback(sslSocket, sni, sslContext):
+        assert(sni == 'powerdns.com')
+        return None
+
     @classmethod
     def startResponders(cls):
         tlsContext = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
         tlsContext.set_alpn_protocols(["h2"])
         tlsContext.load_cert_chain('server.chain', 'server.key')
+        tlsContext.sni_callback = cls.sniCallback
 
         print("Launching DOH responder..")
         cls._DOHResponder = threading.Thread(name='DOH Responder', target=cls.DOHResponder, args=[cls._tlsBackendPort, cls._toResponderQueue, cls._fromResponderQueue, False, False, None, tlsContext])
diff --git regression-tests.dnsdist/test_OutgoingTLS.py regression-tests.dnsdist/test_OutgoingTLS.py
index c07be6633..628262150 100644
--- regression-tests.dnsdist/test_OutgoingTLS.py
+++ regression-tests.dnsdist/test_OutgoingTLS.py
@@ -146,10 +146,16 @@ class TestOutgoingTLSOpenSSL(DNSDistTest, OutgoingTLSTests):
     setWebserverConfig({password="%s", apiKey="%s"})
     """
 
+    @staticmethod
+    def sniCallback(sslSocket, sni, sslContext):
+        assert(sni == 'powerdns.com')
+        return None
+
     @classmethod
     def startResponders(cls):
         tlsContext = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
         tlsContext.load_cert_chain('server.chain', 'server.key')
+        tlsContext.sni_callback = cls.sniCallback
 
         print("Launching TLS responder..")
         cls._TLSResponder = threading.Thread(name='TLS Responder', target=cls.TCPResponder, args=[cls._tlsBackendPort, cls._toResponderQueue, cls._fromResponderQueue, False, False, None, tlsContext])
```
But that requires Python 3.7, and I'm not sure we have that in our CI?

**Review by Habbie — APPROVED** [review]

**Pull request merged**
